### ISSUE TITLE
Request: Merge getsentry/crashpad PR #101 to fix llvm-mingw arm64 crashpad builds

### ISSUE THREAD

**Issue by past-due** [getsentry/sentry-native#1002]
**Description**

llvm-mingw builds targeting arm64 did not succeed if crashpad was the selected backend

**Solution**

Crashpad fix PR: https://github.com/getsentry/crashpad/pull/101

(Once merged, the crashpad submodule in this repo will need to be updated to point the latest commits.)
```[tasklist]
### Tasks
- [x] Merge https://github.com/getsentry/crashpad/pull/101
- [ ] Merge https://github.com/getsentry/sentry-native/pull/1003 (to update submodule)
```

**Comment by past-due** [comment]
Thanks @supervacuus!

Would it be possible to issue a new sentry-native release with this included?

**Comment by supervacuus** [comment]
> Would it be possible to issue a new sentry-native release with this included?

I will release a new version in the first half of next week.

**Comment by supervacuus** [comment]
@past-due, [0.7.6](https://github.com/getsentry/sentry-native/releases/tag/0.7.6) is out.
