### ISSUE TITLE
codecov requires a token

### ISSUE THREAD

**Issue by supervacuus** [getsentry/sentry-native#1023]
I recently saw that Codecov no longer produces coverage reports in our PRs.

It looks like our token is no longer valid (or just missing?):

https://github.com/getsentry/sentry-native/actions/runs/10166682391/job/28117412853#step:14:47

Since Codecov often did not show a coverage report for reasons, I wasn't immediately aware that this was an authentication issue. I don't know how to fix this since I have no idea how the token setup works (and also have no access because that is probably a secret).

@kahest, @Swatinem, do you have any idea what can be done? 
Were other repos affected by this? 
Is the token a repo secret, or do we simply not have one (because I can't see a reference to a secret)? 
If we never had one, could it be that we didn't get a report when Codecov throttled (429) our uploads previously, and now they actually need one every time?
Can we get one?

**Comment by kahest** [comment]
@supervacuus the codecov token is managed centrally and available via `${{ secrets.CODECOV_TOKEN }}` - I guess we need to specify the token similar to other repos, e.g. https://github.com/getsentry/sentry-cocoa/blob/19b93f9bf33fa06d078bbf1b430ffb89e1696b93/.github/workflows/test.yml#L218
