### ISSUE TITLE
Wrong MIME type is sent for attachment

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry-native#1031]
**Description**

The SDK set the 'application/octet-stream' MIME Type for a .txt file, please see details in the JIRA ticket:
https://getsentry.atlassian.net/browse/FEEDBACK-2259

**When does the problem happen**

- [ ] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [e.g. Windows 10, 64-bit]
- Compiler: [e.g. MSVC 19]
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Steps To Reproduce**

**Log output**

**Comment by kahest** [comment]
related: https://github.com/getsentry/sentry/issues/76381
