### ISSUE TITLE
Stack traces seem to incorrectly end at function _sigtramp - leads to incorrect grouping

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry-native#1034]
**Description**

I've noticed that there are a lot of events (native crashes) being grouped together into one issue, specifically on MacOS.  Despite having different causes (from their logs and the panic message added to some of them), they are grouped since their stack traces seem to incorrectly end at the function _sigtramp. 

One delta I've observed is the number of dynamic libraries applied for the events stopping at _sigtramp (Screenshot1) and events that do not (screenshot2) - I see an extra dylib for the latter, do you happen to have context on this?

![Image](https://github.com/user-attachments/assets/504fad0a-4aa4-44cd-906f-e4788f6ea6d4)

![Image](https://github.com/user-attachments/assets/3bd22e90-d828-4803-8889-ecbc9c8e41bb)

**When does the problem happen**

- [ ] During build
- [ ] During run-time
- [x] When capturing a hard crash

**Environment**

- OS: macOS
- Compiler: [e.g. MSVC 19]
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Steps To Reproduce**

**Log output**

**Comment by markushi** [comment]
Hey @kpujjigit, thanks for reaching out! Could you share a few more details with us:

- OS version of the system where _sigtramp occurs
- If possible, an example stack trace
- Is there any specific reason you're using the inproc backend instead of crashpad?

**Comment by kpujjigit** [comment]
> Hey [@kpujjigit](https://github.com/kpujjigit), thanks for reaching out! Could you share a few more details with us:
> 
> * OS version of the system where _sigtramp occurs
> * If possible, an example stack trace
> * Is there any specific reason you're using the inproc backend instead of crashpad?

Shared the above internally with @loewenheim :)

**Comment by Dav1dde** [comment]
Unfortunately this is a limitation of the implementation and we cannot improve this behaviour without significant efforts.
