### ISSUE TITLE
SIGSEGV possible via `sentry_envelope_write_to_path` when path is invalid

### ISSUE THREAD

**Issue by mitchellh** [getsentry/sentry-native#1035]
**Description**

SIGSEGV possible through `sentry_envelope_write_to_path`

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

macOS, but probably doesn't matter.

**Steps To Reproduce**

If you provide a path using a directory that doesn't exist, then `sentry__filewriter_new` returns NULL. The `sentry_envelope_write_to_path` never checks for a null result and attempts to use the `fw`.

**Comment by supervacuus** [comment]
Ouch, thanks for the report!

**Comment by supervacuus** [comment]
The fix will be released in [0.7.9](https://github.com/getsentry/publish/issues/4260).
