### ISSUE TITLE
Consider per-report Consent Checking

### ISSUE THREAD

**Issue by icedtoast** [getsentry/sentry-native#110]
I have some patches I would like to contribute which add basic consent prompt support to Windows with crashpad.

This patchset requires patching crashpad - how do you want me to add that to your build process?

**Comment by mitsuhiko** [comment]
Is your idea to just defer the uploader or also to put the entire crash collection behind the consent prompt? We maintain patches to crashpad on our own repo here so you can also send a PR there: Oesterreichische Hagelversicherung

**Comment by mitsuhiko** [comment]
I added basic support in #116 but I want to see if the flow can be improved.

**Comment by icedtoast** [comment]
Thanks, yes the idea is just defer uploading until consent is given.

#116 is close to what I have, although it is "global", where I was wanting support for asking consent on a per-report basis. I implemented this passing a path to a DLL which crashpad would load and then call before uploading each report.

Would that style (per-report consent) be something you were wanting to implement? 
I'll have to rework my patchset in light of #116, but if you are already working in this area I'm happy to drop my local changes in favor of your solution.

**Comment by mitsuhiko** [comment]
I think it would be nice to have this on a per-report basis somehow. The main problem is that since crashpad is out of process and everything else is in process it's kinda ugly to find a backend independent implementation for that.

Would be very happy to accept something though that makes it possible.

**Comment by kahest** [comment]
closing as superseded by newer issue with more context: https://github.com/getsentry/sentry-native/issues/110
