### ISSUE TITLE
[VC++2019/CMake] __sentry-breadcrumb1 / __sentry-breadcrumb2 : No such file or directory (2)

### ISSUE THREAD

**Issue by Amphaal** [getsentry/sentry-native#111]
Maybe related to #84 ? Many thanks in advance for your help !

### Context
I'm trying to trigger a sentry event from a simple exception, to feed my Sentry dockerized environment. My unsecure HTTP Sentry app is based on the "onpremise Sentry" project, as of https://github.com/getsentry/onpremise/commit/9ec53c33502199b7dd3e28ccad5676ca539a6cc6, with no changes to the default configuration files.

### I'm using 
- VC++2019 (16.4.1)
- CMake (3.16.0)
- sentry-native 0.1.4 from "Releases"
    - using "gen_windows" (linking crashpad_handler.vcxproj  + sentry_crashpad.vcxproj)

### Issue

After initiating Sentry as of : 

```
auto options = sentry_options_new();
sentry_options_set_dsn(options, SENTRY_ENDPOINT);

QString environement = "Production";
#ifdef _DEBUG
    environement = "Debug";
#endif
sentry_options_set_environment(options, environement.toStdString().c_str());

sentry_options_set_release(options, GITHUB_VERSION_NAME);
sentry_options_set_debug(options, 1);

//crashpad integration
sentry_options_set_handler_path(options, CRASHPAD_HANDLER_NAME);
// auto dbStr = AppContext::getAppDataLocation() + "/sentry_db";
// sentry_options_set_database_path(options, dbStr.toStdString().c_str());

sentry_init(options);
```

...and triggering the same kind of exception as #84, my program shuts down as expected, but outputs unexpected logs : 

```
[sentry] crash handler enabled (reporting to http://ec083db6fedc4b64b0233ddb1fb9551f:@lvwl.to2x.ovh:9000/1)
[sentry] started client handler.
[sentry] starting background worker
[11964:7372:20191212,034649.005:ERROR file_io_win.cc:161] CreateFile ./.sentry-native\sentry-runs\1576118808-1100518007\__sentry-breadcrumb1: Le fichier spécifié est introuvable. (2)
[11964:7372:20191212,034649.005:ERROR file_io_win.cc:161] CreateFile ./.sentry-native\sentry-runs\1576118808-1100518007\__sentry-breadcrumb2: Le fichier spécifié est introuvable. (2)
```

### About the issue 
- Release and Debug executables produce this behavior
- `sentry_shutdown()` cannot be reached after the error, even if I try to :
   - define a call with `std::set_terminate` callback
   - catch the exception with try-catch, then call it

### What happened
- a valid minidump file is created at `.sentry-native\reports`, containing expected data
- 3 files are created at `.sentry-native\attachments\xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx`
   - __sentry-breadcrumb1, empty 0 Ko file
   - __sentry-breadcrumb2, empty 0 Ko file
   - __sentry-event, containing : 
`‰¨contexts€«environmentªProduction¥extra€¥level¥error¨platform¦native§release­rpgrpz@0.20.5£sdkƒ¤name­sentry-native¨packages‘‚¤name¾github:getsentry/sentry-native§version¥0.1.4§version¥0.1.4¤tags€¤userÀ`
- 1 file is created at  `.sentry-native\sentry-runs\1576118808-1100518007` : 
    - `__sentry-event`, same content as above.
- my Sentry app also generated 2 events !
    - AttributeError/api/{project_id}/minidump/ - 'WSGIRequest' object has no attribute 'user'
    - UnreadablePostError/api/{project_id}/minidump/ - unable to receive chunked part

![image](https://user-images.githubusercontent.com/13903151/70679740-55e58a00-1c96-11ea-9404-e2be177505fe.png)
![image](https://user-images.githubusercontent.com/13903151/70679758-6433a600-1c96-11ea-825f-c1b0f34a53ba.png)

**Comment by mitsuhiko** [comment]
I think we need to separate the two errors here. Can you check what happens if you send an event to a free account on sentry.io instead? The chunked issue seems unrelated here and might be a setup problem on the onpremise side.

**Comment by Amphaal** [comment]
You were right, the single expected event was sent correctly to the Sentry.io, with no additional events. However, errors still appear in the log : 

```
[sentry] crash handler enabled (reporting to https://xxxxxxxxxxxxxxxxxxx:@sentry.io/1860035)
[sentry] started client handler.
[sentry] starting background worker
[11820:16992:20191219,000430.406:ERROR file_io_win.cc:161] CreateFile ./.sentry-native\sentry-runs\1576710270-285334985\__sentry-breadcrumb1: Le fichier spécifié est introuvable. (2)
[11820:16992:20191219,000430.406:ERROR file_io_win.cc:161] CreateFile ./.sentry-native\sentry-runs\1576710270-285334985\__sentry-breadcrumb2: Le fichier spécifié est introuvable. (2)
```

The event report in the Sentry.io app did not seems to be misformed or missing informations, so I guess these errors do not break the report sending functionality ?

**Comment by mitsuhiko** [comment]
Yeah. The error is in fact a warning. We can proactively create an empty file to silence it. I will do that.

**Comment by maxp1256** [comment]
@Amphaal I'm getting the same error (AttributeError & UnreadablePostError) and the dump isn't showing up in my onprem Sentry. Did you resolve your problem? What did you change in your configuration? Uploading to sentry.io does work without a problem.

**Comment by Amphaal** [comment]
> @Amphaal I'm getting the same error (AttributeError & UnreadablePostError) and the dump isn't showing up in my onprem Sentry. Did you resolve your problem? What did you change in your configuration? Uploading to sentry.io does work without a problem.

I gave up for now, as my Azure free trial expired and my home server is too old to run Sentry 10. I still have no clue on why it did not work tho, but I might try again later this year 😅
