### ISSUE TITLE
Compile as static library ?

### ISSUE THREAD

**Issue by Mecanik** [getsentry/sentry-native#113]
There is no way to integrate this as static lib ? I compiled with /MT as well (with VS) but my application still asks for sentry.dll.

This is **very inconvenient**, especially due to the nature of my software. 

A solution would be appreciated.

Side notes: 

- Why is the code so ugly ?! I mean... it's awful. I`m not expecting it to be perfect, but it looks like it was written in a rush...
- Why is there so much C and C++ combined ?...
- Too many strings in plain, for security apps this is a risk and concern...
- Plenty more to say really...

Anyway, a solution to build as static lib is appreciated at this point; the rest... no further comments.

Thanks

**Comment by mitsuhiko** [comment]
> There is no way to integrate this as static lib ? I compiled with /MT as well (with VS) but my application still asks for sentry.dll.

The main backend is crashpad which cannot be used as a static library since it has an executable. We can probably look into supporting static builds for other backends but no work went into this yet.

> Why is there so much C and C++ combined ?...

There is no C code, but we only expose a C ABI so that has to be exposed.

Not sure what the "too many strings in plain" refers to.

**Comment by Mecanik** [comment]
> The main backend is crashpad which cannot be used as a static library since it has an executable. We can probably look into supporting static builds for other backends but no work went into this yet.

"Probably look into it" ? Man, this should have been within your first things to do... I don't want/need to tell you how this cannot be used safely in commercial apps since anyone could just replace the DLL and load malicious code to crack your software or worse... and nobody would like to create hash/crc for this.

> There is no C code
Oh is that right ? I`m just going to stop right here... no point arguing.

> Not sure what the "too many strings in plain" refers to.

What does a "plain string" tell you ? Everything. This cannot be happening in a commercial app, anyone could see what/where/how by just looking at the strings. 

The least you could have done is place all strings in one place and allow the customer to easily encrypt them all.

**A final note:**

I was pleasantly surprised and got my hopes up to use sentry.io in multiple apps, but after looking at your "windows native sdk" - no thanks.

No idea what's going on with you guys, why is half of the code "good" and half "rubbish"; but honestly I expected more from a company that just got funded "$41 million".

**Comment by BYK** [comment]
Hi @Mecanik,

As much as we appreciate you pointing out things to improve in the code and the project, the way you express your thoughts are violating our code of conduct: https://github.com/getsentry/.github/blob/master/CODE_OF_CONDUCT.md#our-standards

Specifically, your comments are in violation of the following items:

>Trolling, insulting/derogatory comments, and personal or political attacks

>Other conduct which could reasonably be considered inappropriate in a professional setting

Please keep the conversation focused on the code and possible solutions and not about people or the people behind the code. We are all trying to achieve a better product here and working together makes it a lot easier and faster.

Thanks a lot for your cooperation 🙂
