### ISSUE TITLE
Implementing a transport in C++

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-native#162]
Hi there,

I just started playing with sentry-native (finally !) and got it hooked in a very basic way to a command line tool (building on macOS only for now). I love the simple C api and the new 'inproc' mode ; it would be great if we could use this mode on iOS/Android as it would simplify our life a bit, not having to build breakpad/crashpad. (that's a tangent).

I'd like to be able to HTTP upload the report to sentry using our own library, is there some basic doc on doing so dynamically ?

It looks like all I need is to provide a 'sentry_transport_t' (I'm looking at the curl example) 

```
sentry_transport_t *sentry__new_libcurl_transport(void);
```

```
sentry_transport_t *
sentry__new_libcurl_transport(void)
{
    SENTRY_DEBUG("initializing curl transport");
    sentry_transport_t *transport = SENTRY_MAKE(sentry_transport_t);
    if (!transport) {
        return NULL;
    }

    struct transport_state *state = new_transport_state();
    if (!state) {
        sentry_free(transport);
        return NULL;
    }

    transport->data = state;
    transport->free_func = free_transport;
    transport->send_envelope_func = send_envelope;
    transport->startup_func = start_transport;
    transport->shutdown_func = shutdown_transport;

    return transport;
}
```

That thing is used here, called from sentry_options_new
```
    opts->transport = sentry__transport_new_default();
```

Is all we need to do to create a new options, and set override the opts->transport argument ?

Thanks !

**Comment by Swatinem** [comment]
You can use `sentry_options_set_transport` to specify your own transport, and `sentry_new_function_transport` to create a very simple callback-based transport.

You use it like this:

```c
        sentry_options_set_transport(
            options, sentry_new_function_transport(print_envelope, NULL));
```

All you can do right now with that envelope is to serialize it to a string, and then send it as a `Content-Type: application/x-sentry-envelope` to the store endpoint. See https://docs.sentry.io/development/sdk-dev/overview/#parsing-the-dsn for more details.

We are thinking about maybe exposing the internal `sentry__envelope_for_each_request` method in the future to make this a bit simpler for external users.

https://github.com/getsentry/sentry-native/blob/e995329629fab5a9379aca0bc78916a1d96a7d86/src/sentry_envelope.c#L412

I hope this answers your question. Feel free to reopen.

**Comment by agauniyal** [comment]
@Swatinem how do I exactly send the serialized envelope information to required DSN? Suppose my DSN looks like - `https://someid@abc.ingest.sentry.io/123`, do I send a post request to it?
And how do I send the data I get from `char* s = sentry_envelope_serialize(envelope, &size_out);`? I see it's something like - 
```json
{"dsn": "...", "event_id": ""}
{"type":"event","length":...}
{"event_id":"...",.................................................}
```
From the previous comment, I notice I've to set `Content-Type: application/x-sentry-envelope` header but don't know about the string(containing 3 separate JSON) above.

For now, I've tried sending POST and PUT request to above DSN URL, with mentioned header set and that entire thing as raw string in body. The response I get is 404.

**Comment by Swatinem** [comment]
The URL in the post above does not seem to work, anymore, here is an updated one: https://develop.sentry.dev/sdk/overview/#parsing-the-dsn
The envelope docs also give you the POST url: https://develop.sentry.dev/sdk/envelopes

You have to parse the DSN and extract the authentication header from that yourself, as well as to create the actual envelope url from it. That functionality is unfortunately not exposed publicly from the SDK.

**Comment by agauniyal** [comment]
@Swatinem thanks! you correctly identified the problem of URL not working, thanks for providing the updated URL. I also managed to figure everything out by going through the sentry_example.c and putting curl_verbose = 1 :smile:
