### ISSUE TITLE
Generate mini dump without crashing ?

### ISSUE THREAD

**Issue by conradjones** [getsentry/sentry-native#163]
Can I send a stack trace back without actually crashing the application ? I'd like to gracefully handle some errors but get a stack trace to show why it occurred

**Comment by Swatinem** [comment]
You can use the following experimental APIs for that purpose:

* `sentry_event_value_add_stacktrace`
* `sentry_unwind_stack`
* `sentry_unwind_stack_from_ucontext`

Unwinding from a specific pointer or `from_ucontext` does not correctly work on all platforms right now however.

I would just recommend using `sentry_event_value_add_stacktrace` for your usecase.

**Comment by conradjones** [comment]
Thanks I'll give it a go
