### ISSUE TITLE
The lib doens't include enougth mini chromium and zlib resources

### ISSUE THREAD

**Issue by rafagan** [getsentry/sentry-native#171]
If you try to simply build using the cmake commands described in README.MD, it's complains about missing resources in theese third party srcs.

**Comment by Swatinem** [comment]
Are you using the release bundle, or from git? If you are using git, make sure you check out recursive submodules as well.

**Comment by rafagan** [comment]
Thank you! One suggestion: Put the text about git submodules in README.MD before the Cmake commands.
