### ISSUE TITLE
Add ignore SAFESH flags in cmake

### ISSUE THREAD

**Issue by rafagan** [getsentry/sentry-native#173]
When I run cmake the following error occurs:

PS C:\Users\rafagan\Desktop\sentry-native> cmake --build build --parallel
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  getopt.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\getopt.lib
  zlib.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\zlib.lib
  mini_chromium.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\mini_chromium.lib
  crashpad_compat.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\crashpad_compat.lib
  crashpad_tools.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\crashpad_tools.lib
  crashpad_util.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\crashpad_util.lib
  crashpad_client.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\crashpad_client.lib
  crashpad_snapshot.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\crashpad_snapshot.lib
  crashpad_minidump.vcxproj -> C:\Users\rafagan\Desktop\sentry-native\build\crashpad_minidump.lib
crashpad_util.lib(capture_context_win.obj) : error LNK2026: module unsafe for SAFESEH image. [C:\Users\rafagan\Desktop\
sentry-native\build\external\crashpad\handler\crashpad_handler.vcxproj]
crashpad_util.lib(safe_terminate_process.obj) : error LNK2026: module unsafe for SAFESEH image. [C:\Users\rafagan\Deskt
op\sentry-native\build\external\crashpad\handler\crashpad_handler.vcxproj]
C:\Users\rafagan\Desktop\sentry-native\build\crashpad_handler.exe : fatal error LNK1281: Unable to generate SAFESEH ima
ge. [C:\Users\rafagan\Desktop\sentry-native\build\external\crashpad\handler\crashpad_handler.vcxproj]

Then I added the following lines and the errors had gone:

    SET(CMAKE_CXX_FLAGS           "${CMAKE_CXX_FLAGS} /D \"SAFESEH:NO\"")
    SET(CMAKE_EXE_LINKER_FLAGS    "${CMAKE_EXE_LINKER_FLAGS} /SAFESEH:NO")
    SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /SAFESEH:NO")
    SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} /SAFESEH:NO")

**Comment by jan-auer** [comment]
@Swatinem It looks like we need to bring back this: https://github.com/getsentry/sentry-native/pull/64
