### ISSUE TITLE
Messages are not reaching server

### ISSUE THREAD

**Issue by rafagan** [getsentry/sentry-native#175]
After following the samples available [here](https://docs.sentry.io/platforms/native/), I could achieve the following logs in my application:

[sentry] starting transport
[sentry] starting background worker thread
[sentry] starting backend
[sentry] starting crashpad backend
[sentry] started crashpad client handler.
[sentry] capturing event
[sentry] merging scope into event
[sentry] adding attachments to envelope
[sentry] sending envelope
[sentry] submitting task to background worker thread
[sentry] shutting down transport
[sentry] shutting down background worker thread
[sentry] submitting task to background worker thread

Everything seems to work ok, but I'm not receiving the logs in sentry.io, and everything seems ok with my DSN. What could possible be happening?

**Comment by Swatinem** [comment]
I’m wondering, are you configuring the DSN via code or ENV?
Hm, since you get logs about the background worker thread, that does sound correct.
Otherwise, you could check how you configured user consent?

**Comment by rafagan** [comment]
I'm configuring DSN via code. I not configured the user consent:

> sentry_options_t *options = sentry_options_new();
>     sentry_options_set_dsn(options, "https://7c314d0f84c043b5982c254b46ade16c@sentry.io/3775493");
>     sentry_options_set_debug(options, true);
>     sentry_options_set_handler_path(options, "C:/usr/local/bin/crashpad_handler.exe");
>     sentry_options_set_database_path(options, "sentry-db-directory");

**Comment by rafagan** [comment]
Any hint about it?
