### ISSUE TITLE
Curl not found on Windows

### ISSUE THREAD

**Issue by rafagan** [getsentry/sentry-native#179]
When I try building in Windows with Visual Studio 16 2019 the following error occurs:

$ cmake -B build -DSENTRY_BACKEND=crashpad
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.24.28319.0
-- The CXX compiler identification is MSVC 19.24.28319.0
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindCURL.cmake:169 (find_package_handle_standard_args)
  CMakeLists.txt:146 (find_package)

How can I solve that?

**Comment by rafagan** [comment]
Maybe adding this line solves the problem?

`set(CURL_LIBRARY "-lcurl")`

**Comment by Swatinem** [comment]
I will disable curl by default on windows in #177, since windows has its own http handling.

If you want to try, use `cmake -B build -DSENTRY_CURL_SUPPORT=OFF` in the meantime.

**Comment by rafagan** [comment]
Ok, it has compiled.

Now, when I run the following command:


cmake --install build --prefix install

It not founds crashpad_handler.exe

-- Install configuration: "Release"CMake Error at build/cmake_install.cmake:53 (file):  file INSTALL cannot find "C:/Users/rafagan/OneDrive/Área de  Trabalho/sentry-native/build/external/crashpad/handler/Release/crashpad_handler.exe":  No error.

Ráfagan Sebástian de Abreu
________________________________
De: Arpad Borsos <notifications@github.com>
Enviado: domingo, 15 de março de 2020 18:05
Para: getsentry/sentry-native <sentry-native@noreply.github.com>
Cc: Ráfagan Abreu <rafagansa@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [getsentry/sentry-native] Curl not found on Windows (#179)


I will disable curl by default on windows in #177<https://github.com/getsentry/sentry-native/pull/177>, since windows has its own http handling.

If you want to try, use cmake -B build -DSENTRY_CURL_SUPPORT=OFF in the meantime.

**Comment by Swatinem** [comment]
Interesting. I will try to reproduce that tomorrow.

**Comment by rafagan** [comment]
It only works if you run the following sequentially:

`cmake -B Release -DSENTRY_BACKEND=crashpad -DSENTRY_CURL_SUPPORT=OFF`
`cmake --build Release --parallel --config Release`
`cmake --install Release --prefix install`

**Comment by Swatinem** [comment]
well thats expected ;-)

**Comment by Swatinem** [comment]
Ah yes… so cmake builds `Debug` by default, but `cmake --install` tries to install `Release` by default. Thats where that error comes from. It is a bit confusing :-(
