### ISSUE TITLE
Report application hangs in addition to crashes

### ISSUE THREAD

**Issue by maxp1256** [getsentry/sentry-native#185]
Hello,

we're using sentry crashpad_handler successfully to report application crashes (with minidumps). Now we've realized that there are also some "application hangs" reported in the windows eventlog which are not reported to our sentry instance. Is there a parameter/option to create a minidump on hangs too?

Thanks in advance

**Comment by Swatinem** [comment]
We plan to expose a method to manually capture a minidump.

But I don’t think we detect hangs right now.

**Comment by maxp1256** [comment]
Do you know any documentation about these error? Who and how is detecting and logging it?

**Comment by Swatinem** [comment]
I have no idea to be honest, will have to look at all this myself first.

**Comment by Mixaill** [comment]
I think it should be covered with #735
