### ISSUE TITLE
Provide Breakpad and inproc backends for Windows

### ISSUE THREAD

**Issue by sseyod** [getsentry/sentry-native#190]
Hi!

My remaining problem now is that I'm not seeing any crashes reported in the Browser.

NB I'm provoking a crash in response to a menu item within the app, which calls this code:

```
      // Force crash report for sentry.io
      int* crashPtr = nullptr;
      *std::launder(crashPtr) = 0;
```

The app does indeed crash as expected, but for the avoidance of doubt, I see no report about this on the sentry.io website.

I've enabled this line as requested:
sentry_options_set_debug(options, 1);

NB I don't know if this is relevant, but I've noticed that, whether or not I crash the app, or have the sentry_options_set_debug call, I'm no longer seeing anything reported on the sentry.io site sent from sentry_capture_event(...) ... *unless* I modify the "message" parameter in the call below.
In otherwords, only the first call is reported on the site. Subsequent calls aren't reported on the site.

  sentry_capture_event(sentry_value_new_message_event(
    /*   level */ SENTRY_LEVEL_INFO,
    /*  logger */ "custom",
    /* message */ "Prepare to crash..."
  ));

Hopefully you see something useful on the server! :)

Best wishes,

Pete

**Comment by jan-auer** [comment]
Thanks for the information. I can see two separate issues here.

1. Your crashes are not arriving in Sentry. What do the debug logs say when you start up the app? I'm assuming you're running on Windows with the Crashpad backend (default). Provided you've set up the SDK with a valid DSN, crashpad should be uploading immediately after the crash. Based on the SDK's debug logs, we can investigate further.

2. Subsequent calls are not reported independently of whether the app crashes. There is a known issue that if the app crashes while sending an event (which is done in a background thread), you might lose the event based on the progress. However, this seems unrelated, as you're only ever getting one event through. Can you observe similar behavior when building the [`example`](https://github.com/getsentry/sentry-native/blob/c86a6271de131e8599e684c2fee83e8389916ddf/examples/example.c) program, included in the package?

**Comment by sseyod** [comment]
Hi!

With respect to 1) I presume that is what I'm doing... I'm just running with a vanilla configuration.
cmake . -DBUILD_SHARED_LIBS=OFF

I'm sure the DSN must be correct, as otherwise I presume I wouldn't see *anything* from sentry_capture_event ...?!

Just for the avoidance of doubt, my understanding is that this version of Sentry native doesn't require any separate .exe to accompany the application (something which isn't an option for Windows 10 store apps anyhow); so I've been presuming that the crashpad backend is handled within your clever library rewrite; anyhow, just thought I should double-check my understanding of app configuration with you!

NB: is there something I need to do to access the "SDK's debug logs" on my side, or by that do you mean logs that you will have received (from the app) on the server side?

With respect to 2), I presume you mean for me to change the example program to use my app's  DSN, and just see what happens? No worries if so, I'll get that a try and report back!

Thanks for all your help with this,

Pete

**Comment by jan-auer** [comment]
Ah, sorry, I should have clarified a few things :) Unfortunately, I don’t have any experience with Windows 10 Store apps yet. 

By SDK debug logs I meant output on standard out. When you enable debug in options, the SDK starts verbose logging of several operations, such as initializing the crash handler and sending events.

Now, you already pointed to the issue. With the crashpad backend, it is indeed required to ship the crashpad_handler.exe. This is the process that creates the crash dump and sends it to Sentry. This part, we certainly did not rewrite. The debug logs on stdout will likely show an error that this executable cannot be started. We mention this briefly in docs and in the readme (see https://github.com/getsentry/sentry-native#compile-time-options), but we can surely improve clarity around this.

Your regular events are getting through because we send them in-process. There is also an in-process backend that does not require the crashpad handler, but it is not implemented for Windows yet.

Is there any way to ship that second executable alongside your windows 10 app? Otherwise, you will have to hold out until we support either the Breakpad backend or the in-process backend for Windows.

**Comment by sseyod** [comment]
Hi @jan-auer,

Many thanks for your detailed response; that is really appreciated.

Right, that makes sense. Yes, I'm sorry to report that (to the best of my knowledge...) Windows 10 Store applications need to be "monolithic" - they can't run installers or have separate executable components. NB: as said, this is to the best of my knowledge - if anybody reading this knows otherwise, do please share what you know!!

So, it sounds like for crash reporting to work with Windows 10 Store apps, this will required your in-process backend. I'd hoped that had now arrived in Sentry Native :) but of course I understand you can't do everything at once. For some reason, Microsoft's own App Center crash reporting doesn't support C++ apps, so there is certainly an opportunity here for you!

I'm very happy if I've been able to help you out to some extent thus far in your support for C++  Windows 10 apps, and would certainly appreciate if you could let me know at some point, if you're able to get an in-process solution in a testable version - it'd be a privilege to help you test that out in a "real world" app.

Anyhow: do please let me know if you need any more information!

Best wishes,

Pete

**Comment by Swatinem** [comment]
That sure is an interesting limitation.
So you are limited to one `.exe`, but can you still create sub/sibling processes? If so, we might just ship the out-of-process handler as a static library with an exported `main(argc,argv)` function, which you have to invoke yourself based on some argv maybe?

Not sure how feasible that is. In any case, I don’t think this is high priority for us right now.

**Comment by sseyod** [comment]
Hi @Swatinem,

The Windows 10 Store C++ apps are configured in a very specific way. I'll try to give you the necessary background info in this post.

The style of C++ app in question, are Windows apps using "Windows Application Packaging Projects" to deliver them through the Windows Store.

See https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net for info on how to do this. It is certainly pretty easy to configure a C++ app for deployment through the Windows 10 store using this approach.

So, assuming you have a simple test C++ app for Windows, it is easy enough to wrap-up like this, and see what the options might be for Sentry native.

Hoping this info all helps.

Best wishes,

Pete

**Comment by Swatinem** [comment]
Both breakpad and inproc have just landed in master 🎉

**Comment by sseyod** [comment]
Hi @Swatinem,

Thanks for the information.

Your "readme" file says this:

<blockquote>breakpad: This uses the in-process breakpad handler. It is currently only supported on Linux and Windows, and used as the default on Linux.

inproc: A small in-process handler which is supported on all platforms except Windows, and is used as default on Linux and Android.</blockquote>

So: am I correct in saying that by using the <i>breakpad</i> option for Windows, we should now be able to add crash reporting to Windows 10 apps (which doesn't support separate processes, but of course supports multiple threads!)

Best wishes,

Pete

**Comment by Swatinem** [comment]
Not quiiiiite yet. The backends have been merged to master, as you pointed out, I would have to update the README still. And prepare a new release in the following days.

**Comment by sseyod** [comment]
Hi @Swatinem,

I thought I should check-in again, and see if we're any closer yet?!

Best wishes,

Pete

**Comment by Swatinem** [comment]
Aiming for this week ;-)

**Comment by sseyod** [comment]
Awesome 👍 :)

**Comment by sseyod** [comment]
Hi @Swatinem, hoping you're well. Has this now landed?! :) Pete

**Comment by sseyod** [comment]
@Swatinem well, I've dived-in anyhow, and can confirm that it seems to be working. I'll let you know if I have any problems.

**Comment by Swatinem** [comment]
👍 good to hear!

**Comment by sseyod** [comment]
Thanks to you and your team for all your work on this - I'm very happy :-)

Pete
