### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by Binabran** [getsentry/sentry-native#195]
I'm currently having trouble building with the crashpad back-end on windows vs2019, the build arguments are: cmake --build build  --parallel. Error output as follows: 
 
  Assembling C:\psource\Conan\conan\recipes\Sentry\New folder\external\crashpad\util\misc\capture_context_win.asm...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB3686: Unable to create Xaml task.  Compilation failed.   [C:\psource\Conan\conan\recipes\Sentry\New folder\build\external\crashpad\util\crashpad_util.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB3686: Source file 'C:\WINDOWS\ TEMP\fc4fjwnf.0.cs' could not be found [C:\psource\Conan\conan\recipes\Sentry\New folder\build\external\crashpad\util\crashpad_util.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB3686:  [C:\psource\Conan\conan \recipes\Sentry\New folder\build\external\crashpad\util\crashpad_util.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): error MSB4175: The task factory "XamlTaskFactory" could not be loaded from the assembly "Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Object reference not set  to an instance of an object. [C:\psource\Conan\conan\recipes\Sentry\New folder\build\external\crashpad\util\crashpad_util.vcxproj]

Any thoughts on what I'm missing?

building with no back-end works fine

**Comment by Swatinem** [comment]
> error MSB3686: Source file 'C:\WINDOWS\ TEMP\fc4fjwnf.0.cs' could not be found

That looks super strange. No idea where that comes from.

@Binabran since you have `conan` all over your log, are you using that to fetch the sources?
I’m not quite sure how it works.
Are you using the release archive or a git checkout?

CC @madebr since you were working on conan support, right?
CC @Amphaal since you made some asm related changes in the crashpad repo.

**Comment by Binabran** [comment]
> Are you using the release archive or a git checkout?

I am using Conan, I'm using release 0.2.1 archive for now. As mentioned it seems to build ok with no backend so not sure if i'm missing something that's required.

**Comment by madebr** [comment]
@Binabran Can you please try building sentry-native using the conan recipe in my fork?
https://github.com/madebr/sentry-native/tree/sentry_conan
Can you post the *full output* to a gist?
I just successfully built on vs2017 with the following options:
```
[full_options]
    backend=crashpad
    build_examples=True
    build_tests=True
    shared=False
    transport=winhttp
```

@Swatinem Are you interested in a adding a conan recipe to your repo?

**Comment by Amphaal** [comment]
Well since our OP @Binabran is using VS2019, ml64.exe should be able to compile the MASM files without problems. The issue lies elsewhere :-/

**Comment by Swatinem** [comment]
> Are you interested in a adding a conan recipe to your repo?

Wasn’t the conclusion in #79 that maintaining this in the central index would be a better idea?

We can add one, sure, but without any guarantees that it will be supported.

**Comment by madebr** [comment]
> > Are you interested in a adding a conan recipe to your repo?
> 
> Wasn’t the conclusion in #79 that maintaining this in the central index would be a better idea?
> 
> We can add one, sure, but without any guarantees that it will be supported.

Oops, I did not see that issue. It makes sense to keep it in the central index.

**Comment by Binabran** [comment]
Hey, Just to provide an update on this, the issue seems to be with crashpad and was caused by attempting to build it remotely. Have managed to build it properly locally, thank you for your help, It works fine with my script and yours @madebr

**Comment by Swatinem** [comment]
Thanks for circling back, I was close this then.
