### ISSUE TITLE
Can't upload crash dump on linux 

### ISSUE THREAD

**Issue by Garey27** [getsentry/sentry-native#211]
Hi.

I was testing sentry-native and found that it doesn't upload .dmp and didn't make associated report when SEGFAULT happens. Even in sentry-example.

Capture events is work (capture-multiple arg) gives me messages in panel.

Here additional log from ./sentry_example log crash:

> [sentry] starting transport
> [sentry] starting background worker thread
> [sentry] background worker thread started
> [sentry] starting backend
> /.sentry-native/6bea685e-c08f-40ca-b71b-66ce4be5c9f0/69fd3c8f-da54-4309-8927febb-c5f0b59d.dmp
> [sentry] capturing event
> [sentry] merging scope into event
> [sentry] trying to read modules from /proc/self/maps
> [sentry] read 26 modules from /proc/self/maps
> [sentry] adding attachments to envelope
> [sentry] sending envelope
> [sentry] serializing envelope into buffer
> [sentry] Dumped 0 in-flight envelopes to disk
> Segmentation fault (core dumped)

As you can see I've added line to sentry_backend_breakpad.cpp to `sentry__breakpad_backend_callback` for logging dump_path and set `sleep(15)` after log to check file exists, and file was exists!

I think there something wrong with CURL or transport protocol, because this line: 

> Dumped 0 in-flight envelopes to disk.

in sentry_example i just add DSN:

> 
> int
> main(int argc, char **argv)
> {
>     sentry_options_t *options = sentry_options_new();
> 
>     sentry_options_set_environment(options, "Production");
>     sentry_options_set_release(options, "test-example-release");
>     sentry_options_set_dsn(
>         options, "http://8ccf59c0c63b40a7b9c63daced68b309@localhost:9000/2");
> 
>     if (has_arg(argc, argv, "log")) {
>         sentry_options_set_debug(options, 1);
>     }
>     ...

**Comment by Swatinem** [comment]
> Dumped 0 in-flight envelopes to disk.

That is only for things that are queued for sending.

Also, that log is printed *after* the actual crash has been written to disk. Which means:
In your case, the `.sentry-native/6bea685e-c08f-40ca-b71b-66ce4be5c9f0` folder should include a `XXX.envelope` file. That file is submitted on *restart*.

Also, which version of sentry are you running on `localhost`? The `.envelope` support so far is only available for the hosted `sentry.io` service. Or if you use the development version when self-hosting.

**Comment by Garey27** [comment]
Thank You for clarification.
Now i see where its fails:

> * Mark bundle as not supporting multiuse
> < HTTP/1.1 400 Bad Request
> < Content-Length: 132
> < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
> < X-Content-Type-Options: nosniff
> < Content-Language: en
> < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
> < X-Sentry-Error: Bad data decoding request (UnicodeDecodeError, 'utf8' codec can't decode byte 0x93 in position 8830: invalid start byte)
> < Vary: Accept-Language, Cookie
> < Expires: Wed, 01 Apr 2020 02:35:17 GMT
> < X-XSS-Protection: 1; mode=block
> < Allow: GET, POST, HEAD, OPTIONS
> < Cache-Control: no-cache, no-store, must-revalidate, max-age=0
> < Access-Control-Allow-Origin: *
> < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
> < Content-Type: application/json
> < X-Frame-Options: deny
> < 
> {"error":"Bad data decoding request (UnicodeDecodeError, 'utf8' codec can't decode byte 0x93 in position 8830: invalid start byte)"}*

I will try on sentry.io service and see is this are onpremise problem.

**Comment by Garey27** [comment]
Yes, on sentry.io works as excepted.
