### ISSUE TITLE
sentry_modulefinder_windows does not cater for changes in dynamically loaded modules

### ISSUE THREAD

**Issue by mcdurdin** [getsentry/sentry-native#213]
If a dynamically loaded module is not loaded until after the first event (with `SENTRY_SCOPE_MODULES`) is captured, it will never be seen in the module list, and therefore will also lose symbolication.

Loading the module cache is expensive so understand we don't want to do that on every event. Would it be possible to surface methods to invalidate the cache in the API, and/or always invalidate the cache for exceptions (where current module data is pretty essential and the time penalty is worthwhile)?

Version: 0.2.2+ (eb73904a8700fcf67e632a8c7d71174d214a344c)

**Comment by Swatinem** [comment]
> Would it be possible to surface methods to invalidate the cache in the API

I was contemplating something like this already, as a `shutdown/init` cycle is not something we really want to encourage, and which might also break in surprising ways.
