### ISSUE TITLE
sentry_options_set_database_path wipes existing directory contents

### ISSUE THREAD

**Issue by zakalawe** [getsentry/sentry-native#223]
(This might be a documentation bug, reporting it here but if you want to WONTFIX and document it, I understand)

I got bitten today by the fact that sentry_options_set_database_path wants to take control of the directory you pass. I was expecting it make its own sub-dir, but leave other contents untouched. So I passed ~/Library/Application Support/myApp/ as the database dir, this directory already contains some other user data, which then got erased by sentry-native.

The fix for me was just to append 'sentry-db' to the path, but it caused some confusion wondering why my settings file (in the same dir) kept being wiped each launch.

**Comment by Swatinem** [comment]
I will document this better. As yes, this dir should be all for sentry-native for it to do with it whatever it pleases.
But yes, there were some bugs, and depending on the OS, either too many, or too little files were deleted. I cleaned that up in #209 which should only ever remove sub-directories of the database folder that are suffixed with `.run`.

**Comment by zakalawe** [comment]
Thanks for the explanation, all sounds good to me.
