### ISSUE TITLE
HTTP 413 error uploading with Linux

### ISSUE THREAD

**Issue by afedor** [getsentry/sentry-native#224]
I get this error when sentry-native is trying to upload a crash from Linux. This is running on Ubuntu 18.04.4 with the sentry-native git pull from today (Apr 6):

```
[sentry] starting transport
[sentry] starting background worker thread
[sentry] sending envelope
[sentry] submitting task to background worker thread
[sentry] starting backend
qmlRegisterSingletonType requires absolute URLs.
[sentry] background worker thread started
[sentry] executing task on worker thread
*   Trying 35.188.42.15...
* TCP_NODELAY set
* Connected to sentry.io (35.188.42.15) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* NPN, negotiated HTTP1.1
[12:35:10.342] [W] HubVC START 1.2(5796) edc16581
[12:35:10.365] [W] QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Functional Software, Inc.; CN=sentry.io
*  start date: Mar 24 00:00:00 2017 GMT
*  expire date: Jun 21 12:00:00 2020 GMT
*  subjectAltName: host "sentry.io" matched cert's "sentry.io"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> POST /api/1490314/store/ HTTP/1.1
Host: sentry.io
User-Agent: sentry.native/0.2.2
Accept: */*
x-sentry-auth:Sentry sentry_key=XXXXX, sentry_version=7, sentry_client=sentry.native/0.2.2
content-type:application/x-sentry-envelope
content-length:304125

< HTTP/1.1 413 Request Entity Too Large
< Server: nginx
< Date: Mon, 06 Apr 2020 18:35:10 GMT
< Content-Type: text/plain
< Content-Length: 29
< Connection: close
< ETag: "5b27f803-1d"
< Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< 
413 Request Entity Too Large
* we are done reading and this is set to close, stop send
* Closing connection 0
```

**Comment by Swatinem** [comment]
Hm, the sentry server does impose some limits, but I thought these were lifted recently, or at least relaxed a little bit.
Headers say you have a payload of *304k*.

CC @jan-auer

**Comment by jan-auer** [comment]
Right, the limits are still in place. We’re working on lifting them, and will communicate once the change has gone live. Sorry about the inconvenience!

**Comment by afedor** [comment]
OK.  This is just a standard crash report for something like `int *a = nullptr; *a=0`  I haven't added anything extra, but if there's a way for me to make the payload smaller, let me know...

**Comment by Swatinem** [comment]
The envelope basically encapsulates everything in one request:
* scope, including modules and:
* breadcrumbs
* attachments
* the minidump itself

So if you have set up any attachments, or are adding breadcrumbs, that contributes to the payload size. But I really wouldn’t worry about it.

**Comment by jan-auer** [comment]
@swatinem what we could do independently of lifting the 200KB limit is compressing envelopes before sending them to sentry. Especially with attachments, this may make a large difference. Usually, the Sentry SDKs do not compress, but given that attachments are usually very compressable, I think this may be worth a shot (depending on how hard it is to get compression in).

Relay understands deflate, zlib, gz and brotli.

**Comment by Swatinem** [comment]
@afedor Can you check again with an up-to-date version? The SDK now sends everything to the `envelope` endpoint, which has well documented limits which should be plenty for your payloads, even without compression.

See https://develop.sentry.dev/sdk/envelopes/#size-limits

**Comment by afedor** [comment]
Yes, using the latest commit it works for me now, even after adding in breadcrumbs.  Thanks for the support!
