### ISSUE TITLE
Is macOS 10.9 supported?

### ISSUE THREAD

**Issue by Janjanus** [getsentry/sentry-native#228]
I can't seem to find anything related for support for macOS 10.9 with the crashpad backend. I can find this line in the Readme: 'macOS Catalina with most recent Compiler toolchain'. 

Does this mean 10.9 i not supported?

**Comment by Swatinem** [comment]
In general, I try to actively support the platforms we can test on CI.
As I can see, 10.9 has been EOLd since 2016, and the uptake of macOS updates is generally a lot better than for other platforms.

However, I would very much appreciate contributions that add support for more platforms.
