### ISSUE TITLE
Disable sending reports to dsn, but still generate minidump on client

### ISSUE THREAD

**Issue by m1keall1son** [getsentry/sentry-native#24]
Crashpad has the ability to disable sending a report to the remote endpoint while still creating the report on the client if the end user opts out of crash reporting.  Currently it appears there's no way to achieve this with sentrypad, it's either on or off.   It would be lovely if sentrypad could expose a function to enable/disable the report sending by calling the `crashpad::Settings::SetUploadsEnabled(bool);`  in the crashpad backend.  It appears that the crashpad_handler also respects this flag and will not process the event.  

I'm happy to add this to the interface but I want to check that there are not any side effects this could cause or if it breaks the design of sentrypad?

**Comment by tonyo** [comment]
@m1keall1son Thanks for the suggestion, we'll keep this in mind. We'll be adding a Breakpad backend first, and then we'll see how this all fits together.

**Comment by Swatinem** [comment]
With the complete `sentry-native` rewrite which we will release later today (and I think even before), we do call out to `SetUploadsEnabled` here:
https://github.com/getsentry/sentry-native/blob/1e3b02c9b0bad90bd1e4b62b33c409eb65216de3/src/backends/sentry_crashpad_backend.cpp#L34

This setting depends on the user consent, which you can explicitly set via the `sentry_options_set_require_user_consent` and `sentry_user_consent_give/revoke` API.
