### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by maxp1256** [getsentry/sentry-native#244]
Is it possible to enable debug logging to a log file in the file system?

**Comment by Swatinem** [comment]
Not right now. If we ever define a hook for the logging such us #148 that would be possible no problem.

**Comment by maxp1256** [comment]
Is there any timeline for this feature?

**Comment by Swatinem** [comment]
No, its low priority right now.

**Comment by Swatinem** [comment]
Now that #267 landed, this should be possible to implement once I publish a new release ;-)
