### ISSUE TITLE
Setting a callback with sentry_options_set_before_send does not fire under Windows

### ISSUE THREAD

**Issue by Rubonnek** [getsentry/sentry-native#250]
I'm currently using the before-send callback under Linux to do my own crash post-processing, but this `before_send` callback does not fire under Windows.

**Comment by Swatinem** [comment]
This is a known issue, as on windows we use crashpad which is *out-of-process*, and does its own sending, which is independent of our whole transport mechanism.

We would need to do more research into figuring out how to actually send everything through our own infrastructure on next startup. But its not really high priority ATM.

**Comment by daxpedda** [comment]
Considering that we now merged the `breakpad´ and `inproc` backend for windows, I was trying it out now, without avail.
So I tried on Linux, which also doesn't work.

OS: Windows 10, Version 1809
CMake: 3.17.2
Compiler: MSVC 2019, 16.6.2
Backend: crashpad, inproc
Commit: https://github.com/getsentry/sentry-native/tree/e966dd100374efded31f8538080a69d549631628

OS: Ubuntu 18.04.4 LTS
CMake: 3.17.3
Compiler: gcc 9.3.0
Backend: breakpad
Commit: https://github.com/getsentry/sentry-native/tree/e966dd100374efded31f8538080a69d549631628

**Comment by daxpedda** [comment]
I just tried it with e45af98fcfd4ffc44bcf198fdd080ca1d9f271a0 and it works even with crashpad now.

**Comment by Swatinem** [comment]
Either way, another thing we do need tests for ;-)
