### ISSUE TITLE
[crash] if database path exist space or cyrillic symbols

### ISSUE THREAD

**Issue by irov** [getsentry/sentry-native#251]
file sentry_path_windows.c
line 53

use method _wopen

return -1 and run settup to null
sentry_init return 0
and i call any sentry_set_extra i get crash

**Comment by Swatinem** [comment]
Thanks for reporting this! I admit I never tried that case locally, and neither on CI it seems.

**Comment by irov** [comment]
my proposal how to fix this
function sentry__path_from_str use MultiByteToWideChar
and change CP_ACP to CP_UTF8

Thanks!

**Comment by Swatinem** [comment]
> and change CP_ACP to CP_UTF8

Nice! I don‘t know where this came from. We have a few places in the codebase that convert to/from wstr, and we used `CP_UTF8` everywhere else.

**Comment by Swatinem** [comment]
@irov We had quite a lengthy discussion about this right now, and I would like to ask you to clarify and try some things:

* are you calling the `sentry_options_set_database_path` function manually? if so, with what parameter?
* can you run sentry with debug logs enabled? It should print something like `[sentry] using database path "C:\Users\swatinem\AppData\Local\Temp\pytest-of-swatinem\pytest-25\test_capture_stdout0\.sentry-native"`

We definitely do have one bug here:
https://github.com/getsentry/sentry-native/blob/dd1eeef3b0675e63406c6c3f55350d351c3f7f18/src/sentry_database.c#L161

The code incorrectly converts the widestring path back to utf8, even though we want file paths to be in OS-native encoding, whatever that may be, in the case of windows its `CP_ACP`.

**Comment by irov** [comment]
@Swatinem 
Yes, i calling manually. And i show my parametrs it's are utf-8 path, because many OS like iOS or Android use utf-8 path. 
No. You don't fix this issue https://github.com/getsentry/sentry-native/issues/148 ;) 

> The code incorrectly converts the widestring path back to utf8, even though we want file paths to be in OS-native encoding, whatever that may be, in the case of windows its CP_ACP.

May I ask you to provide me with a code that does not convert from wchar_t to utf8?

**Comment by mitsuhiko** [comment]
@irov we're going to clarify the docs. The input parameters to those functions are the platform native C API encoding. That means utf-8 on linux and macos, but ANSI on windows. This is so you can use the file system ANSI APIs on those platforms to do the right thing.

On Windows it's generally better to use the `w` suffixed functions which take wide strings.

**Comment by Swatinem** [comment]
> No. You don't fix this issue #148 ;)

haha, fair enough ;-) BTW, I kicked the idea around internally, but we haven’t decided that yet. We would like it to fit into the [Unified API](https://develop.sentry.dev/sdk/).

oh yes, and like @mitsuhiko said, we will try to improve the docs to make the assumptions a bit clearer.

**Comment by irov** [comment]
>@irov we're going to clarify the docs. The input parameters to those functions are the platform native C API encoding. That means utf-8 on linux and macos, but ANSI on windows. This is so you can use the file system ANSI APIs on those platforms to do the right thing.

Ok, you right, maybe me need use 'w' function. But, i think need add check this code
`options->run = sentry__run_new(options->database_path);`
and if 'options->run' == nullptr return -1

and maybe to refactoring interface to unify path interface (utf-8).

**Comment by Swatinem** [comment]
> But, i think need add check this code
> `options->run = sentry__run_new(options->database_path);`
> and if 'options->run' == nullptr return -1

can you maybe try with the code in #252 ? I fixed at least one issue there. I will work on more tests and fixes in case `sentry_init` for some reason fails to initialize.

**Comment by irov** [comment]
> can you maybe try with the code in #252 ? I fixed at least one issue there. I will work on more tests and fixes in case `sentry_init` for some reason fails to initialize.

Yes, I am checking this fix on the weekend
