### ISSUE TITLE
[crash][Windows] Moving from 0.2.2 to 0.2.6 crashes for some users

### ISSUE THREAD

**Issue by MaxLeb** [getsentry/sentry-native#254]
We have moved to the 0.2.6 release since we found out about the "random deleted files" on Windows and we are facing a random crash that appears only for some users.

Here is what we captured with "DependencyWalker":

> LoadLibraryA("advapi32.dll") called from "SENTRY.DLL" at address 0x00007FFF94F260B6.
> LoadLibraryA("advapi32.dll") returned 0x00007FFFD2B80000.
> GetProcAddress(0x00007FFFD2B80000 [ADVAPI32.DLL], "SystemFunction036") called from "SENTRY.DLL" at address 0x00007FFF94F260CB and returned 0x00007FFFCFC81010.
> Second chance exception 0xC0000005 (Access Violation) occurred in "SENTRY.DLL" at address 0x00007FFF94F236A4.

Maybe this is linked to #251 as the user having this issue does have special chars and spaces in it's username, therefore the database path contains spaces.

**Comment by Swatinem** [comment]
> Maybe this is linked to #251 as the user having this issue does have special chars and spaces in it's username, therefore the database path contains spaces.

Interesting! From the `GetProcAddress` of your report, I figured this has something to do with the module finder.

**Comment by MaxLeb** [comment]
The thing to know is that users were running the app with the 0.2.2 version that might have randomly deleted some files due to this bug #220

**Comment by MaxLeb** [comment]
We can confirm that it is due to whitespaces/special chars like in #251

**Comment by Swatinem** [comment]
Thanks for the feedback!

Are you calling `sentry_options_set_database_path` manually with a literal string? Would you expect that function to treat the string as utf8, or rather use the return values of for example `FindFirstFileA` which is ANSI?

**Comment by MaxLeb** [comment]
Yes we are using that manually and we pass it utf8 string which contains a ë that makes it crash.
Just like that I would assume `utf8`

**Comment by MaxLeb** [comment]
Ok so closing on this,
We added on purpose an `emoji` to the path.
It was crashing, so instead of using the "raw" `utf8` string we converted it to a `utf16` string and used `sentry_options_set_database_pathw`. It seems to be ok with that!

**Comment by Swatinem** [comment]
Thanks for the feedback!
We had another internal discussion, and we will try to document this better to avoid this footgun.

I think we can also do a better job of hardening all the API to at least not crash when anything inside `sentry_init` failed.

**Comment by MaxLeb** [comment]
Yes at least with a nice error message and a feedback on the `sentry_init` so we can still know that `init` did fail.
At least with a crash we know that something is wrong and it is not silent XD

**Comment by Swatinem** [comment]
This was fixed by #252 and #257
