### ISSUE TITLE
Crashpad CaptureContex broken 

### ISSUE THREAD

**Issue by m1keall1son** [getsentry/sentry-native#28]
I'm integrating the sentrypad SDK into a Win64 app.  While testing different crashing scenarios i'm seeing that in some contexts, when I throw an exception in a thread somewhere I get the message:
`"Don't use this! For cross builds only. See https://crbug.com/762167."` printed to the console.  

I see that this is in an impl of crashpad's `CaptureContext` in capture_contex_broken.cc which is included in the Sentrypad SDK premake files for windows builds in premake5.crashpad.lua:440

I looked in crashpad and see that there is an assembly impl of that function in the file crashpad/util/misc/capture_context_win.asm, and in crashpad's build system, this is included instead of  the _broken version in you are on windows and not on ARM64, (we are not building for arm).  crashpad\util\BUILD.gn:390

I tried including the .asm files instead of the _broken.cc files, which now i don't get the message but i just get a crash when CaptureContex is called which ends up with the sentry event containing not-so-useful information in the call stack.   

It looks like CaptureContex is only called in certain types of crashes, but i'm not sure what to make of this situation in general.  Since the [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=762167) is still open, perhaps this is current unresolved issue?  I'm not familiar with crashpad to be able to tell.  

Have you guys encountered this or have any suggestions?  Thanks!

**Comment by mitsuhiko** [comment]
Hi. I'm not sure right now but we're cleaning up everything right now to make this ready for a release so I hope I have an update on this in the next few days.

**Comment by jan-auer** [comment]
This was fixed with the release. Thanks for reporting!
