### ISSUE TITLE
`sentry_shutdown` can break things in a multi-threaded environment.

### ISSUE THREAD

**Issue by daxpedda** [getsentry/sentry-native#280]
I discovered this while trying to call `sentry_init`, `sentry_shutdown` and `sentry_capture_event` multiple times from multiple threads at the same time during unit tests, not a valid use-case scenario of this library.

But I can imagine a valid use case to be when `sentry_shutdown` is called while other threads are still busy using `sentry_capture_event`.

---

Basically what happens is that functions like `sentry_capture_event` do this:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_core.c#L257
They check if it's valid here:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_core.c#L258
And then use it multiple times here:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_core.c#L282-L285

The issue arises when on a different thread `sentry_shutdown` is called which invalidates `g_options` and makes access to it access freed memory.
So the missing part here to me seems a missing lock around `g_options_mutex`.

---

Another example is `sentry_start_session`:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_session.c#L206-L214
So `SENTRY_WITH_SCOPE_MUT` locks `g_lock`:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_scope.c#L85-L90
But `sentry_shutdown` locks a different mutex, `g_options_mutex`:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_core.c#L142-L145
Which doesn't block `sentry_start_session` from using already freed memory:
https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_session.c#L54 https://github.com/getsentry/sentry-native/blob/9651561d45e4d00e9fe708275c086a3cfeb496bd/src/sentry_session.c#L64-L65

---

There are more offenders similar to those.
Is there an intention to account for this scenario?

**Comment by Swatinem** [comment]
The locking of `g_options` is definitely not ideal. I was thinking about this a few month back even, that it would be a lot better if it was an atomic ptr with reference counting. We do (or did? have to check) access the options from at least the background transport thread.

On the other hand, doing anything after `sentry_shutdown` is basically UB, but hardening this up further is definitely a good idea.

**Comment by daxpedda** [comment]
> On the other hand, doing anything after `sentry_shutdown` is basically UB, ...

Maybe we should just check for exactly that, not allow `sentry_init` after `sentry_shutdown`.

We could just not put a nullpointer in `g_options` after `sentry_shutdown` and instead make a field called `is_shutdown` or something in `sentry_options_s`.
If we want to check the validity of `g_options`, we could, additionally to the nullpointer check to see if we initialized already, check for `is_shutdown`.

I don't have a lot of experience in C programming, just a suggestion off the top of my head 😄.
