### ISSUE TITLE
Build dll with static runtime

### ISSUE THREAD

**Issue by FredrikLundkvist** [getsentry/sentry-native#282]
Hello,

I want to build sentry.dll with static runtime (/MT).
I saw this mentioned in issue 170: https://github.com/getsentry/sentry-native/issues/170,
but couldn't figure out what the conclusion of that issue was.

I added to CMakeLists.txt, as suggested in that issue:
if(WIN32)
set(SENTRY_DEFAULT_TRANSPORT "winhttp")
# ??? FL: Added flags
# https://stackoverflow.com/questions/14172856/compile-with-mt-instead-of-md-using-cmake
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /MT")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /MTd")
 
Can we get that as build option? Or is it already possible? I'm not that good at CMake..

We are not a Windows Store app, btw, but we have a plugin version, so I don't want to have dependency issues when we're loaded in another app.

Thanks,
Fredrik

**Comment by Mixaill** [comment]
please check #283
