### ISSUE TITLE
HTTP error sending crash report on MacOS

### ISSUE THREAD

**Issue by OpenJeDi** [getsentry/sentry-native#286]
Hi,

I am trying to integrate Sentry Native on MacOS, using the latest release of the sentry-native SDK (0.3.1). The SDK is built using standard options: curl and crashpad.

When the application crashes, the minidump is not sent to Sentry the next run. I get this errror:
`[22156:5846537:20200610,174128.043244:ERROR http_transport_mac.mm:297] HTTP status 400`

Custom events do work and end up in the dashboard, for example:
`sentry_capture_event(sentry_value_new_message_event(
    /*   level */ SENTRY_LEVEL_INFO,
    /*  logger */ "custom",
    /* message */ "It works!"
));`

**Comment by OpenJeDi** [comment]
I built from master and it works now, thanks!

**Comment by david-antiteum** [comment]
@Swatinem Any release date? I need a new release as I'm using vcpkg and having a port that builds from master is not a good idea :)

**Comment by Swatinem** [comment]
Aiming for monday. I would like to get a few PRs in still, but I can also push a release out without those.

**Comment by david-antiteum** [comment]
I can wait :) Thanks.
