### ISSUE TITLE
Remove final new line from message in sentry_options_set_logger

### ISSUE THREAD

**Issue by david-antiteum** [getsentry/sentry-native#298]
Thanks for the feature but, can you send the message without a final new line? Other loggers already add a new line (in my case spdlog).

Thanks,

**Comment by Mixaill** [comment]
I think it is better to integrate sentry with spdlog

Something like:

```c
#include "spdlog/spdlog.h"

void sentry_logger_spdlog(sentry_level_t level, const char* message, va_list args)
{
    //process format
    char buf[1024]{};
    vsprintf(buf, message, args);

    //write to spdlog
    switch (level) {
    case SENTRY_LEVEL_DEBUG:
        spdlog::debug(buf);
        break;
    case SENTRY_LEVEL_INFO:
        spdlog::info(buf);
        break;
    case SENTRY_LEVEL_WARNING:
        spdlog::warn(buf);
        break;
    case SENTRY_LEVEL_ERROR:
        spdlog::error(buf);
        break;
    case SENTRY_LEVEL_FATAL:
        spdlog::critical(buf);
        break;
    default:
        break;
    }
}

void your_sentry_init_function() 
{
    //create sentry options struct
    sentry_options_t* _options = sentry_options_new();

    //set logger function
    sentry_options_set_logger(_options, sentry_logger_spdlog);

    ...
}
```

**Comment by Swatinem** [comment]
I think this is a valid request. We currently add the newline here:

https://github.com/getsentry/sentry-native/blob/d27146633642b582ce01da67cbe7835815c2d8e7/src/sentry_logger.h#L11

We can move that to our default logging implementations instead.

**Comment by Swatinem** [comment]
Also, I’m not quite sure what the android logger expects, I would have to take a look at that.

**Comment by david-antiteum** [comment]
> ```c
> #include "spdlog/spdlog.h"
> 
> void sentry_logger_spdlog(sentry_level_t level, const char* message, va_list args)
> {
>     //process format
>     char buf[1024]{};
>     vsprintf(buf, message, args);
...
> ```

even better:

```c
	const int len = std::vsnprintf(NULL, 0, message, args);
	std::vector<char> buffer( len + 1 );
	std::vsnprintf( buffer.data(), buffer.size(), message, args );
	std::string string = std::string( buffer.data(), buffer.size() ); 
```

No need to fix the size of the buffer.
