### ISSUE TITLE
missing logging in sentry_init

### ISSUE THREAD

**Issue by irov** [getsentry/sentry-native#300]
some log in sentry_init does not show because g_options is not configured

like this

    SENTRY_DEBUGF("using database path \"%" SENTRY_PATH_PRI "\"",
        options->database_path->path);

**Comment by Swatinem** [comment]
🤦‍♂️ I should have paid more attention. I think it would be best to use a different global for the logger, and set it independently of `g_options`. I can do that tomorrow.
