### ISSUE TITLE
`set_debug(true)` crashes

### ISSUE THREAD

**Issue by daxpedda** [getsentry/sentry-native#309]
Apparently simply doing this:
```cpp
sentry_options_t *options = sentry_options_new();
sentry_options_set_debug(options, 1);
```

Crashes the application. This doesn't happen in 0.3.2, so maybe it has something to do with #302?

**Comment by Swatinem** [comment]
Would be good to know the os / compiler. The `options` code itself does not really do anything.

**Comment by daxpedda** [comment]
Sorry about that, this issue report was very sloppy!
Windows 10, Version 1809
CMake 3.17.2
MSVC 2019, 16.6.2

I will go ahead on try it on Ubuntu now.

**Comment by daxpedda** [comment]
I'm having the same issue on Ubuntu:
Ubuntu 18.04.4 LTS
g++ 9.3.0
Same commit as above.

**Comment by Swatinem** [comment]
Well, this is embarrassing, lets just pretend noone saw that.
Fixed by #310

**Comment by jan-auer** [comment]
Thank you for reporting this issue. `0.3.4` is being released now with the bugfix.

**Comment by daxpedda** [comment]
Thank you for the quick response and fix!
