### ISSUE TITLE
Unable to build on Windows due to ASM_MASM check failure

### ISSUE THREAD

**Issue by jfro** [getsentry/sentry-native#340]
**Description**

Downloaded latest release source & attempted to build on windows with crashbad backend (which appears to be default as well?) Fails with an error in crashpad's cmake config between MSVC runtime & ASM_MASM capabilities.

Building crashpad directly seems OK so it's some interaction between sentry's cmake config invoking crashpad's

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10 Pro 64-bit version 2004
- Compiler: VS2019, MSVC 14.26.28801
- CMake config: SENTRY_BACKEND=crashpad

**Steps To Reproduce**

1. Download latest Sentry SDK source
2. Install cmake if you don't have it
3. Try `cmake -B build -D SENTRY_BACKEND=crashbad`

**Log output**
```
-- Detecting CXX compile features - done
-- SENTRY_TRANSPORT=winhttp
-- SENTRY_BACKEND=crashpad
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/ml64.exe
-- Configuring done
CMake Error in external/crashpad/compat/CMakeLists.txt:
  MSVC_RUNTIME_LIBRARY value 'MultiThreadedDebugDLL' not known for this
  ASM_MASM compiler.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by Swatinem** [comment]
Which cmake version are you using? After a quick search, this looks pretty much like https://gitlab.kitware.com/cmake/cmake/-/issues/20236, as we also explicitly set this policy here:

https://github.com/getsentry/sentry-native/blob/9d0a2ed193b250b88736fc16bdaeba875e71a536/CMakeLists.txt#L4-L5

Maybe we would have to increase the minimum cmake version to one that has this fix applied.

**Comment by jfro** [comment]
3.15.3 & 3.16.1 were the 2 versions we were trying. Just updated to 3.18 via `scoop` and that got through cmake OK. so yeah looks like a higher minimum cmake is definitely required at least for windows now?

**Comment by Swatinem** [comment]
If I see it correctly, `3.15.7` and `3.16.4` seem to have the necessary fix.
CC @Mixaill since you added that particular code/policy.

**Comment by jfro** [comment]
Should I open another issue for further build issues on windows? They're partly documentation issues in conflict with build behavior.
1. Sometimes building on windows seems to trigger an error about accessing a tlog while another process is accessing, unsure if critical, sometimes running again is fine
2. Documentation doesn't say do `--config Release` but default is Debug and yet default for install is Release so following steps yields error because of this difference

**Comment by Swatinem** [comment]
I would appreciate it, yes. Also very open to PRs that update the documentation ;-)

**Comment by Mixaill** [comment]
Because there is not a problem to keep CMake up to date on Windows at all, we can just bump requirement to 3.16.4
