### ISSUE TITLE
No crashes caught by crashpad backend on Linux

### ISSUE THREAD

**Issue by mikepurvis** [getsentry/sentry-native#352]
I'm following the documentation at https://docs.sentry.io/platforms/native/, and this is my test project (on Ubuntu 20.04, x86_64):

```
#include <sentry.h>
#include <cstdio>

void foo(int y)
{
  auto ev = sentry_capture_event(sentry_value_new_message_event(SENTRY_LEVEL_ERROR, "custom", "It works!"));

  for(int j = 0; j < sizeof(ev.bytes); j++)
  {
    printf("%02x", static_cast<uint8_t>(ev.bytes[j]));
  }
  printf("\n");

  int z = 5 / 0;
}

int main(void) {
  sentry_options_t *options = sentry_options_new();
  sentry_options_set_dsn(options, "http://298ebae4eebf40d1b09ea6175723ef3b@10.31.15.72:9000/2");
  sentry_init(options);

  int x = 23;
  foo(x);

  sentry_shutdown();
}
```

And this `CMakeLists.txt`:

```
project(sentry-test CXX)

find_package(sentry)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} sentry::sentry)
```

When I compile this, upload the binary to Sentry with `sentry-cli`, and run it against the Breakpad backend, I get the following expected output:

```
$ ./sentry-test
d220af769cf741d649f6177c22015d2b
Floating point exception (core dumped)
```

And on my Sentry instance, I see both the custom event and also the crash with a (partially) symbolicated stack trace. However, when I instead build `sentry-native` with the crashpad backend and run the same test, neither event comes through and I get nulls back:

```
$ ./sentry-test
00000000000000000000000000000000
Floating point exception (core dumped)
```

Is there something else I need to be doing to make the crashpad backend work?

**Comment by daxpedda** [comment]
Did you set up the Crashpad handler?

The Crashpad handler is a seperate executable that handles the crash out of process.
By default Sentry will search for it in the same folder as the executable you are running, you can also use `sentry_options_set_handler_path` to specify a path.
When you compile Sentry with CMake, it will dump the crashpad executable in the `bin` folder, it's called `crashpad_handler`/`crashpad_handler.exe`.

**Comment by mikepurvis** [comment]
Oh! Yes, I knew about that from using crashpad separately, but for whatever reason assumed the Sentry SDK would take care of it— I see now that it is documented in the page I linked to.

Thanks, working now.
