### ISSUE TITLE
Windows 10 - breakpad - folder location problem and solution

### ISSUE THREAD

**Issue by sseyod** [getsentry/sentry-native#355]
**Description**

I got my Windows 10 app built to use breakpad crash reporting.

It worked great, up until the time the app is bundled into a package for the Windows 10 Store - at which point, I don't see any reports on sentry.io

I found that the reason, is that sentry-native was building the crash folder immediately under the app folder (!), i.e. this specific (hidden) sub-folder.
 .sentry-native

That failed silently in the packaged Windows 10 app for the Windows 10 Store.

So, I changed the code to do something like this to use a non-magic folder, that persists across crashes.

```
  #define SENTRY_BUILD_STATIC 1

  #include <sentry.h>

  #include <ShlObj.h>
  #include <WinError.h>

  //...

  sentry_options_t* options = sentry_options_new();

  //...

  // Don't rely on the default folder - or the crashes will not be uploadable in a *packaged* application,
  // even though it works with non-packaged application!
  char tempFolder[2048];
  tempFolder[0] = 0;
  GetTempPathA((DWORD)sizeof(tempFolder), tempFolder);
  strcat(tempFolder, "\\myapp_crashes");
  auto result = SHCreateDirectoryExA(nullptr, tempFolder, nullptr);

  sentry_options_set_database_path(options, tempFolder);

  //...

  sentry_init(options);
```

That now works!

I'd suggest you document this very clearly somewhere!

**When does the problem happen**

**Environment**

- OS: Windows 10
- Compiler: MSVC 19
- CMake version and config: 3.16.5
cmake -B build -DBUILD_SHARED_LIBS=OFF -DSENTRY_BACKEND=breakpad -SENTRY_BUILD_RUNTIMESTATIC=ON

**Steps To Reproduce**

Just build and run the app, and make it crash. The crash uploading works, even without the above change.

Bundle the app for app store, and deploy it. The crash reports aren't uploaded, *unless* you do something like I suggested.

I hope this helps!

**Comment by Swatinem** [comment]
We do have this notice here:

https://github.com/getsentry/sentry-native/blob/2759bdc1a2e3cda66e8f5ef42354f18d5f2b62ae/include/sentry.h#L844-L845

I remembered incorrectly, and we don’t have anything similar in the example. We should definitely add that. Do you have any suggestions where it would be more discoverable, or where you would have looked for this information?

**Comment by sseyod** [comment]
Hi @Swatinem 

I'd suggest adding that info here: https://github.com/getsentry/sentry-native#building-and-installation, as that is where I looked for the build / integration instructions!

I would also suggest that, by default, you consider changing the existing implementation for Windows to use a path like I constructed above, as that will allow most Windows 10 builds for the Store to work "out of the box", so to speak. I'd make sure the folder name is based on the application name, in case your library is used by more than one application on the user's system :-)

I suspect that for other signed store apps (e.g. for macOS, and iOS), you'd also want to use a similar approach - creating a magic folder under the application's folder wouldn't work as an approach, in general.

Hoping that helps, Pete

**Comment by Swatinem** [comment]
I actually wanted to avoid doing all this in the native SDK itself, based on the platform. Most apps will probably manage their own runtime library conforming to whatever the platform standard for those are. I will make sure to extend the the readme and example with your suggestion.

**Comment by sseyod** [comment]
Fair enough!
