### ISSUE TITLE
New Build Setup

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-native#36]
We want to produce for now the following matrix:

* Platforms
  * Linux (gmake2)
  * Mac (gmake2)
  * Windows (vs2017)
* Backends
  * None
  * Breakpad (`WITH_SENTRY_BREAKPAD_BACKEND`)
  * Crashpad (`WITH_SENTRY_CRASHPAD_BACKEND`)
* Variations
  * Gold
  * Test (`WITH_SENTRY_TESTS`) + tests/**.cpp

And have a `make test` command toplevel that runs all tests locally for linux or mac and figure out something for windows later.

All the outputs are going to be dylibs only for now.

**Comment by jan-auer** [comment]
This is implemented now.
