### ISSUE TITLE
Build fail with static library sentry?

### ISSUE THREAD

**Issue by KhanhPQ-VTI** [getsentry/sentry-native#364]
**Description**
I export the static library sentry (from vcpkg) and my program linked to that *.lib file. But it seems my program doesn't recognize it and still have error LNK2019 for functions of sentry.

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10, 64-bit
- Compiler:MSVC 19
- CMake version and config: 

**Steps To Reproduce**

**Log output**

**Comment by Swatinem** [comment]
Can you try setting the `SENTRY_BUILD_STATIC` define like so:

```c
#define SENTRY_BUILD_STATIC 1
#include <sentry.h>
```

We should definitely improve the docs around this.

**Comment by KhanhPQ-VTI** [comment]
> Can you try setting the `SENTRY_BUILD_STATIC` define like so:
> 
> ```c
> #define SENTRY_BUILD_STATIC 1
> #include <sentry.h>
> ```
> 
> We should definitely improve the docs around this.

Thank you.
I use 
`#define SENTRY_BUILD_STATIC`
and include library: Dbghelp.lib

AND everything seem good.
