### ISSUE TITLE
[feature request] Add an official conan recipe

### ISSUE THREAD

**Issue by AndreyMlashkin** [getsentry/sentry-native#366]
conan is a popular C++ package manager. It would be very helpful if you add an official support for it. 

https://github.com/conan-io/conan-center-index/pull/2696

**Comment by Swatinem** [comment]
This came up already earlier this year, and the consensus back then was to add it to the index rather:
https://github.com/getsentry/sentry-native/issues/79

**Comment by AndreyMlashkin** [comment]
Yes, it's already added by the conan community. You can close this one.
But it would be nice to always have the latest conan recipe for latest sentry version in the future
