### ISSUE TITLE
Docs/usage issue: Attachments not working

### ISSUE THREAD

**Issue by zakalawe** [getsentry/sentry-native#368]
I'm trying to attach a log file to our Sentry reports, following this example in the Native SDK docs. I do:
```  
const std::wstring logPath = .. path to log file ...;
sentry_options_add_attachmentw(options, logPath.c_str());
```
during our startup phase.

But I don't ever see any attachments. Are there some additional restrictions on this API, for example does the file need to exist before calling this function? It's a log file so its open and being appended to frequently as the application runs. We also rotate the old log file out (by renaming it) and create a new log file each time the application starts, is it possible this is messing up some internal logic for attachments?

I will look at the SDK internals now, but wanted to ask as well, in case it's something quick & dumb I have done/not done.

**Comment by Swatinem** [comment]
The SDK will read the attachment lazily at time of crash / `capture_event` call.

You would also have to enable attachment support for your project: https://docs.sentry.io/platforms/native/enriching-error-data/attachments/

**Comment by zakalawe** [comment]
I suspect it's the latter : the setting for storing native data seems to be missing in my project/org settings, I'll keep looking and open a support request instead. From reading the SDK API docs, I had totally missed that there was any configuration changes needed for this to work.
