### ISSUE TITLE
User-feedback (backend specific?)

### ISSUE THREAD

**Issue by zakalawe** [getsentry/sentry-native#375]
**Description**

I was checking if I could enable user-feedback, from the Sentry site, but the docs link bring me to `https://docs.sentry.io/platforms/native/enriching-error-data/user-feedback/` .. which mentions the JavaScript SDK.

Is there any provision to do user-feedback in the native API (which I can guess, might be a backend-specific feature, since it would need a native GUI dialog), or am I missing something here? (I'm wondering if the idea is to launch the user's browser at a particular URL, and use that to collect the feedback...)

**Environment**

Sentry native-SDK 0.4.0

**Comment by Swatinem** [comment]
We don’t have anything along these lines yet for native, and also have no immediate plans for it either.

However it is something we have considered, but its a complex topic and very much backend dependent as well.

**Comment by zakalawe** [comment]
Right, that's exactly what I figured - it's a lot of work. I think all that's missing is a note in the docs saying basically what you wrote above: when I couldn't find such a note, I started wondering if the feature was actually available. And the docs link I posted above got me more confused :)

**Comment by untitaker** [comment]
BTW you can still submit userfeedback through the HTTP API: https://docs.sentry.io/api/projects/post-project-user-reports/. so if you write your own Dialog you can still use it.

I'm working on fixing docs to call this out more.

**Comment by zakalawe** [comment]
@untitaker Well at the point the app has segfaulted, I'm not sure showing a dialog in-process is going to go well. I know some apps defer sending the report, until the next launch, at which point we could easily (at least in our particular app) show some UI to collect this information, but my understanding is that Sentry (or the native backend) sends the report immediately, and hence it would have to be the backend in use, which presents any UI to the user?

**Comment by untitaker** [comment]
I see, ignore then. Was thinking more of non-fatal error events.

**Comment by zakalawe** [comment]
@untitaker No worries, it's good to know the API is there for non-fatal cases indeed.

**Comment by triplef** [comment]
We're also interested in this, as it's often very valuable to get specific feedback from users after a crash, including the ability to optionally collect contact information for further questions.

Could this issue be re-opened as a feature request?
