### ISSUE TITLE
Strange stacktrace for inline functions (Mac)

### ISSUE THREAD

**Issue by FredrikLundkvist** [getsentry/sentry-native#376]
**Description**

For some reports I have seen incorrect stacktraces. Seems to happen only for inlined functions,
and they are clearly wrong. It shows the same address, of the inlining function, for all those frames,
maybe some postprocessing done to the stacktrace?

Here's one example issue (hope this is not public?)
https://sentry.io/organizations/reason-studios/issues/1879135326

We use this to capture the stack trace:
sentry_event_value_add_stacktrace(event, nullptr, 0);

It's hard to know where things go wrong; in Sentry native or processing on the server or if our
symbols are wrong somehow, but I thought I'd report it in case you recognise the problem.

I have added our own stacktracing as attribute to our events to see if there's a difference.

**When does the problem happen**

- [ ] During build
- [? ] During run-time
- [? ] When capturing a hard crash

**Environment**

- OS: Only macOS so far (10.14, 10.15)
- Compiler: Xcode 11
- CMake version and config: [?, SENTRY_BACKEND=none]

**Steps To Reproduce**

**Log output**

**Comment by Swatinem** [comment]
The inlinees are expanded in the postprocessing step, yes. And they do have the same address, thats how inline functions work.

I’m not quite sure what you mean when you say they are clearly wrong? What should the stacktrace look like?

**Comment by FredrikLundkvist** [comment]
I see it's clearly wrong by looking at our code, there's no possibility for that call sequence.

Good to know there is post processing. I am trying to reproduce the problem and also record the stack trace using other means or locally, to see if the problem shows there too.

Sorry if this bug report is a bit open ended. I just wanted to report in case there's some known problem.

**Comment by FredrikLundkvist** [comment]
I looked at this some more and it seems the symbolicator lists some inlines in the involved functions, but those inlines are not in the call sequence. This has happened on some of our issues, but not all.
I thought at first, maybe it lists all inlines, but then there should be many more. Also tried to look at the disassembly of one of the functions and it's hard to see any pattern.

I saw in a blog that you have built your own symbolicator? Maybe the guys who did that have some insight into this problem?

Related: we only see our stack trace in the "Raw" tab. Are we doing something wrong? What would the "Full" stack trace be?

**Comment by Swatinem** [comment]
Yes we do symbolication via https://github.com/getsentry/symbolicator via https://github.com/getsentry/symbolic
We constantly try to improve the fidelity, especially around inline functions. @jan-auer is the one who knows it the best.

The reason you see the trace only via `raw` is because the trace is attached to the `threads` property, and not the `exception` I guess. I think thats the same as https://github.com/getsentry/sentry-native/issues/235 probably. The API certainly needs improvements.
