### ISSUE TITLE
Please add instructions to pull git submodules before trying to build

### ISSUE THREAD

**Issue by kiteflies** [getsentry/sentry-native#379]
**Description**

I've been hit by this situation about 3rd time now, always end up wasting 20-30 mins searching for cmake errors but then I realize I forget to call ```git submodule update --init --recursive``` after initial clone. I suppose this could be written in readme as a hint to next person who might make the same mistake as me.

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [Ubuntu]
- Compiler: [gcc]
- CMake version and config: [e.g. 3.18, SENTRY_BACKEND=crashpad/breakpad]

**Comment by jan-auer** [comment]
The expected way to build the SDK is via our [official releases](https://github.com/getsentry/sentry-native/releases) which already come with submodules resolved, mentioned in the [readme](https://github.com/getsentry/sentry-native#downloads). In contrast, the contribution guidelines mention how to [set up the environment](https://github.com/getsentry/sentry-native/blob/master/CONTRIBUTING.md#setting-up-environment). 

Is there a place we can add information that makes this easier to discover?

**Comment by kiteflies** [comment]
Oh I glanced over the release part until now. Since there wasn't a stable(v1) type release I was building on master always. Looks like I'll build with releases from now on. Thanks!
