### ISSUE TITLE
Building for Windows 32bits

### ISSUE THREAD

**Issue by imayo** [getsentry/sentry-native#382]
Hello, we are using sentry-native into our project and would like to understand how to compile for 32 bits static library windows as we managed to do so for 64bits but not for 32bits.

Thanks!

**Comment by Mixaill** [comment]
pass `-A Win32` argument to the cmake

**Comment by imayo** [comment]
Thanks! is there the same option from the UI? We are not using command line :)

**Comment by Mixaill** [comment]
![image](https://user-images.githubusercontent.com/704382/94538388-a42b4000-024c-11eb-890d-5b1fab242dd1.png)

**Comment by Mixaill** [comment]
@Swatinem can be closed, I think

**Comment by Swatinem** [comment]
👍
