### ISSUE TITLE
Is it possible to build sentry native to work on IOS?

### ISSUE THREAD

**Issue by hvorovk** [getsentry/sentry-native#391]
I can't find any mentions about building to IOS. So how can i use sentry-native in my IOS project(C++ + Qt).

**Comment by Swatinem** [comment]
In theory it should be possible to use the xcode generator for cmake, and it should work with the inproc backend.
I experimented with getting the crashpad backend to work as well, it is currently blocked by the compile-time code generation that we have to do on mac with cmake, and which is not being translated correctly when using the xcode generator for cmake.

**Comment by hvorovk** [comment]
Thank you, I did it!  In addition i used https://github.com/leetal/ios-cmake as toolchane and xcode as generator. Resulting cmake string for me: ```cmake -DSENTRY_BACKEND=none -DSENTRY_TRANSPORT=none -D BUILD_SHARED_LIBS=OFF -GXcode -B {BUILD-DIR} -DPLATFORM=OS -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake```

**Comment by Swatinem** [comment]
Ah thats good to hear. Have you tried using the `inproc` backend? I know that at least the `crashpad` backend suffers from the code-generation problem I described above.

**Comment by hvorovk** [comment]
Nope, i haven't tried it. In my current project I don't need backend at all.
