### ISSUE TITLE
How to build with qmake (Qt Creator)

### ISSUE THREAD

**Issue by mosntahunta** [getsentry/sentry-native#394]
**Description**

Hi, I'm a bit confused whether we should run the CMake commands first, then include the libs in my Qt .pro file. Or should I be building the sentry library as part of the qmake build process?

**When does the problem happen**

During build

**Environment**

- OS: Mac and Windows 64 bit
- Compiler: MSVC 19
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Comment by mosntahunta** [comment]
I would also like to specify the SENTRY_BACKEND=crashpad option in .pro file if possible

**Comment by david-antiteum** [comment]
Build sentry-native using CMake and then use it as any other third party library in your PRO file. When packing your app be sure than you copy the crashpad_handler application with yours.
