### ISSUE TITLE
Custom Transport example?

### ISSUE THREAD

**Issue by kiteflies** [getsentry/sentry-native#399]
I need to use my own custom transport(which is basically libcurl) on all platforms(linux,win,osx). I was searching for the documentation and came across https://docs.sentry.io/platforms/native/transports/. Though it gives an declaration for `custom_transport()` method and how to set it but I wanted to see an example implementation for it instead of currently empty body.

Is there anywhere else I can find this?

**Comment by Swatinem** [comment]
In general, what you need is to construct your own HTTP requests. You will need the correct authentication header for that: https://develop.sentry.dev/sdk/overview/#authentication
And then send the envelopes to the envelope endpoint: https://develop.sentry.dev/sdk/envelopes/
So far the only thing you can do with envelopes is basically serialize them to a buffer:

https://github.com/getsentry/sentry-native/blob/beae72a16c43726a39ddc4fee15166e7bec351e2/include/sentry.h#L477-L483

We do have a builtin curl transport here: https://github.com/getsentry/sentry-native/blob/master/src/transports/sentry_transport_curl.c

You can certainly take inspiration from that one, however most of the internal http-related APIs are not exposed publicly.
So while building your own transport is possible, it is not really convenient right now.
