### ISSUE TITLE
Hook to call when background task worker start

### ISSUE THREAD

**Issue by xamix** [getsentry/sentry-native#411]
Hello,

I'm using Sentry Native 0.4.3 on Linux.

I'm naming all my thread in my application and the only thread I cannot name is the sentry background task worker.

Is it possible to add a hook, (something like the one called by sentry inside of `sentry_init`) but here called by the background thread worker in order to get possibility to name the thread inside this hook?

Or a function to return the thread handle?

Regards.

**Comment by Swatinem** [comment]
The thread is an implementation detail of our default transports, and I wouldn’t want to expose any of it. We can try to assign a name to it ourselves though.

**Comment by xamix** [comment]
Hello,

This is good for my usage, however it will force you to implement it on each platform (Linux Windows Mac...)
On Linux maximum thread name size seem to be 15 bytes

For information, on Linux I use the following code:

```
#include <pthread.h>

inline void set_thread_name(pthread_t t, const char* name)
{
    int i = pthread_setname_np(t, name);
    if(i != 0) {
        if(i == ERANGE) {
            ERR("Cannot set thread name to " << name << " maximum 15 bytes!");
        }
        else {
            ERR("Cannot set thread name to " << name << " (" << i << ")");
        }
    }
}
```

And to get the current thread to pass it to the function as parameter, I use the following function:
`pthread_self()`

**Comment by Mixaill** [comment]
>This is good for my usage, however it will force you to implement it on each platform (Linux Windows Mac...)

Not a bad idea I think.

**Comment by xamix** [comment]
Ability to set specific [thread name](https://github.com/getsentry/sentry-native/pull/413#issuecomment-720633721) will be used by me since all my threads name have a specific format ;-)

**Comment by Mixaill** [comment]
Implemented :D

**Comment by xamix** [comment]
Thank you for the incredible reacticvity!
