### ISSUE TITLE
Sentry-native build failed with error C2220

### ISSUE THREAD

**Issue by LilyWangL** [getsentry/sentry-native#415]
**Description**

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [e.g. Windows 10, 64-bit]
- Compiler: [e.g. MSVC 2019 version 16.8]
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Steps To Reproduce**
I am a member of Microsoft VCPKG team. In an internal version of Visual Studio, `sentry-native` build failed with error C2220. For fixing this issue, we need to disable warning C5105 in _external/crashpad/third_party/zlib/zlib/x86.c_. I have added a patch to solve this problem temporarily on VCPKG, the related PR https://github.com/microsoft/vcpkg/pull/14349. I submit this issue and want to fix this error on upstream.

**Log output**
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9461): error C2220: the following warning is treated as an error
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9461): warning C5105: macro expansion producing 'defined' has undefined behavior
```

**Comment by Swatinem** [comment]
Thanks for reporting this. The *real* upstream is here: https://chromium.googlesource.com/crashpad/crashpad/+/refs/heads/master/third_party/zlib/BUILD.gn#94

**Comment by BillyONeal** [comment]
@Swatinem To be clear: the desired fix would not be to silence the warning, it would be to avoid the undefined behavior in the first place.

**Comment by Swatinem** [comment]
> the desired fix would not be to silence the warning, it would be to avoid the undefined behavior in the first place.

Agreed. While we maintain our own fork of crashpad, that in turn consumes a few dependencies via submodules which we don’t touch, and their copy of zlib is one of those.

**Comment by Swatinem** [comment]
We silence some of these errors directly. Also I found out the hard way that older versions of certain Windows SDK headers have such errors as well, which is completely outside of our control.
