### ISSUE TITLE
Submitted events are now silently lost after upgrade to 0.4.4

### ISSUE THREAD

**Issue by roman380** [getsentry/sentry-native#435]
**Description**

After upgrading 0.3.4 -> 0.4.4 I see no longer submitted results in web interface.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10, x64 buld
- Compiler: Visual Studio 2019 Preview; Version 16.9.0 Preview 2.0
- CMake version and config: 3.19.1

cmake -S . -B .\x64 -D SENTRY_BUILD_SHARED_LIBS=OFF -D SENTRY_BUILD_TESTS=OFF -D SENTRY_BUILD_EXAMPLES=OFF -D SENTRY_BUILD_RUNTIMESTATIC=ON

I have to add /Wv:18 to compile the static libraries.

**Steps To Reproduce**

pretty much regular 

```
sentry_options_t *options = sentry_options_new();
sentry_options_set_dsn(options, "...");
sentry_init(options);
...
sentry_value_t event = sentry_value_new_message_event(SENTRY_LEVEL_INFO, nullptr, ToMultiByte(m_Text).c_str());
sentry_capture_event(event);
...
sentry_shutdown();
```

Going back to 0.3.4 with the same code get me the events back.

**Log output**

No error happens, submissions are just lost somewhere.

**Comment by Swatinem** [comment]
Can you please run this with `sentry_options_set_debug(options, 1);` and paste the relevant output here? Please make sure to remove your DSN key from the output.

**Comment by roman380** [comment]
```
		sentry_options_t *options = sentry_options_new();
		sentry_options_set_dsn(options, "https://...ingest.sentry.io/...");
		sentry_options_set_debug(options, 1);
		sentry_init(options);
...
```
 output

```
[sentry] INFO using database path "C:\Project\...\bin\x64\Release\.sentry-native"
[sentry] DEBUG starting transport
[sentry] DEBUG starting background worker thread
[sentry] DEBUG starting backend
[sentry] DEBUG background worker thread started
[sentry] WARN unable to start crashpad backend, invalid handler_path
[sentry] WARN failed to initialize backend
[sentry] WARN `sentry_init` failed
[sentry] DEBUG shutting down transport
[sentry] DEBUG shutting down background worker thread
[sentry] DEBUG submitting task to background worker thread
[sentry] DEBUG executing task on worker thread
[sentry] DEBUG background worker thread shut down
```

**Comment by jan-auer** [comment]
Thanks!

> unable to start crashpad backend, invalid handler_path

Is the crashpad handler located next to your executable, as per [instructions](https://docs.sentry.io/platforms/native/configuration/backends/crashpad/)?

**Comment by roman380** [comment]
No, I was linking everything statically, into single binary.

**Comment by roman380** [comment]
Things are fine if I put crashpad_handler.exe side by side, can you calrify if this is something that was changed intentionally since 0.3.4? Because it was not mandatory in that version. Also my primary target is DLL where I link Sentry Native to and that DLL is used in C# project which has its own Sentry integration so I don't think I want to use external handler app for the DLL.

**Comment by jan-auer** [comment]
I will have to check the old build first, but to my recollection this was not intentionally changed. Quite the opposite, in 0.3.4 the default backend on Windows was Crashpad already and should require the crashpad_handler executable to work.

Can you paste debug logs from a build with the old SDK? My best guess is that we didn't fail initialization when the crashpad handler wasn't there, which means you could send custom errors but would receive no crashes.

**Comment by roman380** [comment]
I switched to inproc and it looks good for non-crashpad event submission. 

I verified today earlier that switch back to 0.3.4 had event submission working without need for `crashpad_handler` executable side by side. That is, `sentry_init` was probably not failing. Explicit event submission was working and crashpad related activity was probably not working but failing at some later step when crash was actually taking place (if ever at all).

**Comment by jan-auer** [comment]
That confirms my suspicion then, thank you. We did indeed make initialization stricter. In your case, crashpad would not initialize and application crashes would not be captured at all.

You should be good using the inproc backend on Windows, as it will also intercept application crashes and send them to Sentry on restart.

**Comment by roman380** [comment]
Thanks, I believe the issue can be closed then but I will leave to you to press the button.
