### ISSUE TITLE
How to control the number of breadcrumbs attached to the captured event?

### ISSUE THREAD

**Issue by weidonglian** [getsentry/sentry-native#438]
**How to control the number of breadcrumbs attached to the captured event?**

I only found the SENTRY_BREADCRUMBS_MAX macro and it feels bad to change it directly. There ought to be an API or an option? 

Thanks

**Comment by Swatinem** [comment]
This is not yet supported, but it should be easy enough to expose a setting on `sentry_options_t` and use that.

**Comment by weidonglian** [comment]
Absolute! I can then hack the macro definition for a workaround.
