### ISSUE TITLE
DSN client issue

### ISSUE THREAD

**Issue by lazam** [getsentry/sentry-native#444]
**Description**

I was unable to send events via captureException when using the legacy DSN client (https://xxxxxx:xxxxxxxx@sentry.svc.xxxxx.io/1), but using the current client DSN (https://xxxxxx@xxxxxx.ingest.sentry.io/54) works fine. 

I tried to use 0.4.4 version, but unable to send event. I can confirm that both DSN are working since I was able to send events using sentry-cli. 

```
< HTTP/1.1 302 FOUND
* HTTP error before end of send, stop sending
```

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Ubuntu 18.04
- CMake version and config: 3.10.2, SENTRY_BACKEND=breakpad

**Steps To Reproduce**

Use a legacy DSN client

**Comment by deathlyrage** [comment]
I'm not sure if legacy DSNs are supposed to work as they are moving away from supporting them, its why the new one exists afaik.

**Comment by Swatinem** [comment]
We do test with a kind-of legacy DSN:
https://github.com/getsentry/sentry-native/blob/db6eebde2edd2fc450d3756c66fa37869d86d540/tests/unit/test_utils.c#L104
But since you say it works fine with the new DSN, why not use that one…

**Comment by lazam** [comment]
I wasn't able to find anything unusual with the sentry logs regarding the request. The sentry version was really old which is **8.21**. 
I'll stick with the cloud hosted one since it has new DSN, then just upgrade the self hosted Sentry in the future.

Thanks guys for the help!

**Comment by jan-auer** [comment]
For future reference, this SDK requires a minimum Sentry server version. See the first paragraph in the README:

> Supports Sentry _20.6.0_ and later.
