### ISSUE TITLE
DLL name collides with Sentry dotnet

### ISSUE THREAD

**Issue by tgreenman** [getsentry/sentry-native#458]
**Description**

Sentry-native 0.4.4 produces a dll named `sentry.dll`. https://github.com/getsentry/sentry-dotnet also produces a dll named `sentry.dll` when consumed through nuget. This causes problems when loading the DLL at runtime. If possible, it would be great to either rename the dll (it was `sentry-crashpad.dll` / `sentry-<backend>.dll` previously) or provide a cmake config to change it more easily in order to support applications which have code in c# and c++ (lots of interop to native libraries).

**When does the problem happen**

- [ ] During build
- [X] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [Windows 10, 64-bit]
- Compiler: [MSVC 19]
- CMake version and config: [3.18, SENTRY_BACKEND=Crashpad]

**Steps To Reproduce**

1. Have a project that consumes both Sentry-dotnet and Sentry-native.
2. Attempt to start application
3. Runtime error will appear, most likely a BadImageFormatException

**Log output**

```
An unhandled exception of type 'System.BadImageFormatException' occurred in Application.exe
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```

**Comment by Swatinem** [comment]
I think @bruno-garcia has some input here, as he was working on using native alongside dotnet.

**Comment by bruno-garcia** [comment]
I've got a [NuGet package for capturing Minidumps of .NET apps with sentry-native](https://github.com/getsentry/sentry-dotnet-minidump) but I didn't explore it with both that and Sentry .NET so it's a good point, it'll conflict event if you add [`Sentry.Minidump`](https://www.nuget.org/packages/Sentry.Minidump/) and [`Sentry`](https://www.nuget.org/packages/Sentry).

Can we compile `sentry-native` with an alternative name?

**Comment by bruno-garcia** [comment]
Also, I'm curious about your use case @tgreenman of using `sentry-native` and `sentry-dotnet`. Would you share it with us?

**Comment by tgreenman** [comment]
My use case is essentially just that wanted to be able to capture and track handled / unhandled exceptions in c# as well as c++ code since my c# code interops with quite a few native libs. Sentry-dotnet on its own (to my knowledge) isn't be able to capture fatal exceptions from c++ libraries like sentry-native is with crashpad. Currently, I use both by having a shim c++ project which passes over initial configuration values and things like additional tags / breadcrumbs to initialize sentry-native. I'm using the nlog implementation within sentry-dotnet.

**Comment by bruno-garcia** [comment]
Is this a .NET Core app or .NET Framework? Desktop or something else?
I wonder if you could leverage the work done for "Minidumps" which is basically `sentry-native` with `crashpad` and expand the P/Invoke API. To avoid distracting this issue I've created an another one on that other repo if you'd like to discuss it: https://github.com/getsentry/sentry-dotnet-minidump/issues/2
[We're also on Discord](https://discord.gg/PXa5Apfe7K) if you'd like to collaborate on this.

**Comment by jan-auer** [comment]
> Can we compile sentry-native with an alternative name?

You are always free to change the name after compilation finished or move it to a different location. I'd rather not change the default name.

**Comment by tgreenman** [comment]
> > Can we compile sentry-native with an alternative name?
> 
> 
> 
> You are always free to change the name after compilation finished or move it to a different location. I'd rather not change the default name.

The underlying problem is that the c++ library which utilizes sentry-native links against a dll named 'sentry.dll' and depending on build order the sentry-dotnet sentry.dll gets copied over to my output directory first. I'm familiar with changing the what certain dylibs link against after they've been built on Mac but not so much on windows. I looked up a few tutorials on it and it seemed a bit manual and convoluted in comparison.

**Comment by tgreenman** [comment]
> Is this a .NET Core app or .NET Framework? Desktop or something else?
> 
> I wonder if you could leverage the work done for "Minidumps" which is basically `sentry-native` with `crashpad` and expand the P/Invoke API. To avoid distracting this issue I've created an another one on that other repo if you'd like to discuss it: https://github.com/getsentry/sentry-dotnet-minidump/issues/2
> 
> [We're also on Discord](https://discord.gg/PXa5Apfe7K) if you'd like to collaborate on this.


.net framework 4.7.2. I'll definitely take a look at using that lib, hadn't heard of it before this.

**Comment by bruno-garcia** [comment]
@tgreenman another approach might be moving the .NET dll to a subfolder and using `AppDomain.CurrentDomain.AssemblyResolve` to intercept the calls and find the managed Sentry.dll in the subfolder. Or another .NET specific approach to load the Sentry .NET SDK.

> .net framework 4.7.2. I'll definitely take a look at using that lib, hadn't heard of it before this.

Awesome.

**Comment by bruno-garcia** [comment]
@tgreenman For the record which solution did you end up going with?
