### ISSUE TITLE
Crash report is not sending to sentry server

### ISSUE THREAD

**Issue by austinlin7732** [getsentry/sentry-native#46]
1. With default sentry_crashpad example binary
In x86 ubuntu, I build and run the example_crashpad with **http DSN**, I can see it send the report to my sentry server.

2. I [unmark the crash source code](https://github.com/getsentry/sentry-native/blob/0.0.4/examples/sentry_crashpad.c#L56) ,build it  and run it with my **http DSN**, my sentry server doesn't get the report

I saw it POST something by using wireshark but it is showing bad request 401
![image](https://user-images.githubusercontent.com/50258355/65101528-15f66a00-d9fb-11e9-8bdf-04f4e642b1c0.png)

Do I miss anything ?
Does sentry-native support sending the crash report to sentry server now ?
or user should use curl to POST minidump report in sentry-db ?

**Comment by jan-auer** [comment]
The URL in the initial screenshot was truncated, but it seems like you were using the _Legacy DSN_ including the private key. This is not supported by this SDK and generates a wrong `sentry_key` query parameter in the URL. This generated the initial 401 request.

Are you sending this to sentry.io or an on-premise version of Sentry? It seems that you're using an on-premise version. If so, which version are you running on? You will require a relatively recent version -- ideally the latest `master` -- for this to work. Also, you can check the server log for the exact error in this case. Depending on the error, there might be an `X-Sentry-Error` header (or similar) that explains why the request was bad.

That being said, we only ran limited tests with Crashpad on Linux yet, I will try this out myself and see if we can reproduce this error.

**Comment by austinlin7732** [comment]
Hi jan-auer, 
Thanks for your suggestion.  
I also set up sentry.io, I think I can try sentry.io first.  But it seems only provide _HTTPS_ DSN 
![image](https://user-images.githubusercontent.com/50258355/65122435-8add9a00-da23-11e9-8ffa-a7de932061f7.png)

with default [sentry_crashpad.c](https://github.com/getsentry/sentry-native/blob/0.0.4/examples/sentry_crashpad.c) and https dsn, I can see report in server, but if I [unmark the crash source code](https://github.com/getsentry/sentry-native/blob/0.0.4/examples/sentry_crashpad.c#L56), it said it only accept http.  

1.  Does sentrypad-native only support http for crash report ?
  I can't find the _HTTP_ DSN, can you tell me where is that ?

**Comment by jan-auer** [comment]
> I can see report in server, but if I unmark the crash source code, it said it only accept http.

Can you share the exact message that you're getting here? Sentry definitely accepts and prefers HTTPS usually. Also, uncommenting the crash line should not change anything with this. 

> I can't find the HTTP DSN, can you tell me where is that ?

It is strongly discouraged to use http in this scenario. If absolutely required, you can always just replace `https://` with `http://` in the DSN. In your case, there is probably a different issue and you can continue to use the HTTP DSN.

We're updating the UI now to remove the legacy DSN. If you use the **Public DSN** then sending crash reports should work out of the box.

**Comment by austinlin7732** [comment]
Hi jan-auer,  
Thanks for your information.  Let me have more clear description, thanks.  
With Sentry 4  

**1.**  Try default condition
with default [sentry_crashpad.c](https://github.com/getsentry/sentry-native/blob/0.0.4/examples/sentry_crashpad.c), after running sentry_example_crashpad binary with my _HTTP DSN_  It can send message to my sentry server as below,  
![image](https://user-images.githubusercontent.com/50258355/65224122-23901a80-daf5-11e9-9f8d-0a5be873407e.png), this test is no problem.  

**2.** Try crash condition 
    2.1 [unmark the crash source code](https://github.com/getsentry/sentry-native/blob/0.0.4/examples/sentry_crashpad.c#L56), and run sentry_example_crashpad to see core dump, it will said it need _HTTP_
![image](https://user-images.githubusercontent.com/50258355/65224464-cf396a80-daf5-11e9-960b-eb4c832221fd.png)    

   2.2  I [Modify to accept HTTPS](https://github.com/getsentry/crashpad/blob/master/util/net/http_transport_socket.cc#L548)  ,
build and run sentry_example_crashpad again,    

![image](https://user-images.githubusercontent.com/50258355/65224788-74544300-daf6-11e9-9d3f-8dd7dbfe391a.png)
Crash is there, Sentry doesn't get the report,  refer to wireshark, it is sent by http, that's why I think the minidump(crash ) report is not supported to send by _HTTPS_

![image](https://user-images.githubusercontent.com/50258355/65225026-ecbb0400-daf6-11e9-8b3a-61f712ff58a4.png)  

![image](https://user-images.githubusercontent.com/50258355/65225332-8bdffb80-daf7-11e9-9015-fbcceab880cf.png)

   2.3 If  I run sentry_example_crashpad with _HTTP_, with HTTP checking rule,  

I see some error in red square, 
**Does these error normal or it is issue ?**  
![image](https://user-images.githubusercontent.com/50258355/65226495-884d7400-daf9-11e9-9216-980487313804.png)

With wireshark, I see it POST to sentry server, but server doesn't get the report, and no response as wireshark shown.  
![image](https://user-images.githubusercontent.com/50258355/65225607-014bcc00-daf8-11e9-9651-f27626b5d885.png)


**Question 1**,  
Will it support to send crash report by HTTPS in the future ?

**Question 2,**   
Currently sentrypad have issue with sending core dump report with HTTP to sentry right?
or I miss something?

**Question 3,** 
Without crash happened in sentry_example_crashpad, report can send to sentry server by _HTTPS_, so the report type will be sent with different method in source code right ?

**Comment by jan-auer** [comment]
> With Sentry 4

Does this mean you're on Sentry version 4? You need to be on the latest `master`, that is, version 10.

> Will it support to send crash report by HTTPS in the future

You are using the Crashpad backend for Sentry native. At the moment we haven't completed tests on Linux. It seems like there might be an issue sending via HTTPS on Linux, which we will have to investigate. Unfortunately, Crashpad is not fully stable on Linux, so you might wanna try out the Breakpad version, instead. This is all work in progress, and we will update documentation as we gain more insights.

> Currently sentrypad have issue with sending core dump report with HTTP to sentry right?

Sentry Native will never send core dumps. It uses either Crashpad or Breakpad to send Minidumps. Submission should always be possible via HTTPS, but as stated above, on Linux Crashpad might not work properly. 

> Without crash happened in sentry_example_crashpad, report can send to sentry server by HTTPS, so the report type will be sent with different method in source code right?

That is correct. On Linux, we bundle `curl` to send events manually. It is on our roadmap to do this for crashes (i.e. minidumps) aswell, but we still need some more time for this.

**Comment by austinlin7732** [comment]
> insights

**Comment by austinlin7732** [comment]
Does this mean you're on Sentry version 4? You need to be on the latest `master`, that is, version 10.
>  Sorry I should say sentry-native Tag 0.04
 
You are using the Crashpad backend for Sentry native. At the moment we haven't completed tests on Linux. It seems like there might be an issue sending via HTTPS on Linux, which we will have to investigate. Unfortunately, Crashpad is not fully stable on Linux, so you might wanna try out the Breakpad version, instead. This is all work in progress, and we will update documentation as we gain more insights.
>   Thanks for you information, I will try Breapad version for sentry native. 

Sentry Native will never send core dumps. It uses either Crashpad or Breakpad to send Minidumps. Submission should always be possible via HTTPS, but as stated above, on Linux Crashpad might not work properly.
>  Understand 

That is correct. On Linux, we bundle `curl` to send events manually. It is on our roadmap to do this for crashes (i.e. minidumps) aswell, but we still need some more time for this. 
>  Thanks for this information

Doubt : 
I have one idea that I only need sentry-native and its minidumps module to catch the crash (core dump) for producing the minidumps report. (may be using curl manually or other method to send report to sentry server)  

If I remove other functionality modules and only keep minidumps modules in sentry-native for my thought above, do you think  it need much effort ? 
I means maybe the source file are depends tightly or the build depends is also tightly.

**Comment by jan-auer** [comment]
> I only need sentry-native and its minidumps module to catch the crash

sentry-native does not include such a module. At present time, this can only be achieved via either Crashpad or Breakpad. 

> I test with example_breakpad with unmark crash source line

After writing you, I'm realizing that we deactivated some code in the SDK for Breakpad. We will be checking in the proper breakpad implementation soon, then I'll update you here. Sorry about the confusion.

> If I only need minidumps functionality , do you recommend me to use crashpad or breakpad ?

On Linux I would recommend Breakpad. On macOS and Windows, I would recommend Crashpad.

**Comment by austinlin7732** [comment]
sentry-native does not include such a module. At present time, this can only be achieved via either Crashpad or Breakpad.
>  Thanks for your reminder, sentry-native is a wrapper of Crashpad/Breakpad

After writing you, I'm realizing that we deactivated some code in the SDK for Breakpad. We will be checking in the proper breakpad implementation soon, then I'll update you here. Sorry about the confusion.

>  Thanks, so after fix it, example_breakpad will create dmp file, 
> Q1: will it support upload to sentry ? Or user should use curl manually ?

On Linux I would recommend Breakpad. On macOS and Windows, I would recommend Crashpad.
> Thanks for your recommendation.
> Q2:
Breakpad uses in-process crash reporting, if I only need minidump function, will it has other disadvantage with out-of-process used by Crashpad ?

**Comment by jan-auer** [comment]
Q1: Yes, it will support uploads to Sentry. This will likely be included in one of the next releases of the SDK.

Q2: In-process error reporting is slightly less reliable. Once a process crashes, possibilities are significantly limited. Thus Crashpad would be theoretically superior, but it still has to catch up to Breakpad in some areas (e.g. uploading crashes).

I added your issues now to _"Known Issues"_ in the main readme. We'll work actively to get Breakpad working as soon as possible. Thanks for sharing all this context and information!

**Comment by Swatinem** [comment]
@austinlin7732 
We are planning to release a new version of sentry-native later today. It does not have official support for crashpad on linux, but plans are to add breakpad support asap, and looking into supporting crashpad on linux as well in the future.
