### ISSUE TITLE
Extend Sentry Options to better integrate with Android

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-native#473]
When initializing `sentry-react-native` or `sentry-flutter` the user provides some options such as:

* maxBreadcrumb
* inAppInclude
* ...

These SDKs in turn call `sentry-android`'s init, propagating the values from the options. Not everything is supported, but many options are.

Between `sentry-android` and `sentry-native` not many options are supported.

We'd like to extend the support between these two SDKs.

Relates to #472

The options we have in [Java](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryOptions.java) and [Android](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/SentryAndroidOptions.java)

**Comment by Swatinem** [comment]
Closing this, as we are not doing `in-app` now
