### ISSUE TITLE
Add `close` function to disable completely the SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-native#474]
In hybrid SDKs such as React Native, we want to be able to close the SDK in JS and have that `close` call flow through to all inner SDKs.

For that we need make sure `close` is implemented in all layers and works as intended.
The [spec defined a close method on the client](https://develop.sentry.dev/sdk/unified-api/#client) but we're looking for a close on the static API, which will be added to the spec.

The expected behavior is that if a crash happens after close is called, an envelope with the crash data isn't generated.

**Comment by Swatinem** [comment]
Native does have a `sentry_shutdown`, which does what it says.
The only exception is crashpad, which we can’t stop once its started, and we have customers who explicitly want to capture crashes in their apps "shutdown" phase, *after* they already cleaned up sentry via `sentry_shutdown`.

**Comment by bruno-garcia** [comment]
Since we don't use crashpad on Android, it should be good then. Thanks.

**Comment by marandaneto** [comment]
nice, one less thing, wondering if we should rename it to `close` though :)
https://develop.sentry.dev/sdk/unified-api/#client

**Comment by bruno-garcia** [comment]
Or just add `sentry_close` that calls `sentry_shutdown`, to deprecate the latter in a future version
