### ISSUE TITLE
Issues with building static

### ISSUE THREAD

**Issue by hjaltisan** [getsentry/sentry-native#477]
**Description**

When I build sentry-native statically everything seems to work.
```
   cmake .. -G "NMake Makefiles" `
    -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded `
    -DCMAKE_BUILD_TYPE=Release `
    -DSENTRY_BUILD_SHARED_LIBS=OFF `
    -DSENTRY_BUILD_RUNTIMESTATIC=ON
```
All the code I'm trying to run is this:
```
    sentry_options_t *options = sentry_options_new();
    sentry_options_set_dsn(options, "<SENTRY_URL>");
    sentry_options_set_release(options, "app@1.2.3");
    sentry_init(options);
```
However when I try to use the sdk, I run into linker errors:
```
installer.lib(packagemanagercore_p.obj) : error LNK2019: unresolved external symbol __imp__sentry_options_new referenced in function "public: void __thiscall QInstaller::PackageManagerCorePrivate::initialize(class QHash<class QString,class QString> const &)" (?initialize@PackageManagerCorePrivate@QInstaller@@QAEXABV?$QHash@VQString@@V1@@@@Z)
installer.lib(packagemanagercore_p.obj) : error LNK2019: unresolved external symbol __imp__sentry_options_set_dsn referenced in function "public: void __thiscall QInstaller::PackageManagerCorePrivate::initialize(class QHash<class QString,class QString> const &)" (?initialize@PackageManagerCorePrivate@QInstaller@@QAEXABV?$QHash@VQString@@V1@@@@Z)
installer.lib(packagemanagercore_p.obj) : error LNK2019: unresolved external symbol __imp__sentry_options_set_release referenced in function "public: void __thiscall QInstaller::PackageManagerCorePrivate::initialize(class QHash<class QString,class QString> const &)" (?initialize@PackageManagerCorePrivate@QInstaller@@QAEXABV?$QHash@VQString@@V1@@@@Z)
installer.lib(packagemanagercore_p.obj) : error LNK2019: unresolved external symbol __imp__sentry_init referenced in function "public: void __thiscall QInstaller::PackageManagerCorePrivate::initialize(class QHash<class QString,class QString> const &)" (?initialize@PackageManagerCorePrivate@QInstaller@@QAEXABV?$QHash@VQString@@V1@@@@Z)
installer.lib(packagemanagercore_p.obj) : error LNK2019: unresolved external symbol __imp__sentry_shutdown referenced in function "public: virtual __thiscall QInstaller::PackageManagerCorePrivate::~PackageManagerCorePrivate(void)" (??1PackageManagerCorePrivate@QInstaller@@UAE@XZ)
```
So then I add `#define SENTRY_BUILD_STATIC 1` into my c++ file, and get new linker errors instead. (see bottom)
It seems like I need to provide `winhttp.lib`, `dbghelp.lib` and possibly one more `lib`. But where do I get them?
Do I need to edit `CMakeLists.txt` somehow so that the build also produces those files?

**When does the problem happen**

This happens during the linking phase.

- [x] During build (linking)
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

```
[vcvarsall.bat] Environment initialized for: 'x86'
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
```

- OS: Windows 10, 64-bit
- Compiler: MSVC 19.16.27045.0
- CMake 3.19.4
- `CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded`, `CMAKE_BUILD_TYPE=Release`, `SENTRY_BUILD_SHARED_LIBS=OFF`, `SENTRY_BUILD_RUNTIMESTATIC=ON`

**Log output**

```
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpCrackUrl@16 referenced in function _sentry__winhttp_send_task
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpOpen@20 referenced in function _sentry__winhttp_transport_start
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpCloseHandle@4 referenced in function _sentry__winhttp_bgworker_state_free
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpConnect@16 referenced in function _sentry__winhttp_send_task
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpOpenRequest@28 referenced in function _sentry__winhttp_send_task
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpSendRequest@28 referenced in function _sentry__winhttp_send_task
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpReceiveResponse@8 referenced in function _sentry__winhttp_send_task
sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp__WinHttpQueryHeaders@24 referenced in function _sentry__winhttp_send_task
sentry.lib(sentry_symbolizer_windows.c.obj) : error LNK2019: unresolved external symbol __imp__SymFromAddr@20 referenced in function _sentry__symbolize
sentry.lib(sentry_unwinder_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp__StackWalk64@36 referenced in function _sentry__unwind_stack_dbghelp
sentry.lib(sentry_unwinder_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp__SymFunctionTableAccess64@12 referenced in function _sentry__unwind_stack_dbghelp
sentry.lib(sentry_unwinder_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp__SymGetModuleBase64@12 referenced in function _sentry__unwind_stack_dbghelp
sentry.lib(sentry_windows_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp__SymSetOptions@4 referenced in function _sentry__init_dbghelp
sentry.lib(sentry_windows_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp__SymGetOptions@0 referenced in function _sentry__init_dbghelp
sentry.lib(sentry_windows_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp__SymInitialize@12 referenced in function _sentry__init_dbghelp
```

**Comment by hjaltisan** [comment]
Turns out I was missing 
```
LIBS += -lwinhttp -ldbghelp
```
In my application, everything seems to work now

**Comment by Swatinem** [comment]
https://github.com/getsentry/sentry-native/blob/1843a913ada69f1e13e20efc815b63ddc4110155/CMakeLists.txt#L353

I wonder if changing that to `PUBLIC` would make sure you get those libs automatically?

**Comment by Mixaill** [comment]
I think @hjaltisan does not use CMake at all.

----

>I wonder if changing that to PUBLIC would make sure you get those libs automatically?

I think it should be something like

```cmake
if(ANDROID)
if(WIN32)
   set(SENTRY_PLATFORM_LIBS "dbghelp version")
elseif(LINUX)
   set(SENTRY_PLATFORM_LIBS "dl log")
elseif(ANDROID)
set(SENTRY_PLATFORM_LIBS "dl rt")
endif()
...
if(SENTRY_LIBRARY_TYPE STREQUAL "static")
    target_link_libraries(sentry PUBLIC ${SENTRY_PLATFORM_LIBS}) 
else()
    target_link_libraries(sentry PRIVATE ${SENTRY_PLATFORM_LIBS})
endif()
```

**Comment by hjaltisan** [comment]
I'm using CMAKE when I build Sentry-Native. But you're correct I'm not using CMAKE when I build my application. I'm building the Qt Installer Framework, and that is built with a specific tool called qmake (which I believe is using CMAKE behind the scenes, but I could be wrong).
I tried building the Sentry-Native library with these changes, and used that in the Installer Framework, but ran into the exact same issue. But as soon as I point qmake to where winhttp and dbghelp are, then everything works. So I'm thinking the issue is my inexperience, assuming that all required lib files would be in the install folder, and not realizing that Windows specific ones would have to be provided by me.

**Comment by Mixaill** [comment]
@hjaltisan 

CMake has **packages** feature which helps you to automatically specify needed .lib files. In your case you the only way is manually specify it.

I think we have some area to improve sentry-native documentation in area of linking with non-CMake projects.

----

So, how it works in general (over-simplificated, bit it is enough for us)



1) For the **dynamic library**, during the linkage phase, linker tries to find position of the functions using the `.lib` files and write the result into the `.dll` or `.exe`  **Import Address Table (IAT)**

![image](https://user-images.githubusercontent.com/704382/107773508-ce3e5400-6d4e-11eb-92cd-48823e047a14.png)

2) During the execution, operating system load dependencies according **Import Address Table (IAT)** and match records with **Export address table (EAT)** of dependencies. **EAT** contains info where the function code is located.

![image](https://user-images.githubusercontent.com/704382/107773765-2f662780-6d4f-11eb-8a5b-4bc30218a2d5.png)

---- 
3) In case of **static library**, we do have code inside the `.lib` files itself. But we do not have information about dependencies
![image](https://user-images.githubusercontent.com/704382/107774610-46f1e000-6d50-11eb-9694-264504ecd256.png)

4) So we need to specify additional `.lib` files to find it
![image](https://user-images.githubusercontent.com/704382/107775079-e7480480-6d50-11eb-81b4-f96cd84f32cf.png)

**Comment by hjaltisan** [comment]
Brilliant! Thanks for this explanation, it was really helpful!
