### ISSUE TITLE
Only ably to get stack trace from Sentry with Frame Pointers Enabled. 

### ISSUE THREAD

**Issue by Notaurious** [getsentry/sentry-native#479]
**Description**

From a release build we do not enable frame pointers. 
We noticed Sentry is unable to grab a stack track in this scenario. 
Is this intended? Is there away around this?

**When does the problem happen**

Build with frame pointers omitted:
https://docs.microsoft.com/en-us/cpp/build/reference/oy-frame-pointer-omission?view=msvc-160

- [ ] During build
- [ ] During run-time
- [x] When capturing a hard crash

**Environment**

- OS: Windows
- Compiler: MSVC 14
- CMake version and config:
                         CMake Version: 3.17
			-DSENTRY_BUILD_RUNTIMESTATIC=ON
			-DCMAKE_SYSTEM_VERSION=6.0
			-DSENTRY_API=ON
			-DBUILD_SHARED_LIBS=OFF
			-DSENTRY_BACKEND=breakpad #crashpad is default for windows
			-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

**Steps To Reproduce**

We can only get a stack trace from sentry if we turn frame pointers on -> (/Oy-) 
   
   if ("${CMAKE_CXX_FLAGS_RELEASE}" STREQUAL "")
		if("$ENV{FRAME_POINTERS}" STREQUAL "ON")
			message( "Set default value to var CMAKE_CXX_FLAGS_RELEASE -> Frame pointers enabled!" )
			set(CMAKE_CXX_FLAGS_RELEASE "/MT /O2 /Ob2 /DNDEBUG /Oy-")
		else()
			message( "Set default value to var CMAKE_CXX_FLAGS_RELEASE" )
			set(CMAKE_CXX_FLAGS_RELEASE "/MT /O2 /Ob2 /DNDEBUG")
		endif()
    endif()

**Log output**

N/A

**Comment by Mixaill** [comment]
It is the intended behavior when you compile application with frame pointer omission

* https://stackoverflow.com/a/13007258

**Comment by jan-auer** [comment]
Based on your description, I'm assuming you're building for _64-bit Windows_.

Since you're using Breakpad, the SDK sends Minidumps to the Sentry server and we compute stack traces there. We are able to compute stack traces even with FPO enabled. For this, you have to provide Sentry with unwind information by uploading the executables in addition to your PDB files. You should see some errors under "Images Loaded" on the Issue Details page that inform you about missing unwind information.

See the [Debug Information Files](https://docs.sentry.io/platforms/native/data-management/debug-files/) and especially [Uploading Files](https://docs.sentry.io/platforms/native/data-management/debug-files/upload/) for a description of how to do this.

**Comment by jan-auer** [comment]
@Mixaill 

> It is the intended behavior when you compile application with frame pointer omission. In theory, DbgHelp's APIs `SymLoadModule64` + `StackWalk64` may generate reliable stacktrace for FPO-enabled modules, but I do not think that this mode is supported in sentry-native.

Not quite. A missing FP indeed makes it harder, but not at all impossible to unwind the stack. For example, C++ exception unwinding still has to work even with FPO. On x86, the CPU always stores the frame pointer in the `ebp` (base pointer) register. On x64, there is `rbp` but it is a general purpose register. For this reason, compilers generate _call frame_ / _unwind information_ and puts it the exception data directory. See:

https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64?view=msvc-160

Stack walkers like `StackWalk64` or also Sentry's processing pipeline can read this information and then compute full stack traces. This is why Sentry requires executables (or DLLs) in addition to PDB files.

**Comment by Mixaill** [comment]
>Sentry's processing pipeline can read this information and then compute full stack traces.

Nice to hear that sentry supports FPO-aware unwinding!

**Comment by Notaurious** [comment]
@jan-auer Sounds like this maybe the missing piece, very promising. Currently uploading PDBs but not the executable (or DLLs). Thank you for confirming support!

**Comment by Swatinem** [comment]
Seems like this was solved by uploading the executable and debug info.
