### ISSUE TITLE
Android + Sentry Native - Section Crashed is not in Loaded Images

### ISSUE THREAD

**Issue by deathlyrage** [getsentry/sentry-native#483]
**Description**

![image](https://user-images.githubusercontent.com/3461558/108609990-24358a80-7426-11eb-88bd-1eb72cd6c1dd.png)

![image](https://user-images.githubusercontent.com/3461558/108609995-331c3d00-7426-11eb-87d6-40992544037f.png)

**When does the problem happen**

- [ ] During build
- [X] During run-time
- [X] When capturing a hard crash

**Environment**

Using the pre-built package from sentry-java which uses sentry-native.

**Steps To Reproduce**

Not sure how to reproduce this one, but i'd say 50% of my crashes experience this issue, other crashes do have libUE4.so loaded.
It might have something to do with my libUE4.so symbol size, (its around 1.8 GB) 

**Log output**

Here is a link to the event on Sentry SAAS if that helps:

https://sentry.io/share/issue/d6ecd48de5bf43db9990a56c42a6807b/

I upload full symbol files and source maps, I'm not sure why sentry can't identify the right loaded symbol and give additional context, eg like line numbers or source code information about the crash.

**Comment by Swatinem** [comment]
One known limitation that we have is that we can’t find the loaded images correctly if they are being loaded directly from `.apk` files. You have to instruct android to properly extract them to disk. The docs give examples of how to achieve this:

https://docs.sentry.io/platforms/android/usage/advanced-usage/#integrating-the-ndk

In particular, the `extractNativeLibs` and `enableUncompressedNativeLibs` options need to be set appropriately.

CC @marandaneto 

> Using the pre-built package from sentry-java which uses sentry-native.

In that case please open an issue in the sentry-java repo next time.

**Comment by Swatinem** [comment]
Another common source of missing loaded images is if you have loaded the library dynamically.
In that case, you might need to flush sentries internal cache that it has:

https://github.com/getsentry/sentry-native/blob/f75ae734b3e7c44ffc7934569b23f700669c7c8d/include/sentry.h#L950-L959

Unfortunately that is something that needs to be done manually right now.

**Comment by marandaneto** [comment]
related to https://github.com/getsentry/sentry-java/issues/1280 so people won't need to set `extractNativeLibs` manually.

**Comment by deathlyrage** [comment]
> Another common source of missing loaded images is if you have loaded the library dynamically.
> In that case, you might need to flush sentries internal cache that it has:
> 
> https://github.com/getsentry/sentry-native/blob/f75ae734b3e7c44ffc7934569b23f700669c7c8d/include/sentry.h#L950-L959
> 
> Unfortunately that is something that needs to be done manually right now.

What's the best way to call this from java? I have tried calling it from native but it doesn't carry over. Should I ask on the getsentry/sentry-java issue tracker instead?

**Comment by marandaneto** [comment]
@deathlyrage 

> but it doesn't carry over.

I don't follow this sentence, what do you mean?

you could call directly from native or you could create a JNI bridge, both would work in the same way

**Comment by deathlyrage** [comment]
Yeah just attempting to call:

#if PLATFORM_ANDROID
	sentry_clear_modulecache();
#endif

Didn't properly clear the module cache for future reports. However my sentry_init() call is done in java, so i'm not sure how thats supposed to work. I'v got no idea how to call sentry_clear_modulecache(); in the java version of the SDK, but it looks burried between interface hell. If anyone has a code example of calling it would be lovely.

**Comment by marandaneto** [comment]
you need to init. the SDK using the manual mode.


options.debugImagesLoader

**Comment by deathlyrage** [comment]
Managed to get it working thanks!

**Comment by Swatinem** [comment]
> Managed to get it working thanks!

@deathlyrage Was it just about calling `sentry_clear_modulecache` or what else did you do here?

I would like to understand this better, since this is one of the most frequent annoyances that Android customers are facing.

**Comment by deathlyrage** [comment]
> > Managed to get it working thanks!
> 
> @deathlyrage Was it just about calling `sentry_clear_modulecache` or what else did you do here?
> 
> I would like to understand this better, since this is one of the most frequent annoyances that Android customers are facing.

This managed to solve the problem, just attempting to move to Native + Android + Breakpad without java NDK version of it so i can get more crash information and minidumps.

https://github.com/getsentry/sentry-native/issues/496

**Comment by deathlyrage** [comment]
Nevermind looks like I spoke too soon, its still broken with sentry_clear_modulecache.

https://sentry.io/share/issue/be797880554f45f29251688e6a4f3e18/

**Comment by deathlyrage** [comment]
It looks like it exclusively happens on Android 11 devices?

**Comment by Swatinem** [comment]
We do know that the module finder is not really reliable in some cases, though its a pain to make that work even as it is.

**Comment by Swatinem** [comment]
@deathlyrage I have been looking at this again, and it seems that in the event you sent (https://sentry.io/share/issue/be797880554f45f29251688e6a4f3e18/), `libUE4.so` is loaded directly from the apk (just hove the filename in the stacktrace).

I recently landed #431 which should support this usecase.

**Comment by Swatinem** [comment]
Closing this for now, as it should be fixed by the new modulefinder. Still working on releasing and uplifting the new version to the Android SDK though.
