### ISSUE TITLE
The SDK can't be built with musl

### ISSUE THREAD

**Issue by ericriff** [getsentry/sentry-native#498]
**Description**

- [X] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Ubuntu 18.04
- Compiler: gcc 8.3.0
- CMake version and config: SENTRY_BACKEND=inproc, SENTRY_TRANSPORT=curl

While cross compiling the sdk for a `mips` platform with `musl` I get:

```
source_subfolder/src/sentry_sync.h:218:36: error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' undeclared here (not in a function); did you mean 'PTHREAD_MUTEX_INITIALIZER'?
 #        define SENTRY__MUTEX_INIT PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```  

A quick google search reveals that `PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP` is a `glibc` extension and it is not available on `musl`.

See:
https://stackoverflow.com/a/53430592/13861425
https://www.openwall.com/lists/musl/2017/02/20/3

Thanks!

**Comment by Swatinem** [comment]
This should be fixed by https://github.com/getsentry/sentry-native/pull/506. I also had to add an ifdef around `execinfo.h` as that does not seem to be available on musl either.

**Comment by ericriff** [comment]
I can confirm this builds with `SENTRY_BACKEND=crashpad` and `SENTRY_BACKEND=inproc`. Unfortunately I can't test it now.
`breakpad` doesn't build on mips+musl.

**Comment by Swatinem** [comment]
Closing this, as at least the build should be working. If I read a few discussions correctly online, musl has no `backtrace` function, so you won’t have backtraces at all at this point.
