### ISSUE TITLE
User information is missing when crashpad handles a crash

### ISSUE THREAD

**Issue by olexiys2** [getsentry/sentry-native#499]
User information is missing when crashpad handles a crash

I try to use crashpad as a backend to handle crashes. When crash happens, the event displayed in Sentry  doesn't have any user information, which was set with a call to sentry_set_user(). 
When "regular" sentry events are sent (with sentry_capture_event()), the user information is present.

I use Sentry crashpad (not standalone). Initialization of sentry happens in this sequence:
   sentry_options_t* options = sentry_options_new();
   ,,, options set ..
  sentry_init(options);
 sentry_value_t user = sentry_value_new_object();
  .. user options set..
 sentry_set_user(user);

I am new with Sentry so I may be missing something basic, but so far I was unable to find it out from documentation.
I use 0.4.8 SDK.

**When does the problem happen**

- [ ] During build
- [ ] During run-time
- [x ] When capturing a hard crash

**Environment**
- OS: Windows 10, 64-bit
- Compiler: MSVC 19
- CMake version and config: 3.17.2, SENTRY_BACKEND=crashpad

**Comment by olexiys2** [comment]
closing

**Comment by shanekoss-output** [comment]
@olexiys2 - did you get this to work?
