### ISSUE TITLE
get stack trace for a *caught* exception (in the try-catch code)

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-native#515]
Hi thanks for the lib! I wonder how can we get StackTrace for a *caught* exception (in the try-catch code)?

For example:

```
void bad_func() { throw runtime_error("ouch!"); }
void middle_func() { bad_func(); }
void outer_func() {
  try{
    middle_func();
  }catch(const exception& e) {
    CAPTURE_THE_EXCEPTION_TO_SENTRY_WITH_STACK_TRACE(e);
  }
}
```

I do know how to capture the *exception* to sentry; but I do not know how to know the *stack trace*? Thanks!

**Comment by Swatinem** [comment]
We don’t hook into the c++ exception throwing mechanism, so there is currently no way to get the stacktrace *at the time of throw*, you would have to do that yourself.

**Comment by fzyzcjy** [comment]
@Swatinem Thanks all the same
