### ISSUE TITLE
Cannot clone release/0.4.9

### ISSUE THREAD

**Issue by jracle** [getsentry/sentry-native#526]
**Description**

**When does the problem happen**

- [x ] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: all

**Steps To Reproduce**

Clone release/0.4.9

- external/breakpad fails to retrieve commit 'bbc999925cadc1b40f153f1a695062a88be5891a'.
- external/libunwindstack-ndk fails to retrieve commit '08419958d963276c154e570203a342878f50ca41'.

**Comment by jan-auer** [comment]
Thanks, we'll look into that. You can download the source code with all dependencies resolved here:
https://github.com/getsentry/sentry-native/releases/download/0.4.9/sentry-native.zip

**Comment by jracle** [comment]
Thanks Jan, already did it.
Chees

**Comment by Swatinem** [comment]
Are you attempting a fresh clone? Or are you pulling from an older revision?

Updating from an older revision, you would need to change the submodule origin, since we switched to our own fork:

    cd external/breakpad && git remote set-url origin https://github.com/getsentry/breakpad.git

And then make sure to always use `git submodule update --recursive` maybe even with the `--init` flag as well.

**Comment by jracle** [comment]
Good catch, indeed I was pulling from an older revision.. Oh you also did that for libunwindstack-ndk right?

**Comment by jracle** [comment]
OK I've fixed breakpad, but no luck with libunwindstack-ndk. Wonder what is going on there

**Comment by jracle** [comment]
Oh ok I see :) submodule update, sorry guys indeed! Thanks
