### ISSUE TITLE
Make building for clang/libc++ simpler

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-native#531]
**Description**

I need to compile on Linux to link with a project that uses clang and libc++ (rather than gcc and libstdc++)
It took me a few hours of googling and trial and error to figure out the solution.

Either it could  be documented or made simpler via cmake config

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**
Ubuntu 18, with cmake 3.30

**Steps To Reproduce**

To successfully compile sentry-native, the following needs to be done:
1. Install prerequisites 
  - zlib-dev
  - libssl-dev
  - clang
  - libc++-dev
  - libc++abli-dev
 2. run cmake with the following extra options:
    ` -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" `

**Comment by Swatinem** [comment]
I think this is rather something that should be documented on the libc++ side, as I bet this affects all c++ projects essentially.

**Comment by kristjanvalur** [comment]
I don't know, this SDK has a long list of compatible environments.  I don't
see a problem with giving build suggestions for various platforms and
targets.  I already found that the default instructions don't work on
windows (see PR #528).  Pre-requisited libs also _probably_ should be
listed.
I'll be happy to make a PR with suggested Linux additions.

fim., 29. apr. 2021 kl. 10:26 skrifaði Arpad Borsos <
***@***.***>:

**Comment by madebr** [comment]
The easiest way to address your problem would be to use cmake toolchain files.

e.g. create a file names `toolchain-clang-libcxx.cmake`:
```
find_program(CMAKE_C_COMPILER NAMES clang)
find_program(CMAKE_CXX_COMPILER NAMES clang++)

set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_STARED_LINKER_FLAGS_INIT "-stdlib=libc++")
```

and build the project with:
```
cmake -S $path_to_sentry_native -B build -DCMAKE_TOOLCHAIN_FILE=/path/to/toolchain-clang-libcxx.cmake
cmake --build build --parallel
```

No changes need to be done to sentry-native's cmake scripts.
