### ISSUE TITLE
libunwindstack-ndk commit does not point to master

### ISSUE THREAD

**Issue by OlivierLDff** [getsentry/sentry-native#532]
**Description**

libunwindstack-ndk reference is `0841995`. But this commit doesn't exist in master.
I struggled to understand what was hapenning, because this commit is not into any branch.
The commit lives inside PR https://github.com/getsentry/libunwindstack-ndk/pull/3

Correct commit should be `abcfef9e77ec6c8b0fe179591e354b8509727686`.

**When does the problem happen**

Git submodules init does not work with git version or inside docker (not sure what cause the problem).

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

I think this might be related to git version?
It's working on ubuntu 18 with git 2.17.1
It's not working on ubuntu 16 with git 2.7.4

Build fail inside this docker : https://github.com/OlivierLDff/QtLinuxCMakeDocker

- OS: Ubuntu 16
- Compiler: gcc7
- CMake version and config: 3.19 (not related)
- git 2.7.4

**Steps To Reproduce**

```bash
docker run --rm reivilo1234/qt-linux-cmake:qt5.15.2-gcc7 git clone https://github.com/getsentry/sentry-native --recursive
```

**Log output**

```
## ... ##
Cloning into 'external/libunwindstack-ndk'...
fatal: reference is not a tree: 08419958d963276c154e570203a342878f50ca41
Cloning into 'external/third_party/lss'...
Submodule path 'external/third_party/lss': checked out '171a36a8e0d1e456f63d342a09f811f9273a64af'
Unable to checkout '08419958d963276c154e570203a342878f50ca41' in submodule path 'external/libunwindstack-ndk'
```

**Comment by Swatinem** [comment]
Oh yes, that must have slipped through somehow. I pushed https://github.com/getsentry/sentry-native/commit/3fdaa5d5eeb306fa2d13ca66ec25e656960d19b8 to fix up the submodule ref.
