### ISSUE TITLE
Crash dump upload out of process

### ISSUE THREAD

**Issue by mattgodbolt** [getsentry/sentry-native#534]
The fact that crash dumps aren't uploaded upon crashing, but on restart was surprising and I didn't spot any documentation explaining this. I wrote:

> This is super surprising behaviour and caught me off-guard. My use case is a bunch of command-line tools; and it's not obvious that the user will re-run after a crash to do the upload. Is there any way to schedule sweeping of crash dumps somehow?

_Originally posted by @mattgodbolt in https://github.com/getsentry/sentry-native/issues/530#issuecomment-836779309_

**Comment by mattgodbolt** [comment]
(in other systems before I've been able to configure something as the global crash handler in `/proc/sys/kernel/core_pattern ` or similar to handle crashes globally and upload them. Was hoping sentry could help me do the same here)

**Comment by cmanallen** [comment]
@Swatinem Is this now the default on Linux?

**Comment by supervacuus** [comment]
Yes, `crashpad` is the default backend on Linux, and the difference in behavior is documented in https://docs.sentry.io/platforms/native/advanced-usage/backend-tradeoffs/
