### ISSUE TITLE
Sentry failed to use crashpad after crash

### ISSUE THREAD

**Issue by ahmadbeirkdar** [getsentry/sentry-native#539]
**Description**

On my test machine, and use machines, when a hard crash occurs, sentry fails to use crashpad to upload the attachment. The following error shows up in the console:

`[2157:81156:20210130,171500.365458:ERROR http_transport_mac.mm:283] An SSL error has occurred and a secure connection to the server cannot be made. (NSURLErrorDomain -1200)`

Note it does not occur on the development machine, but occurs on ever test and user machine.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [x] When capturing a hard crash

**Environment**

- OS: [e.g. Windows 10, 64-bit] macOS 10.15
- Compiler: [e.g. MSVC 19] apple-clang
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc] 3.20.2, crashpad backend

**Steps To Reproduce**

As mentioned above in the description

**Comment by Swatinem** [comment]
Interesting. Do you have proxies configured? Those are not being passed down to crashpad at the moment
