### ISSUE TITLE
Starting an older version of sentry after running 0.4.9 may crash in sentry_init

### ISSUE THREAD

**Issue by mcdurdin** [getsentry/sentry-native#542]
**Description**

If you start an older version of sentry (in this case 0.2.3), and it refers to a sentry-db location which has been written to by version 0.4.9, then sentry will crash in `sentry_init`:

```
(2b08.68cc): Unknown exception - code c0000090 (first chance)
(2b08.68cc): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
```

Ref: https://github.com/keymanapp/keyman/issues/5188

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10 x64 [e.g. Windows 10, 64-bit]
- Compiler: MSVC2019 [e.g. MSVC 19]
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Steps To Reproduce**

**Log output**

**Comment by Swatinem** [comment]
Do you have any more information on this? The provided error codes are not much to go by.
Having a downgrade path is not really something we have ever considered, but out of the top of my head, I can’t really say in which way the sentry-db changed since that version (which is over a year old, and super unsafe, so updating is very much recommended)

**Comment by mcdurdin** [comment]
> Do you have any more information on this?

Yeah, sorry -- I kicked myself for not capturing the crashdump. Unfortunately, when I tried to reproduce this today, I was unable to reproduce it. If/when I repro it, I'll definitely save a crashdump (although given we've now worked around it, this may not happen).

> which is over a year old, and super unsafe, so updating is very much recommended

Well, we are doing the update, but it hasn't gone as smoothly as we might have hoped...

Is 0.4.9 considered production ready? (semver below 1.0 would suggest not?) I have not been able to find any guidance anywhere on this; the sentry documentation does not have any warnings on sentry-native's readiness for use.

**Comment by mcdurdin** [comment]
[sentry_init_crash.zip](https://github.com/getsentry/sentry-native/files/6594802/sentry_init_crash.zip)

I got a repro for this today. Sadly I don't think I have the pdb for that version of sentry.dll (2.3) so this may not help much unless you are really keen to spelunk in ASM. Attached FWIW.

**Comment by kahest** [comment]
As pointed out above, having a downgrade path is not something we consider for the time being, but in any case the SDK should degrade gracefully, i.e. not crash in `sentry_init` but.
