### ISSUE TITLE
Function json_serialize_string(...) does not correctly escapes backslash (\) character

### ISSUE THREAD

**Issue by martinsliwka** [getsentry/sentry-native#55]
Function `json_serialize_string(...)` used in `Value::to_json(...)` does not correctly escapes backslash (\\) characters and serialization generates invalid json. Therefore, sending events fails on Windows because event contains debug_meta key containing list of modules including backslash characters.

**Comment by deathlyrage** [comment]
Ran into this issue too, would be nice to get a fix soon.

**Comment by jan-auer** [comment]
Fixed with `0.1.1`
