### ISSUE TITLE
What do you call a fly with broken wings?

### ISSUE THREAD

**Issue by chadwhitacre-test** [getsentry/sentry-native#557]
A walk.

**Comment by jan-auer** [comment]
Are you going to close this out or should we interact with the bot, @chadwhitacre?

**Comment by chadwhitacre** [comment]
Hey, Native team is paying attention! 😅

> should we interact with the bot

Yes, please. Go ahead and apply a label (any label) and the bot should remove `Status: Untriaged`.

P.S. I was talking with @Swatinem behind the scenes but highly async.

**Comment by chadwhitacre-test** [comment]
Bot is working! Thanks @jan-auer. :)
