### ISSUE TITLE
Can't compile sentry_crashpad 0.1.0 x32 Release

### ISSUE THREAD

**Issue by vkalitkin** [getsentry/sentry-native#56]
crashpad_util.lib(capture_context_win.obj) : error LNK2026: module unsafe for SAFESEH image.
crashpad_util.lib(safe_terminate_process.obj) : error LNK2026: module unsafe for SAFESEH image.
bin\Release\crashpad_handler.exe : fatal error LNK1281: Unable to generate SAFESEH image.
Done building project "crashpad_handler.vcxproj" -- FAILED.

crashpad_util.lib(capture_context_win.obj) : error LNK2026: module unsafe for SAFESEH image.
crashpad_util.lib(safe_terminate_process.obj) : error LNK2026: module unsafe for SAFESEH image.
   Creating library bin\Release\sentry_crashpad.lib and object bin\Release\sentry_crashpad.exp
bin\Release\sentry_crashpad.dll : fatal error LNK1281: Unable to generate SAFESEH image.
Done building project "sentry_crashpad.vcxproj" -- FAILED.

Can you release ready to use Sentry Native SDK precompiled binaries for VS2017?

**Comment by jan-auer** [comment]
Thanks for reporting this! 

We hadn't tested building with `/SAFESEH` on x86 before. Will be fixed in the next release.
