### ISSUE TITLE
Feature request: cancel session.

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-native#560]
We have a project in which automatic session tracking is enabled and sentry starts by default, including for content developers.  However, some developer choose to disable sentry after it has been started via scripting.  In this case, they would be closing a successful session.  It would be useful to be able to cancel the session prior to closing sentry, to avoid having such a run end up in the successful run tally.

**Comment by Swatinem** [comment]
That is good feedback, I have forwarded this internally to figure out how this fits in the broader release health story.
