### ISSUE TITLE
feature request:  Add attachment file at runtime

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-native#561]
The attachment feature requires attachments to be specified before starting up sentry.  Frequently, attachment file names are not known in advance.  It would be useful to be able to add attachment locations after starting sentry.

**Comment by Swatinem** [comment]
There is https://github.com/getsentry/sentry-native/pull/433 opened for quite some time, but it never went anywhere since it was unclear how the API fits into the unified API spec.

**Comment by kristjanvalur** [comment]
I see. Should have grepped more for this.  Closing this then as a duplicate.
