### ISSUE TITLE
feature request:  Clarify use of experimental api, to dump tracebacks

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-native#562]
The sentry api has an "experimental" part.  I am interested in the ability to manually emit a traceback at the time of a crash, for example, during the `before_send` callback.
 I can see the apis like `sentry_unwind_stack_from_ucontext()` but this is undocumented.  Also `sentry.h` does not apparently ever provide one with a `sentry_ucontext_t *` to use.  Additionally, the `void **stacktrace_out, size_t max_len` arguments are not explained (who owns memory, what does it contain, etc)

**Comment by Swatinem** [comment]
I tried to expand on the docs a bit in https://github.com/getsentry/sentry-native/pull/564. Currently, only unwinding from the current frame (`sentry_unwind_stack(NULL, x, y)`) is supported across all platforms. The caller has to allocate (probably on the stack) the instruction pointers.
