### ISSUE TITLE
Windows: if shutdown timeout expires the background thread is not closed properly.

### ISSUE THREAD

**Issue by smibe** [getsentry/sentry-native#567]
**Description**
On Windows WinHttp is used. WinhttpReceiveResponse has a default timeout of about 30 seconds. If we are running into the timoeout but in the meantime the application is closed the background thread is still running and the application hangs.

**When does the problem happen**
WinhttpReceiveResponse  or any other WinHttp function is running into a timeout.

**Environment**

Windows (all versionns) 
MSVC 19
SENTRY_BACKEND=none

**Comment by Swatinem** [comment]
#571 was merged and released, which should take care of this. Thanks @smibe
