### ISSUE TITLE
[Windows][0.4.10] Unit test fails when changing output directory name

### ISSUE THREAD

**Issue by Forbinn** [getsentry/sentry-native#573]
**Description**

If the build folder name changes between the build and the execution of the unit test, 2 of them fails. If you change the name of the folder back to its "original" name then all tests pass fine.

This issue occurs if you build the sentry library as a shared library or not. The test that fail is slightly different but it fail anyway.

Also I noticed that no matter what build type (Release / Debug) I precise, the library and test binary are always placed in a `Debug` folder: is this intended?

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10, 64-bit
- Compiler: MSVC 16
- CMake version and config: `3.20.5`, `SENTRY_BACKEND=breakpad`, `SENTRY_TRANSPORT=winhttp`

**Steps To Reproduce**

I have used git bash for Windows for those commands.

- `git clone -b 0.4.10 https://github.com/getsentry/sentry-native.git`
- `cd sentry-native`
- `git submodule update --init`
- `cmake -G "Visual Studio 16 2019" -A "x64" -DSENTRY_TRANSPORT="winhttp" -DSENTRY_BACKEND="breakpad" -DSENTRY_BUILD_TESTS="ON" -Wno-dev -DCMAKE_BUILD_TYPE=Release -B build .`
- `cmake --build build`
- `mv build Release`
- `./Release/tests/unit/Debug/sentry_test_unit.exe`

**Log output**

```
Test background_worker...                       [ OK ]
Test basic_consent_tracking...                  [ OK ]
Test basic_function_transport...                [ OK ]
Test basic_http_request_preparation_for_event... [ OK ]
Test basic_http_request_preparation_for_event_with_attachment... [ OK ]
Test basic_http_request_preparation_for_minidump... [ OK ]
Test buildid_fallback...                        [ OK ]
Test count_sampled_events...                    [ OK ]
Test custom_logger...                           [ OK ]
Test dsn_parsing_complete...                    [ OK ]
Test dsn_parsing_invalid...                     [ OK ]
Test dsn_store_url_with_path...                 [ OK ]
Test dsn_store_url_without_path...              [ OK ]
Test empty_transport...                         [ OK ]
Test fuzz_json...                               [ OK ]
Test init_failure...                            [ OK ]
Test invalid_dsn...                             [ OK ]
Test invalid_proxy...                           [ OK ]
Test iso_time...                                [ OK ]
Test lazy_attachments...                        [ OK ]
Test module_addr...                             [ OK ]
Test module_finder...                           [ OK ]
Test mpack_newlines...                          [ OK ]
Test mpack_removed_tags...                      [ OK ]
Test os...                                      [ OK ]
Test page_allocator...                          [ OK ]
Test path_basics...                             [ OK ]
Test path_current_exe...                        [ OK ]
Test path_directory...                          [ OK ]
Test path_joining_unix...                       [ OK ]
Test path_joining_windows...                    [ OK ]
Test path_relative_filename...                  [ OK ]
Test procmaps_parser...                         [ OK ]
Test rate_limit_parsing...                      [ OK ]
Test recursive_paths...                         [ OK ]
Test sampling_before_send...                    [ OK ]
Test serialize_envelope...                      [ OK ]
Test session_basics...                          [ OK ]
Test slice...                                   [ OK ]
Test symbolizer...                              [ FAILED ]
  test_symbolizer.c:17: Check info->symbol && strstr(info->symbol, "test_function") != 0... failed
  test_symbolizer.c:20: Check info->symbol_addr == &test_function... failed
Test task_queue...                              [ OK ]
Test uninitialized...                           [ OK ]
Test unwinder...                                [ FAILED ]
  test_unwinder.c:45: Check 0 == 1... failed
  Unhandled SEH exception... failed
    Exception code:    0xc0000005
    Exception address: 0x00007FF7BCC375A0
  Access violation.
Test url_parsing_complete...                    [ OK ]
Test url_parsing_invalid...                     [ OK ]
Test url_parsing_partial...                     [ OK ]
Test uuid_api...                                [ OK ]
Test uuid_v4...                                 [ OK ]
Test value_bool...                              [ OK ]
Test value_collections_leak...                  [ OK ]
Test value_double...                            [ OK ]
Test value_freezing...                          [ OK ]
Test value_int32...                             [ OK ]
Test value_json_deeply_nested...                [ OK ]
Test value_json_escaping...                     [ OK ]
Test value_json_invalid_doubles...              [ OK ]
Test value_json_locales...                      [ OK ]
Test value_json_parsing...                      [ OK ]
Test value_json_surrogates...                   [ OK ]
Test value_list...                              [ OK ]
Test value_null...                              [ OK ]
Test value_object...                            [ OK ]
Test value_string...                            [ OK ]
Test value_unicode...                           [ OK ]
Test value_wrong_type...                        [ OK ]
FAILED: 2 of 65 unit tests have failed.
```

**Comment by Swatinem** [comment]
I have been looking into this, and I’m afraid its not easily fixable.

These tests depend on being able to symbolize some functions. The pdb is needed for that, because otherwise it will only resolve the exported public symbol stubs, which is wrong.

But cmake by default embeds the absolute build-time path of the pdb file into the exe.

It would be possible to make that a relative path by using the linker option `/PDBALTPATH:%_PDB%`.
See https://docs.microsoft.com/en-us/cpp/build/reference/pdbaltpath-use-alternate-pdb-path:

> %_PDB% expands to the file name of the actual .pdb file without any path information

But that seems to be broken in cmake since at least 6 years (https://gitlab.kitware.com/cmake/cmake/-/issues/15865 and the original https://cmake.org/Bug/view.php?id=15865)

**Comment by Forbinn** [comment]
Thank you for the response. I understand the problem and I can deal with it for the unit test but I'm wondering if this can affect applications build with sentry.

What I mean by that is: if I use the sentry library to build an application, then ship this app to a customer, will I have trouble with some function calls in the sentry SDK?

**Comment by Swatinem** [comment]
No, this is very specific to the assertions that our unittests make, this should have no effect on any apps that use the SDK. The crash that you see is also very specific to the unit test. The observed crash is also because it does not find the stack frame it is looking for based on the function name.

**Comment by Forbinn** [comment]
Ok, that's what I wanted to be sure about. Thank you for your help.
