### ISSUE TITLE
Block until flush previous crashes

### ISSUE THREAD

**Issue by Renat060888** [getsentry/sentry-native#575]
**Description**

Hello everyone!

I noticed that if an error is found immediately after sentry initialization, it does not have time to send a dump to the server. Can I somehow block execution (e.g. sentry_inti( ..., block_until_flush )) before the data (crash on previous launch) is unploaded? ( sorry for my eng :)

I'm testing simple fake SEGFAULT just after sentry init.

**When does the problem happen**
During run-time

**Environment**
OS: Linux 4.19.0
Compiler: clang-12
Sentry: native 0.4.9 breakpad
CMake: 3.20.1

**Comment by Swatinem** [comment]
We have a method to explicitly flush queued events in other SDKs. Implementing this for native would give you an explicit `sentry_flush(timeout)` or similar method, so you can call that directly and decide on a suitable timeout.

**Comment by Swatinem** [comment]
Landed in #670, we will be tagging a new release soon-ish.
