### ISSUE TITLE
Building using VS 2019 16.3.1 fails

### ISSUE THREAD

**Issue by martinsliwka** [getsentry/sentry-native#58]
`sentry-native\gen_windows\crashpad_zlib.vcxproj` defines macro _`__clang__`_ and compilation fails with lots of similar errors

> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\include\vcruntime_string.h(18,1): error C2059: syntax error: '['

because function declarations in `vcruntime_string.h` are prefaced by _`_NODISCARD`_ macro which, for _`__clang__`_, is expands to `[[nodiscard]]`

**Comment by jan-auer** [comment]
Fixed with `0.1.1`. Thanks for reporting!
