### ISSUE TITLE
Release string can't have a forward slash

### ISSUE THREAD

**Issue by ericriff** [getsentry/sentry-native#581]
**Description**
If the string passed to `sentry_options_set_release()` contains a forward slash (`/`), my project builds just fine but the crash reports show no release tag. I don't know if this is an issue with the native SDK or the webpage.
This is on the latest version, 0.4.11. Not sure about older versions.
 

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Steps To Reproduce**

Set a release name with no forward slashes, then there is no problem.
`sentry_options_set_release(options, "test-example-release");`

![Screenshot from 2021-07-18 21-56-34](https://user-images.githubusercontent.com/57375845/126088383-81a94f28-8a99-4395-b36d-544ae8ad4e79.png)

Add a forward slash, then the page shows no release tag.
`sentry_options_set_release(options, "test-example/release");`

![Screenshot from 2021-07-18 21-51-55](https://user-images.githubusercontent.com/57375845/126088242-d377f696-d540-4080-9643-d96759dea3fc.png)

**Comment by flub** [comment]
Releases are not supposed to have slashes according to the docs: https://docs.sentry.io/platforms/rust/configuration/releases/#bind-the-version

**Comment by ericriff** [comment]
Duh. I missed that. Sorry about the noise.
Closing this.

**Comment by flub** [comment]
Out of curiosity, would you have preferred if the sdk stripped the invalid characters instead of silently not setting the release tag?

**Comment by ericriff** [comment]
I was considering during the stripping myself, so but I guess it would be better if it is done internally by the SDK.
In order for this stripping to make sense, the webpage would have to do the same. Otherwise the strings won't match.

By the way this is on the c++ native SDK, your link took me to the rust sdk. Regardless I navigated the docs and came across the same warnings for the C++ sdk.

**Comment by ericriff** [comment]
We've decided to sanitize the version string by replacing the forbidden chars with dashes. The same sanitization will be performed when we upload the commit metadata so they match.
So I guess it would be better if sentry does this internally for us instead of ignoring the string silently.

**Comment by flub** [comment]
> By the way this is on the c++ native SDK, your link took me to the rust sdk. Regardless I navigated the docs and came across the same warnings for the C++ sdk.

whoops, but yes the rules are the same for all SDKs
