### ISSUE TITLE
Add `log4cplus` integration

### ISSUE THREAD

**Issue by darkknight0007** [getsentry/sentry-native#589]
There's an integration of Sentry with log4j and log4net
https://docs.sentry.io/platforms/java/guides/log4j2/
https://docs.sentry.io/platforms/dotnet/guides/log4net/

There's also sentry-native support c++
https://github.com/getsentry/sentry-native

So it'll be nice if there is an integration of Sentry with log4cplus also.

**Comment by Swatinem** [comment]
See https://github.com/log4cplus/log4cplus for reference.

It might be nice to have, yes. But I don’t think our team will actively work on this in the near future, however contributions are always welcome.
