### ISSUE TITLE
mingw-w64 cross compile from linux failure.

### ISSUE THREAD

**Issue by OmniBlade** [getsentry/sentry-native#590]
**Description**

Cross compile with mingw-w64 fails due to case sensetive file system when building minichromium dependency.

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [Linux]
- Compiler: [mingw-w64-gcc]
- CMake version and config: [3.21, SENTRY_BACKEND=crashpad]

**Log output**

third_party/mini_chromium/mini_chromium/base/rand_util.cc:30:10: fatal error: NTSecAPI.h: No such file or directory
 #include <NTSecAPI.h>
          ^~~~~~~~~~~~

**Comment by mitsuhiko** [comment]
While this issue is absolutely valid, the actual issue here is happening in crashpad which is an upstream dependency. While we do have custom patches on top of crashpad, this particular issue is quite fundamental to crashpad and should be fixed there.
