### ISSUE TITLE
minidump report  doesn't work with uploaded sym file to render proper information

### ISSUE THREAD

**Issue by austinlin7732** [getsentry/sentry-native#61]
I upload the minidumps to sentry server, but it show `<unknown>` for the function name with the minidump report, 
I know it need symbol file, how do I get the symbol file ? 
Or I just need to upload the binary and library which are build with "-g" option?  

The server remind me that missing 2 files, how do I upload the required file ?  
_There were 2 errors encountered while processing this event_
use curl -x POST with any option ?

![image](https://user-images.githubusercontent.com/50258355/66387750-2f397780-e9f7-11e9-94f8-af26b7cef41e.png)

**Comment by afedor** [comment]
Well, first you need to create a debug symbols file.  On Linux you'd use "dump_syms".  It seems like dump_syms should be built with the sentry-native code, but it's not.  But you can get it from the breakpad package itself.

Then you need to upload the symbols file to sentry.  The best way to do that is using sentry-cli.  So all together it looks something like this:

```
dump_syms $APP > $APP.sym
export SENTRY_ORG=XXX
export SENTRY_PROJECT=$PROJECT
export SENTRY_AUTH_TOKEN=XXXXXXXXXXXXXXXXX
sentry-cli upload-dif -t breakpad "$APP.sym" 2>&1 >/dev/null
```

**Comment by austinlin7732** [comment]
Hi @afedor , 

Thanks for your introduction, but after I upload required sym file, it still not work for processing the event.  

1)  upload the sym file and done as below screen shot
$ sentry-cli upload-dif -o test-hcr -p minidump /path/to/sym/file

![image](https://user-images.githubusercontent.com/50258355/66577031-4325da80-ebab-11e9-830f-846f7c7a8cae.png)

2.  In my project, it seems not updated the status with my uploaded debug files

![image](https://user-images.githubusercontent.com/50258355/66577141-723c4c00-ebab-11e9-96a3-8c5e7f6715d4.png)

3.   The <unknown> text is still there, 
![image](https://user-images.githubusercontent.com/50258355/66577241-9861ec00-ebab-11e9-9d13-bc8ca85ca855.png)


Q: Does this sentry server's issue ?

**Comment by afedor** [comment]
Did you upload the crash report before uploading the sym files?  AFAIK, Sentry doesn't reprocess old events when new sym files get uploaded. Other than that I don't know what's wrong - the sym file ids match so it seems like it should work.

**Comment by austinlin7732** [comment]
Ok, 
I deleted the event and upload the minidump file for some try.  
Let me delete the project and upload the crash report first, then upload the sym files again.

**Comment by jan-auer** [comment]
> Do we need to choose any specific "Built-in Repositories" for processing C symbol file?

No, you don't need any by default. If you're using libraries from a certain vendor, then activate that symbol server. Microsoft and iOS are active by default.

**Comment by jan-auer** [comment]
> Or I just need to upload the binary and library which are build with "-g" option?

This is exactly what you need to do. You can verify that you've uploaded the correct file in the list of uploaded debug files. Check two things:

 1. The identifier (UUID-like hash) matches **exactly**. 
 2. There is a `debug` tag shown with the file (as you can see in your screen shot). This allows Sentry to symbolicate. You mostly also want `unwind` for Minidumps. Note that you might need to upload multiple files for this. 

Of course, then make sure to upload the files first so that they get applied.

**Comment by austinlin7732** [comment]
Hi   @afedor @jan-auer, 
Thanks for your kindly help.  
@jan-auer, 
> Of course, then make sure to upload the files first so that they get applied.
I follow your comment, upload native debug information file and then upload minidump file by `curl`.
It work with porting information as below,  


> 2. There is a `debug` tag shown with the file (as you can see in your screen shot). This allows Sentry to symbolicate. You mostly also want `unwind` for Minidumps. Note that you might need to upload multiple files for this.

**Comment by austinlin7732** [comment]
Hi @afedor @jan-auer,
Thanks for your kindly help.

@jan-auer,
> Of course, then make sure to upload the files first so that they get applied.  　　

I think I follow the correct steps, but still meet some problems.  

**steps:**
1.I modify the example_breakpad.c, src/api.c and rebuild for example_breakpad and libsentry_breakpad.so 
2.upload the debug info binary to sentry
3.Run example_breakpad and upload the minidumps report by curl
**Result:**
    The crash report seems not handled properly by sentry.   
    It is good that libsentry_breakpad.so is handled, but _example_breakpad is not handled_
![image](https://user-images.githubusercontent.com/50258355/66634550-e4f70700-ec3f-11e9-9b22-d615b0064df9.png)


**Check Items**
1.The UUID of the debug file in server is the same as the uploaded ones  => pass

_Check before uploading:_
![image](https://user-images.githubusercontent.com/50258355/66634433-a4978900-ec3f-11e9-8794-c33168d9b7cc.png)

_Check after uploding:_
![image](https://user-images.githubusercontent.com/50258355/66634490-c5f87500-ec3f-11e9-9a49-86e17f7beeda.png)

2.  The UUID of example_breakpad sentry required is different  => **Fail**
![image](https://user-images.githubusercontent.com/50258355/66634599-fcce8b00-ec3f-11e9-9632-0157b6cc4f65.png)

![image](https://user-images.githubusercontent.com/50258355/66634614-03f59900-ec40-11e9-8c2c-d8fa1aa714aa.png)

Q1: Why sentry server need different UUID of example_breakpad, I think this is the root cause, do I miss anything ?


> There is a debug tag shown with the file (as you can see in your screen shot). This allows Sentry to symbolicate. You mostly also want unwind for Minidumps. Note that you might need to upload multiple files for this.   

Yes, I aware that many shared library is required to upload, 
Q2:  is there any suggestion ?  or just let binary without having unwind tag ?

**Comment by jan-auer** [comment]
> Why sentry server try to find the different UUID of example_breakpad?

This is indeed strange. Usually, this only happens when the crash happened on a different build than what was uploaded to Sentry. The UUIDs also look very similar. Could you send the minidump and executable to jan.auer@sentry.io? There might be an issue with how we read these identifiers. 

Another issue is that `example_breakpad` occurs twice in your _"Loaded Modules"_ section. Both are reported with different load addresses and image sizes. Once I have the minidump, I can take a closer look at this.

**Comment by austinlin7732** [comment]
> Could you send the minidump and executable to [jan.auer@sentry.io](mailto:jan.auer@sentry.io)? 

@jan-auer  I mailed the minidump and executable to you

> Another issue is that `example_breakpad` occurs twice in your _"Loaded Modules"_ section. Both are reported with different load addresses and image sizes.   

I am not sure whether I removed `example_breakpad` and upload it with several times cause this issue.  

I also use `sentry-cli difutil check`  cmd to check the `example_breakpad`, it is the same as the uploaded one 
![image](https://user-images.githubusercontent.com/50258355/66698049-4a64f980-ed0d-11e9-8f1c-10cdee0a83fb.png)

**Comment by austinlin7732** [comment]
> @jan-auer I mailed the minidump and executable to you, please kindly let me know if you doesn't receive it

Hi @jan-auer, 
Does the information I mailed you enough for debugging ?

**Comment by austinlin7732** [comment]
Hi @jan-auer,    

Please give me some hint that I can know whether I should keep find the root cause or just wait for sentry server side to be fixed.    
If it is also sentry server problem I can just wait, thank you. 

For the uploaded debug file, if they are already show `unwind, debug, symtab` as below,  
Does it mean the debug file I upload is no problem  ?  I don't need to do other thing with compiler, tight ?
![image](https://user-images.githubusercontent.com/50258355/69535131-29532200-0fb6-11ea-9765-3eb0d6a06292.png)

I'm asking this because I find that 
**[with arm target]**   
`$ file libsentry_breakpad.so`  showing BuildID   **=>** crash report can be partial handle if crash in `libsentry_breakpad.so`
![image](https://user-images.githubusercontent.com/50258355/69535222-6a4b3680-0fb6-11ea-9671-f1976069c7c0.png)

Other library I compile on my own doesn't show up the BuildID    **=>** crash report can be partial handle if crash in `libsentrycfg.so`
`$ file libsentrycfg.so` 
![image](https://user-images.githubusercontent.com/50258355/69535299-936bc700-0fb6-11ea-98a1-34216f4a8a51.png)


Do I need to care about `BuildID`  ?  
My inference is that I don't need to care the BuildID with `file` command, cuz I try with Ubuntu target, 
`$ file libsentry_breakpad.so`  is not showing BuildID, but it can show something like below, 
![image](https://user-images.githubusercontent.com/50258355/69535831-b054ca00-0fb7-11ea-9198-8217563bd191.png)

I need to get some suggestion to know whether my side is also missing something or not, thanks

**Comment by Swatinem** [comment]
@austinlin7732 
From your report, I can’t really see what is going on.
But as mentioned in your other report, we will be releasing a rewritten version of `sentry-native` later today, so please check again with that one, and create a new issue if things still don’t work.
