### ISSUE TITLE
Sentry APIs block after failed sentry_init

### ISSUE THREAD

**Issue by zakalawe** [getsentry/sentry-native#638]
**Description**

When `sentry_init` returns non-zero, in my case due to broken deployment (no crashpad executable in the correct location), calling other Sentry APIs on other threads will block forever, because they try to acquire mutexes which are in-use.

**When does the problem happen**

- [ ] During build
- [X ] During run-time
- [ ] When capturing a hard crash

**Environment**

Observed on Windows and macOS (pthread)

**Steps To Reproduce**

1) run with a missing / non-executable crashpad
2) call an API, eg `sentry_add_breadcrumb`, from a secondary thread
 -> the thread blocks indefinitely on `sentry__options_getref`, trying to lock g_options_lock

I'm now correctly handling non-zero returns from `sentry_init`, but of course it would be ideal if other APIs did not block in this case, but rather just returned immediately.

**Comment by zakalawe** [comment]
Wow, fast response, thanks guys, you are awesome.

**Comment by Swatinem** [comment]
Are you okay using the git version for the time being? We are in the middle of some bigger changes and would rather hold of on releasing some incomplete things.

**Comment by zakalawe** [comment]
Yes, that's no problem at all.
