### ISSUE TITLE
sentry_set_tag doesn't work. Tags is absent in result event json

### ISSUE THREAD

**Issue by DrHomer** [getsentry/sentry-native#654]
**sentry_set_tag doesn't work. Tags is absent in result event json and not see in frontend**

- [ ] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [e.g. Windows 10, 64-bit]
- Compiler: [e.g. MSVC 19]
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=crashpad]

Which SDK and version?
sentry-native-0.4.13

How do you use Sentry?
Sentry SaaS (sentry.io) AND self-hosted/on-premise (current version (jan 2022), Sentry 21.7.0, accordingly)

**Steps To Reproduce**

1. added next code:
sentry_set_tag("remoteServer", "test server");
sentry_set_tag("machineUniqueId", "5d6ce5c7-3239-4d71-952a-ea8cc077bc49");

I thought tags will be seen in the description item in the frontend. 
But I see only "base tag" (osname, version ... ) and no tags 'remoteServer' and 'machineUniqueId' :(

### Actual Result

Attached file contain json description of event  (and it doesn't contain my tags)
[json.json.zip](https://github.com/getsentry/sentry-native/files/7860753/json.json.zip)

**Comment by Swatinem** [comment]
May I ask what backend are you using? And what is the ordering in which you configure sentry vs set those tags.
We clear the scope (on which tags are being saved) on `sentry_init`. So anything you set before calling that function will be lost.

**Comment by DrHomer** [comment]
Problem is solved.  I moved my code with 'sentry_set_tag' after the 'sentry_init'.

Thanks for fast feedback.
