### ISSUE TITLE
No line and file information in Qt breadcrumbs in release mode

### ISSUE THREAD

**Issue by MartinDelille** [getsentry/sentry-native#655]
**Description**

My [Qt](https://qt.io) application doesn't provide the file and line information in the breadcrumbs in release mode:

```
error
{
file: None, 
line: 0
}
```

When compiled in debug mode, file and line are filled correctly.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [x] When capturing a hard crash

**Environment**

- Sentry version: 0.4.13
- OS: MacOS 11.6.2
- Compiler: appleclang 13
- CMake version and config: 3.17.2, SENTRY_BACKEND=breakpad, SENTRY_INTEGRATION_QT=ON
- Qt version: 5.15.2

**Steps To Reproduce**

```cpp
int main(int argc,
         char *argv[]) {
	sentry_options_t *options = sentry_options_new();
	sentry_options_set_dsn(options, "https://xxx@yyy.ingest.sentry.io/zzz");
	sentry_options_set_debug(options, 1);

	sentry_init(options);
	qDebug() << "test qdebug" << PH_BUILD_TYPE;
	sentry_capture_event(sentry_value_new_message_event(
							 SENTRY_LEVEL_ERROR,
							 "logger",
							 "my message"));

	sentry_close();
	return 0;
}
```

**Comment by Swatinem** [comment]
The Qt integration internally uses `QMessageLogContext` here:
https://github.com/getsentry/sentry-native/blob/0e94e49f442b75da4cf4048e25d577cd581a7b09/src/integrations/sentry_integration_qt.cpp#L41-L44

The docs for that class state:

> By default, this information is recorded only in debug builds. You can overwrite this explicitly by defining QT_MESSAGELOGCONTEXT or QT_NO_MESSAGELOGCONTEXT.

https://doc.qt.io/qt-5/qmessagelogcontext.html#details

**Comment by MartinDelille** [comment]
Awesome! Thanks! 😻
