### ISSUE TITLE
Returns an error when compiling, error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by illyashenko** [getsentry/sentry-native#659]
Hello, I use in the project Vcpkg, install x64-windows-static. It's the static one that is needed. No static - work

Rebuild started...
1>------ Rebuild All started: Project: CppSentryTest, Configuration: Debug x64 ------
1>CppSentryTest.cpp
1>HSentry.cpp
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_value_new_message_event referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_options_new referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_dsn referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_environment referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_auto_session_tracking referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_symbolize_stacktraces referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_handler_path referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_init referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_close referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_capture_event referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>HSentry.obj : error LNK2019: unresolved external symbol __imp_sentry_start_session referenced in function "void __cdecl send_message(void)" (?send_message@@YAXXZ)
1>C:\Users\ad-illyashenko\source\repos\CppSentryTest\x64\Debug\CppSentryTest.exe : fatal error LNK1120: 11 unresolved externals
1>Done building project "CppSentryTest.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Mixaill** [comment]
I think `SENTRY_BUILD_STATIC` definition is missing. Please try to add it to the project defines

**Comment by illyashenko** [comment]
#define SENTRY_BUILD_STATIC 1
another mistake)

Rebuild started...
1>------ Rebuild All started: Project: CppSentryTest, Configuration: Debug x64 ------
1>CppSentryTest.cpp
1>HSentry.cpp
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpCrackUrl referenced in function sentry__winhttp_send_task
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpOpen referenced in function sentry__winhttp_transport_start
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpCloseHandle referenced in function sentry__winhttp_bgworker_state_free
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpConnect referenced in function sentry__winhttp_send_task
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpOpenRequest referenced in function sentry__winhttp_send_task
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpSendRequest referenced in function sentry__winhttp_send_task
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpReceiveResponse referenced in function sentry__winhttp_send_task
1>sentry.lib(sentry_transport_winhttp.c.obj) : error LNK2019: unresolved external symbol __imp_WinHttpQueryHeaders referenced in function sentry__winhttp_send_task
1>sentry.lib(sentry_unwinder_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp_StackWalk64 referenced in function sentry__unwind_stack_dbghelp
1>sentry.lib(sentry_unwinder_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp_SymFunctionTableAccess64 referenced in function sentry__unwind_stack_dbghelp
1>sentry.lib(sentry_unwinder_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp_SymGetModuleBase64 referenced in function sentry__unwind_stack_dbghelp
1>sentry.lib(sentry_os.c.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoSizeW referenced in function sentry__get_os_context
1>sentry.lib(sentry_os.c.obj) : error LNK2019: unresolved external symbol GetFileVersionInfoW referenced in function sentry__get_os_context
1>sentry.lib(sentry_os.c.obj) : error LNK2019: unresolved external symbol VerQueryValueW referenced in function sentry__get_os_context
1>sentry.lib(sentry_symbolizer_windows.c.obj) : error LNK2019: unresolved external symbol __imp_SymFromAddr referenced in function sentry__symbolize
1>sentry.lib(sentry_windows_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp_SymSetOptions referenced in function sentry__init_dbghelp
1>sentry.lib(sentry_windows_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp_SymGetOptions referenced in function sentry__init_dbghelp
1>sentry.lib(sentry_windows_dbghelp.c.obj) : error LNK2019: unresolved external symbol __imp_SymInitialize referenced in function sentry__init_dbghelp
1>C:\Users\ad-illyashenko\source\repos\CppSentryTest\x64\Debug\CppSentryTest.exe : fatal error LNK1120: 18 unresolved externals
1>Done building project "CppSentryTest.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Mixaill** [comment]
Please try to build with commit in #662

**Comment by Mixaill** [comment]
@illyashenko Is it fixed for you?
