### ISSUE TITLE
sentry_close() doesn't release memory

### ISSUE THREAD

**Issue by OleksandrDorosh** [getsentry/sentry-native#664]
**C++ code:** SENTRY_SDK_VERSION == "0.4.12"

    sentry_options_t *options = sentry_options_new();
    sentry_init(options);
    sentry_close();
    sentry_options_free(options); //optional

**Visual Studio detects:**
Detected memory leaks!
Dumping objects ->
{17087} normal block at 0x0000016C72A9A500, 48 bytes long.
 Data: <                > 00 00 00 00 CD CD CD CD FF FF FF FF FF FF FF FF 
Object dump complete.

**Comment by Swatinem** [comment]
Your `sentry_options_free(options)` is actually a double-free. We are supposed to clean up after ourselves without any problem.

Can you provide a bit more context? Such as a stack trace of the allocation site?

We had another leak report a month ago: https://github.com/getsentry/sentry-native/issues/609 though even with the stack trace in the report, it was not entirely obvious why the leak happened or if the report is even valid.

**Comment by OleksandrDorosh** [comment]
Ok after further investigation I found issue not in your code but rather
in crashpad. But it reproducible with help of your library...

**My code:**
    MyApplication() {
        _CrtSetBreakAlloc(423);
        sentry_options_t *options = sentry_options_new();
        sentry_init(options);
        sentry_close();
        quit();
    }

**Stack:**
MyApp.exe!operator new(unsigned __int64 size) Line 35	C++
MyApp.exe!crashpad::`anonymous namespace'::CommonInProcessInitialization() Line 574	C++
MyApp.exe!crashpad::CrashpadClient::StartHandler(const base::FilePath & handler, const base::FilePath & database, const base::FilePath & metrics_dir, const std::string & url, const std::map<std::string,std::string,std::less<std::string>,std::allocator<std::pair<std::string const ,std::string>>> & annotations, const std::vector<std::string,std::allocator<std::string>> & arguments, bool restartable, bool asynchronous_start, const std::vector<base::FilePath,std::allocator<base::FilePath>> & attachments) Line 640	C++
MyApp.exe!sentry__crashpad_backend_startup(sentry_backend_s * backend, const sentry_options_s * options) Line 260	C++
MyApp.exe!sentry_init(sentry_options_s * options) Line 155	C
MyApp.exe!MyApplication::MyApplication() Line 13	C++
MyApp.exe!juce_CreateApplication() Line 52	C++
MyApp.exe!juce::JUCEApplicationBase::main() Line 253	C++
MyApp.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 52	C++
MyApp.exe!invoke_main() Line 107	C++
MyApp.exe!__scrt_common_main_seh() Line 288	C++
MyApp.exe!__scrt_common_main() Line 331	C++
MyApp.exe!WinMainCRTStartup(void * __formal) Line 17	C++

**Memory leak itself:**
void CommonInProcessInitialization() {
  g_non_crash_dump_lock = new base::Lock();
}

_// Guards multiple simultaneous calls to DumpWithoutCrash(). This is leaked._
base::Lock* g_non_crash_dump_lock;

So not sure is it bug at all. But strange to see it in VisualStudio output.

**Comment by Swatinem** [comment]
@OleksandrDorosh Thank you for the suggested patch. I fixed that in our crashpad fork, and will soon publish a new release.
