### ISSUE TITLE
Query: Difference between inproc, breakpad, crashpad?

### ISSUE THREAD

**Issue by agauniyal** [getsentry/sentry-native#672]
Apart from platform availability, which is not really an issue on let's say Linux where all 3 are available. What is the main difference between these 3?
One of the reasons I'm aware of is crashpad doesn't support custom transport and still uses its own transport. Any other differences besides this?

**Comment by Mixaill** [comment]
- `crashpad` launches separate process
- `breakpad` and `inproc` works within the same process with your application
