### ISSUE TITLE
Cannot use sentry.lib on windows

### ISSUE THREAD

**Issue by agauniyal** [getsentry/sentry-native#673]
I've tried numerous ways to use sentry.lib(static library) on windows and everytime it fails while linking the library and giving following errors -
```
main.obj : error LNK2019: unresolved external symbol __imp_sentry_options_new referenced in function main
main.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_dsn referenced in function main
main.obj : error LNK2019: unresolved external symbol __imp_sentry_options_set_symbolize_stacktraces referenced in function main
main.obj : error LNK2019: unresolved external symbol __imp_sentry_init referenced in function main
main.obj : error LNK2019: unresolved external symbol __imp_sentry_close referenced in function main
debug\sentry_test_win.exe : fatal error LNK1120: 5 unresolved externals
```

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 11, 64-bit
- Compiler: VS2019, 22
- CMake version and config: 3.22.2
- SENTRY_BACKEND=inproc

**Steps To Reproduce**
```cpp
#include "sentry.h"
int main()
{
    sentry_options_t* options = sentry_options_new();
    sentry_options_set_dsn(options,"REDACTED");
    sentry_options_set_symbolize_stacktraces(options, true);
    sentry_init(options);
    sentry_close();
}
```

This is how I'm building library(for example release configuration with vs2019, otherwise I've tried debug. vs2022 etc as well) -
```
cmake -B build -DCMAKE_BUILD_TYPE=Release -D SENTRY_BUILD_SHARED_LIBS=OFF -G "Visual Studio 16 2019" -A x64
cmake --build build --parallel --config Release
cmake --install build --prefix install --config Release
```
and then copying the generated .h and .lib files, including them inside visual studio(also modifying includepaths, linker paths).
I've also tried using qtcreator and including them like -
```
SOURCES += \
        main.cpp

LIBS += -L$$PWD/inproc/ -lsentry

INCLUDEPATH += $$PWD/inproc
DEPENDPATH += $$PWD/inproc
```

And each time the linker throws error.

**Comment by agauniyal** [comment]
Overall I've tried combinations of following -
1. Visual Studio 2019, 2022 passed into CMake
2. Visual Studio IDE, Qt Creator IDE
3. Debug, Release
4. inproc, breakpad
5. static, dynamic libraries

It runs fine on linux(and I've more of background with linux), but on windows I can't make it work.

**Comment by Swatinem** [comment]
The README says this:
https://github.com/getsentry/sentry-native#compile-time-options

> When using `sentry` as a static library, make sure to `#define SENTRY_BUILD_STATIC 1` before including the sentry header.

Can you try that? It seems missing in the above example.

**Comment by Mixaill** [comment]
Looks like the duplicate of #659

**Comment by agauniyal** [comment]
I needed both `#define SENTRY_BUILD_STATIC 1` and following libraries on windows - `-lwinhttp -lversion -lDbghelp -lAdvapi32`, then it worked perfectly fine. I wasn't using `CMake`, but `qmake` instead so that might be the reason for the requirements of those libraries explicitly.
