### ISSUE TITLE
Inconsistent allocator usage causing crashes

### ISSUE THREAD

**Issue by p0358** [getsentry/sentry-native#687]
**Description**

There's `sentry_malloc` and `sentry_free` functions. It is expected that they're the only ones used for memory allocation and free operations.
However, for example in this code: https://github.com/getsentry/sentry-native/blob/757a7b8aae5c6a01d1c8bf4d59e835c4aa062c82/src/backends/sentry_backend_crashpad.cpp#L85-L92
the usage is inconsistent. When `sentry_value_to_msgpack` is called, it calls `mpack_writer_init_growable`, that uses `MPACK_MALLOC`, which is defined as: https://github.com/getsentry/sentry-native/blob/757a7b8aae5c6a01d1c8bf4d59e835c4aa062c82/vendor/mpack.h#L204-L206

So the pointer is allocated with `MPACK_MALLOC` aka `malloc`, but getting freed with `sentry_free`.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [e.g. Windows 10, 64-bit] Windows 10, 64-bit
- Compiler: [e.g. MSVC 19] MSVC 19.31.31104.0
- CMake version and config: 3.22.22022201-MSVC_2, -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=OFF -DSENTRY_LIBRARY_TYPE=STATIC
-- SENTRY_TRANSPORT=winhttp
-- SENTRY_BACKEND=crashpad
-- SENTRY_LIBRARY_TYPE=SHARED

**Steps To Reproduce**

See https://github.com/getsentry/sentry-native/issues/606#issuecomment-967181401
What I did was commenting out these functions and then implementing them in a different library, that in turn getting successfully linked.
But on runtime, when sentry_free is called in https://github.com/getsentry/sentry-native/blob/757a7b8aae5c6a01d1c8bf4d59e835c4aa062c82/src/backends/sentry_backend_crashpad.cpp#L92 with a custom free function on a pointer it doesn't recognize, it fails.
I cannot paste the exact code, as the allocator is specific to the game engine and I'm not sure if the behavior would be the same with all allocators.

**Proposed fix**

It seems that replacing these macros with sentry_ functions does fix my crash.
Inserting the changes above the only import of `vendor/mpack.h` I could find did not help, so I simply just did those somewhere at the top of my `vendor/mpack.h`:
```cpp
#define MPACK_MALLOC sentry_malloc
#define MPACK_REALLOC sentry_realloc
#define MPACK_FREE sentry_free
```
Note that `sentry_realloc` didn't exist and I created it in my copy as well.
But creating `sentry_realloc` and defining `MPACK_REALLOC` *isn't really* needed, since the mpack header will just create its own realloc if it's missing, so you could do just fine skipping that one.

**Comment by Swatinem** [comment]
Thanks for reaching out, I think using the defines to redirect to our own malloc/free is a good idea indeed.
