### ISSUE TITLE
Compile the lib for Android with Qt support end with error

### ISSUE THREAD

**Issue by fro0m** [getsentry/sentry-native#695]
# How to reproduce;
```
cmake     -B build     -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake     -DANDROID_ABI=armeabi-v7a     -DANDROID_PLATFORM=android-27     -D SENTRY_BACKEND=none     -D CMAKE_PREFIX_PATH=/home/kotr/dev/tools/Qt/5.15.2/android/lib/cmake/Qt5/     -D SENTRY_INTEGRATION_QT=YES     --config RelWithDebInfo     -S .
```
it is fine

go for build:
`cmake --build build --config RelWithDebInfo --parallel`

It unds up with error: 
![image](https://user-images.githubusercontent.com/3215404/162623112-66cf639e-6f0c-4e5a-a5ff-9723def2c7b4.png)

p.s. specifying diffenrent `-DANDROID_ABI=armeabi-v7a` parameter does not make any effect

Environment;
lib version 0.4.15
OS Kubuntu linux 21.10 x64
cmake 18
Qt 5.15.2

**Comment by loewenheim** [comment]
Can you try disabling integration tests when building?

**Comment by fro0m** [comment]
@loewenheim 
![image](https://user-images.githubusercontent.com/3215404/163544890-baa0e6b0-a859-402a-8548-00c3c9abc219.png)

**Comment by Swatinem** [comment]
As the linker is complaining about `libQt5Core` not having the right format; which format does it have?
Is it a valid elf file? If so, does it have the same elf architecture, etc?

As you are trying to link to a pre-built qt library, it would be good to double-check that it is indeed matching up.

**Comment by Swatinem** [comment]
That looks good so far. How about the build artifacts in the sentry build directory?

C is known to be a pain to cross-compile (on top of CMake itself being a huge pain), and we have limited resources to support the infinite amount of build configurations and setups that people want to use :-(
