### ISSUE TITLE
Prevent sentry_init() initialize breakpad

### ISSUE THREAD

**Issue by Kostiantyn-Zakharchuk-GlobalLogic** [getsentry/sentry-native#705]
Description
sentry_init() function calls 'sentry__breakpad_backend_startup' and  I want to call sentry_init with some options if user need breakpad or not.

When does the problem happen
I've built sentry library with breakpad backend but breakpad is always turned on. 

- [ ] During build
- [ X] During run-time
- [ X] When capturing a hard crash

Environment
- OS: [Linux, armv7a]
- Compiler: [armv7a-cros-linux-gnueabihf]
- CMake version and config: [3.18.0, SENTRY_BUILD_TESTS=OFF, SENTRY_BUILD_EXAMPLES=OFF, SENTRY_TRANSPORT="curl", SENTRY_BACKEND="breakpad", SENTRY_EXPORT_SYMBOLS=OFF, CMAKE_BUILD_TYPE=MinSizeRel, SENTRY_LIBRARY_TYPE=SHARED

Steps To Reproduce
To reproduce: just call sentry_init() function

Bug reason: I have two binaries which use sentry-native library. For the first binary 'crash-uploader' app is installed and It catches crashes. For the second app I've used breakpad. But breakpad backend is overlapped my 'crash-uploader' app.
How I've used it: for now I've added include to my project 'sentry_options.h' and sent options->backend = nullptr. Actually It works and I have one app which runs alongside 'crash_uploader' and another with prebuild breakpad.

**Comment by Kostiantyn-Zakharchuk-GlobalLogic** [comment]
Yes, for now this variant works fine but I can't say what will be in the future with this fix. It's tricky solution. For using sentry I should to include only 'sentry.h' but I added also 'sentry_options.h'(prevent c style encapsulation).

**Comment by sandraiser** [comment]
use case is as follow:
3 apps
Sentry lib compiled with breakpad
app A owned by us - Sentry native
app B co-owned by us _and_ third party , Sentry native+crash_uploader
app C owned by third party , crash_uploader only
third party has crash_uploader that detect crash in app B and C, generate minidump and uploads to their system via shell script that we piggy back on.
we upload minidumps for app A via Sentry native
app C via shell script inserted code with curl uploading to minidump endpoint
problem with app B : Sentry (shared lib with app A) intercept crashes and crash_uploader never runs.
If breakpad in not compiled then app A will not produce minidumps.

**Comment by Swatinem** [comment]
Oh, so you would like app B to upload things via the third party crash reporter *and* to hook into that shell script to upload to sentry as well?

**Comment by Kostiantyn-Zakharchuk-GlobalLogic** [comment]
I would like to call crash reporter only in app B. But while breakpad is auto enabled in sentry, It's impossible. Breakpad is overlap third party crash reporter
