### ISSUE TITLE
Feature Request: Allow to add message event or some kind of key-value while uploading crashes

### ISSUE THREAD

**Issue by kaptaanalt** [getsentry/sentry-native#711]
**Description**

This is more of a feature request or a query - I want to be able to add a message or key-value pair or any kind of information while uploading crash reports. I know there's already an option for [Capturing Message](https://docs.sentry.io/platforms/native/usage/#capturing-messages) but this happens immediately or before the crash has happened.

I'll try to explain my scenario -
1. User is interacting with application and it crashes. Since sentry sdk was initialized properly, it'll record crash in `.sentry-native` directory for the next time application starts.
2. User starts the application again, sentry code initializes.
3. `sentry_init()` gets called and it checks for previous crashes in `.sentry-native` which it finds and beings upload procedure.
4. I set `sentry_transport_new()` to use my own transport and call `sentry_envelope_serialize()`.
5. It returns a newline separated json objects like - `{eventid: ...}\n{size: ...}\n{eventid:..., ...., ...}` which then I upload to sentry api.

**I want to be able to add some message in my transport handler, before sending, because I have extra context about the crash which sentry didn't capture.**

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [x] When capturing a hard crash

**Comment by supervacuus** [comment]
Closing as transferred to support. Feel free to reopen at any time.
