### ISSUE TITLE
Feature request:  Provide extra context to custom logger

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/sentry-native#712]
**Description**

Feature request

It would be useful for the custom logger to know if it is being called during a crash handling call.
The reason is that in this case, it may decide to send logs directly to stderr, rather than use whatever custom
log pipeline it was using previously.  During crash handling, the "standard" log pipeline may be well defunct.

We don't want to duplicate all logs during init and regular phase (sending it to custom log pipe _and_ stderr).

During crash handling, progress is logged using INFO level, so the level also cannot be used to decide when to send logs
to stderr, rather than custom log pipe.

This could be done by providing a `sentry_get_status()` api, or by providing additional args to logging.  Possibly passing a flag along with
the level.

**When does the problem happen**

- [ ] During build
- [ ] During run-time
- [x] When capturing a hard crash

**Comment by Kobby-Bawuah** [comment]
Hey @kristjanvalur, please send this request to support@getsentry.com. The support team will go ahead and create a feature request if appropriate.

**Comment by kristjanvalur** [comment]
That seems a bit roundabout, but okay, I guess.

**Comment by supervacuus** [comment]
Closing as transferred to support. Feel free to reopen at any time.
