### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by z787804918** [getsentry/sentry-native#722]
root@ubuntu204:/clickhouse/sentry-native/sentry-native-0.4.17/build# cmake ..
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=breakpad
-- SENTRY_LIBRARY_TYPE=SHARED
-- SENTRY_SDK_NAME=
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
root@ubuntu204:/clickhouse/sentry-native/sentry-native-0.4.17/build# ls
root@ubuntu204:/clickhouse/sentry-native/sentry-native-0.4.17/build# cmake .. -DBUILD_SHARED_LIBS=OFF
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=breakpad
-- SENTRY_LIBRARY_TYPE=STATIC
-- SENTRY_SDK_NAME=
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Found CURL: /usr/lib/powerpc64le-linux-gnu/libcurl.so (found version "7.68.0")  
-- Looking for getcontext
-- Looking for getcontext - found
-- Configuring done
CMake Error at external/CMakeLists.txt:119 (add_library):
  Cannot find source file:

    breakpad/src/common/convert_UTF.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at external/CMakeLists.txt:119 (add_library):
  No SOURCES given to target: breakpad_client

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by supervacuus** [comment]
The default backend on Linux is Breakpad which you can see selected in your CMake configuration log:

```-- SENTRY_BACKEND=breakpad```

The compilation fails because you also need to download the Breakpad source as a git submodule. You can use

```make setup```

as a convenience script that initializes all submodules.

**Comment by jan-auer** [comment]
If you download the release bundle `sentry-native.zip` from our Releases page rather than the sources, all submodules will already be resolved for you: https://github.com/getsentry/sentry-native/releases/tag/0.4.17
