### ISSUE TITLE
Windows:  attachments don't show up with unhandled exceptions

### ISSUE THREAD

**Issue by wpreder** [getsentry/sentry-native#731]
**Description**

Attachments do not show up in the portal for unhandled exception events (e.g. divide-by-zero).
They show up fine for the "it works!" test event.

**When does the problem happen**

- [ ] During build
- [ ] During run-time
- [x ] When capturing a hard crash

**Environment**

- sentry.native SDK 0.4.18 with latest Crashpad backend
- OS: Windows 11 (10.0.22000(739))
- Compiler: MSVC 19 (Visual Studio 2019 16.11.10)
- cmake 3.18.6
- Intel NUC NUC8i7BEH

**Steps To Reproduce**

- create a crash test function, e.g.
  `void my_crash_test() {`
`	volatile int x = 0, y = 1, z;`
`	z = y / x;`
`}`
- initialize sentry
- add an attachment, e.g. `sentry_options_add_attachment(my_options, "<path_to_some_file>");`
- call my_crash_test()

Result:  unhandled exception event appears in portal, but without attachments

**Comment by Swatinem** [comment]
The ordering is wrong here. As you add attachments to the `sentry_options`, and "move" those into `sentry_init`, the attachments are frozen at init time. "In theory", adding them after init would still work in some cases, though not when using the Crashpad backend.

So just move `add_attachment` to before `sentry_init` and things should work.

**Comment by wpreder** [comment]
Well, it seems attachments are now magically showing up.  I'm not sure what jostled it into place.  Could it have been related to not having a valid user ID (#730)?  Anyway, it's working now.  Closing.
