### ISSUE TITLE
Crash still getting reported after calling sentry_close()

### ISSUE THREAD

**Issue by sandormatyi** [getsentry/sentry-native#736]
**Description**

I have an application that I sometimes want to manually crash without the crash getting reported. I am calling `sentry_close()` before the crash happens but the crash still ends up getting processed and reported.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [x] When capturing a hard crash

**Environment**

- OS: Windows 10, 64-bit
- Compiler: MSVC 19
- CMake version and config: 3.22,0 SENTRY_BACKEND=crashpad

**Steps To Reproduce**

```
// ...initialize Sentry

sentry_close();
*((int*)(nullptr)) = 1;
```

**Log output**

**Comment by sandormatyi** [comment]
The documentation is not clear about `sentry_close()` being synchronous or asynchronous, so I'm assuming the former. Do I have to wait some amount of time after calling `sentry_close()`?

**Comment by ReneGreen27** [comment]
Bump @getsentry/owners-native

**Comment by Swatinem** [comment]
You mention that you are using the crashpad backend on Windows.
On that configuration, it is unfortunately not possible to de-register the crash handler. All other backends seem to handle that correctly though.

**Comment by sandormatyi** [comment]
@Swatinem Do you have a workaround in mind that you could recommend? Would revoking user consent prevent the crash from being processed by Sentry?

**Comment by Swatinem** [comment]
I believe it will, though not 100% certain.

**Comment by sandormatyi** [comment]
@Swatinem Unfortunately, `sentry_user_consent_revoke()` doesn't work either. The crashes after revoking user consent are still sent to the Sentry server. This doesn't sound right to me. Is this the expected behaviour? Am I missing something here?

**Comment by Swatinem** [comment]
That is a good point, we will have to investigate. In the meanwhile using a different backend is a good workaround.
