### ISSUE TITLE
No gen_* folder in version 0.1.1 and 0.1.2

### ISSUE THREAD

**Issue by alam-vudu** [getsentry/sentry-native#74]
Versions 0.1.1 and 0.1.2 does not contain any gen_* folder. I want to run test trial for Windows native application. Please let us know how these files can be generated.

**Comment by jan-auer** [comment]
The release archive of version 0.1.2 contains those gen folders. You can download it on the releases page, here is a direct link: [sentry-native-0.1.2.zip](https://github.com/getsentry/sentry-native/releases/download/0.1.2/sentry-native-0.1.2.zip)

You can also generate a VS solution manually from our premake files by following the instructions [here](https://github.com/getsentry/sentry-native/tree/0.1.2#development-setup).

**Comment by alam-vudu** [comment]
Thank you!. I think I messed up between package and source code, as both have same folder name.

**Comment by alam-vudu** [comment]
@jan-auer I am trying to integrate sentry_native in my local test application. When I define `SENTRY_WITH_CRASHPAD_BACKEND` in sentry project I am getting `1>c:\projects\liquidsky\liquidskystream2\sentry-native\src\backends\crashpad_backend.cpp(17): fatal error C1083: Cannot open include file: 'client/crash_report_database.h': No such file or directory
` I am using VS2017
