### ISSUE TITLE
How to limit the queued event to send

### ISSUE THREAD

**Issue by xamix** [getsentry/sentry-native#748]
Hi,

I'm on an application on which I want to limit the queued event awaiting to be sent.

Since a lot of issue/event are queued when the system goes wrong, a lot of event are waiting to be sent and it takes more and more memory....
I know that I can use the sampling and other settings to limit repetition also on specific event but that's not what I want.

Is there a solution to limit the queue of event waiting to be sent and drop if limit is reached?
I see that there is a *before_send* callback but I don't know if it is usable by having a global counter to count the posted event and decrement it on the *before_send* to have the queued amount of event?

Regards

**Comment by Swatinem** [comment]
There is no built in mechanism to do this. I think the best thing to do would be to implement your own transport that has better queue handling.

**Comment by supervacuus** [comment]
@ashwoods, since this is assigned to you: I think this will be a while before anyone will be working on this. Is there another reason not to close this? Is there a sensible follow-up to the suggestion that @Swatinem has provided?

**Comment by ashwoods** [comment]
@supervacuus agreed.
