### ISSUE TITLE
How to compile the win32 version

### ISSUE THREAD

**Issue by kc991229** [getsentry/sentry-native#750]
thanks

**Comment by supervacuus** [comment]
Where does the [documentation](https://docs.sentry.io/platforms/native/#install) fail you with your win32 build? There is a complete build steps description for Windows in the lower shell view. If you have problems with those steps, please post the error messages here.

**Comment by supervacuus** [comment]
I hope the documentation was helpful. Feel free to reopen the issue if you have further questions or just open a new one.
