### ISSUE TITLE
crashpad-handler starts when hosting native application is invoked directly, but not when the app package is started (on macOS)

### ISSUE THREAD

**Issue by IliasBergstrom** [getsentry/sentry-native#753]
**Description**

Hi!

We are evaluating using sentry for our native C++ macOS application, and have this far had a great experience with integration and reporting.

However I am at my wits end with crashpad-handler!

For the exact same package, i.e. the very same files:

* If in finder, I go into “OurDesktopApp/Contents/MacOS” and there invoke “OurDesktopApp” executable, the crashpad-handler instance appears in macOS's Activity Monitor.
* If I double click the "OutDesktopApp" package in finder, it runs, but I see no crashpad-handlers in Activity Monitor.

To rule out that the path to the crashpad-handler executable is the issue, I construct the path relative to the executable, so it’s not relative to the working directory. In our log files written to /tmp the path I've printed is correct in both cases.

See also code example, where (using the juce C++ library) I check the file I link to exists.

I've spent a while with Console.app's logs to see if I can get anything relevant there, but searching for "crashpad-handler" gives nothing.

Is macOS intervening somehow, and hindering crashpad-handler from starting?

I'd be grateful if you have some input/experience on this!

I'm not SURE it's a bug, but the Sentry discourse forum redirects here...

**When does the problem happen**

- [ ] During build
- [X] During run-time
- [ ] When capturing a hard crash

**Environment**

Our C++ app uses the latest 0.5.0 SDK fetched from vcpkg ("sentry-native"), and I am running on MacOS 12.5.1, on an M1 Pro.
cmake version 3.23.2

**Steps To Reproduce**

See the description, it also contains the steps. Meanwhile this is the code:

```
constexpr char const* CRASHPAD_HANDLER_PATH_FROM_PACKAGE_ROOT =
    "/Contents/Applications/crashpad_handler";

 juce::File pathToDesktopAppExecutable =
        juce::File::getSpecialLocation (juce::File::currentExecutableFile);

    auto packageRootPath = pathToDesktopAppExecutable.getParentDirectory()
                               .getParentDirectory()
                               .getParentDirectory()
                               .getFullPathName();

    juce::File crashpadHandlerFile (packageRootPath + CRASHPAD_HANDLER_PATH_FROM_PACKAGE_ROOT);

    bool crashpadHandlerExists = crashpadHandlerFile.existsAsFile();

    jassert (crashpadHandlerExists);

    juce::String existsString ("Desktop app crashpad-handler path is correct: ");
    existsString.append (crashpadHandlerExists ? "Yes" : "No", 5);

    auto sentry_options = sentry_options_new();
    sentry_options_set_dsn (sentry_options, OUR_SENTRY_DSN);
    sentry_options_set_handler_path (sentry_options, crashpadHandlerAbsolutePath.toRawUTF8());
    sentry_init (sentry_options);

# I also write the existsString and path to the handler into a log file which under both working and non-working conditions are identical, but I left that code out here.

The log contains, both cases, this ('ve edited the path to make it general):
/Users/user/repos/repo/cmake-build-debug-ninja/OurDesktopApp_artefacts/Debug/Our Desktop.app/Contents/Applications/crashpad_handler

Desktop app crashpad-handler path is correct: Yes


```

**Comment by IliasBergstrom** [comment]
When it succeeds, sentry_init returns 0. When I don't see crashpad-handlers starting, it returns '1', but I am not able to find what that '1' means, other than failure of some sort?

**Comment by Swatinem** [comment]
Yes, it is pretty much "failure of some sort". You can enable debug logging and it should tell you what went wrong.

**Comment by IliasBergstrom** [comment]
Thanks! I just stepped through the init function while debugging after attaching to the process when it's first been manually started as an app bundle.

I still think this is a bug, and should file it, just differently than what I have done now:

The default 'database_path' value is next to the executable - but the program has no write access if it is run as an app bundle on mac os, meaning Sentry fails to initialise.

This is surely solved by setting the database_path to a folder where Sentry CAN write, but the default should already be such a path.

Everyone making a macOS app using sentry native will have this problem, and all examples leave setting database_path out so it is a very easy mistake to make when starting out.
And difficult to debug, since the README doesn't mention debug logging, one has to look at the CMake to see that it's available to enable...

**Comment by IliasBergstrom** [comment]
I've reported it here https://github.com/getsentry/sentry-native/issues/754 and will close this issue.
