### ISSUE TITLE
database_path default value is .sentry-native next to executable - this will fail when deploying on macOS/Win/most linux. Either set the default to an appropriate path per platform, os judiciously signpost this needs changing in all examples.

### ISSUE THREAD

**Issue by IliasBergstrom** [getsentry/sentry-native#754]
**Description**

The database_path default value is .sentry-native next to executable - this will fail when deploying on macOS/Win/most linux. Either set the default to an appropriate path per platform, os judiciously signpost this needs changing in all examples.

**When does the problem happen**

- [ ] During build
- [X] During run-time
- [ ] When capturing a hard crash

**Environment**

mac OS, when running an executable inside an app bundle, it will never have write access in the app bundles folder, and will fail.

**Steps To Reproduce**

Try to run an app bundle with a native app that runs sentry using the default example init code  on mac OS - sentry will fail to start as it lacks write access.

So, the example code, from your docs here https://docs.sentry.io/platforms/native/:

`  sentry_options_t *options = sentry_options_new();
  sentry_options_set_dsn(options, "https://examplePublicKey@o0.ingest.sentry.io/0");
  sentry_options_set_release(options, "my-project-name@2.3.12");
  sentry_init(options);`

....Will fail when deployed on virtually all platforms.

I think you can make sentry use a sensible default on mac OS / Linux ( /tmp/.sentry-native ? ), probably also on windows.

If you don't, your examples should clearly communicate this path needs setting.

**Comment by Swatinem** [comment]
I think this can be solved with some improvements to docs.
This is being called out in the repo README here: https://github.com/getsentry/sentry-native#runtime-configuration
Though admittedly, it is missing from the sentry docs website.

**Comment by supervacuus** [comment]
> Though admittedly, it is missing from the sentry docs website.

It is also contained in the docs, but only in the [crashpad configuration](https://docs.sentry.io/platforms/native/configuration/backends/crashpad/). It should at least find its way into the [Common Options](https://docs.sentry.io/platforms/native/configuration/options/#common-options).

**Comment by supervacuus** [comment]
All "getting started" code samples now provide an explicit `database_path` initialization referencing the documentation in the [Common Options](https://docs.sentry.io/platforms/native/configuration/options/#database-path).
