### ISSUE TITLE
Crashes in sentry_transaction_start()

### ISSUE THREAD

**Issue by parsley72** [getsentry/sentry-native#756]
**Description**

I've added a simple use of sentry_transaction_start() and it sometimes crashes. I've seen two so far:

https://sentry.io/organizations/teknique-limited/issues/3627244287/
myapp +0x1eac60 sentry_value_get_by_key (sentry_value.c:690)
myapp +0x1e0df4 sentry_transaction_start (sentry_core.c:744)

https://sentry.io/organizations/teknique-limited/issues/3627258751/
libc.so.6 +0x06eca0 __libc_message (libc_fatal.c:155)
libc.so.6 +0x076228 malloc_printerr (malloc.c:5347)
libc.so.6 +0x077a44 _int_free (malloc.c:4177)
myapp +0x1e0ea4 sentry_transaction_start (sentry_core.c:765)

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: ARM Linux
- Compiler: gcc
- CMake version and config:

**Steps To Reproduce**

    sentry_transaction_context_t* tx_ctx = sentry_transaction_context_new("MyName", "MyOperation");
    sentry_transaction_t* tx = sentry_transaction_start(tx_ctx, sentry_value_new_null());
    // do the thing
    sentry_transaction_finish(tx);

**Comment by Swatinem** [comment]
The first one crashes in `thing_get_type(thing)` which dereferences an internal heap allocation associated with an internal `sentry_value_t`.

The second one crashes in `sentry__transaction_context_free(opaque_tx_cxt)` which frees the `sentry_value_t` and the wrapping transaction context.

This looks like a double-free maybe. Are you seeing problems with exactly the minimal repro you posted or is some other code involved there?

**Comment by parsley72** [comment]
The actual code is slightly more complicated but not much:
```
   sentry_transaction_context_t* tx_ctx = nullptr;
    if (_local_settings->return_bool_value(oclea::SENTRY_PERFORMANCE, false)) {
        tx_ctx = sentry_transaction_context_new("MyName", "MyOperation");
    }

    // block any other token access while renewing access token
    unique_lock<std::shared_timed_mutex> w(_token_m);

    CurlRequest request(base_url + "/GetToken", api_key);
    request.Debug(debug);

    sentry_transaction_t* tx = nullptr;
    if (nullptr != tx_ctx) {
        tx = sentry_transaction_start(tx_ctx, sentry_value_new_null());
    }
    const CURLcode curl_code = request.Execute();
    if (nullptr != tx) {
        sentry_transaction_finish(tx);
    }

```

**Comment by parsley72** [comment]
Sorry, my mistake - working fine now.
