### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by facontidavide** [getsentry/sentry-native#782]
**Description**

Sentry native client doesn't work in my Qt application.

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [x] When capturing a hard crash

**Environment**

- Version of sentry-native: 0.5.0, provided by conan (https://conan.io/center/sentry-native)
- OS:Ubuntu 20.04, 
- Compiler: GCC 9.4.0
- Qt version 6.4
- CMake version and config:  3.21.3, SENTRY_BACKEND=crashpad SENTRY_INTEGRATION_QT=YES

**Log output**

[sentry] DEBUG executing task on worker thread
* STATE: INIT => CONNECT handle 0x556973ab57f8; line 1789 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => RESOLVING handle 0x556973ab57f8; line 1835 (connection #0)
* family0 == v4, family1 == v6
*   Trying 34.120.195.249:443...
* STATE: RESOLVING => CONNECTING handle 0x556973ab57f8; line 1917 (connection #0)
* Connected to o4504077504872448.ingest.sentry.io (34.120.195.249) port 443 (#0)
* STATE: CONNECTING => PROTOCONNECT handle 0x556973ab57f8; line 1980 (connection #0)
* ALPN, offering http/1.1
* Didn't find Session ID in cache for host HTTPS://o4504077504872448.ingest.sentry.io:443
* STATE: PROTOCONNECT => PROTOCONNECTING handle 0x556973ab57f8; line 2000 (connection #0)
* SSL certificate problem: unable to get local issuer certificate
* multi_done
* The cache now contains 0 members
* Closing connection 0
* Expire cleared (transfer 0x556973ab57f8)
[sentry] WARN sending via `curl_easy_perform` failed with code `60`

**Comment by supervacuus** [comment]
Hi @facontidavide, this sounds like an outdated CA certificate chain in the trust store of the affected system. It says it cannot find the "local issuer certificate" which in the case of `o4504077504872448.ingest.sentry.io` is "Let's encrypt" (and its [ISRG Root X1](https://letsencrypt.org/certificates/)). You must update your trust store on the system for `libcurl` to connect with our ingest endpoint.

**Comment by facontidavide** [comment]
I will try. My concern is : if I use sentry in my distributed desktop app, will my user experience the same issue?

**Comment by supervacuus** [comment]
Feel free to re-open anytime when you have further questions.
