### ISSUE TITLE
conan recipe for sentry-native

### ISSUE THREAD

**Issue by tonka3000** [getsentry/sentry-native#79]
Hey @jan-auer ,

as discussed today here is an conan recipe for sentry-native https://github.com/tonka3000/conan-sentry_native .

It's not finished (see travis and appveyor), but I think you get the point 😄 

Greetings

**Comment by Swatinem** [comment]
I just had a very brief look at conan, and it sounds nice to have.

We just merged a big rewrite in C, and switching to CMake for builds. Feel free to open a PR for this, however I don’t think this will be a priority from our team anytime soon.

**Comment by Croydon** [comment]
If anyone wants to tackle this, I would recommend to directly contribute a Conan recipe to the central, official Conan recipe repository called Conan Center Index 😄 

https://github.com/conan-io/conan-center-index

**Comment by Swatinem** [comment]
> The recipe should be now easier because sentry native is now based on cmake.

BTW, I would very much appreciate feedback on the CMake parts, I have no idea if they are correct this way, or how they could be further improved.

> I will contribute it to the conan center index

If moving this to the index is the way to go, I will close this issue. Feel free to re-open.
