### ISSUE TITLE
thread name displayed as hex addresses in crashes with breakpad backend (but works with crashpad)

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-native#799]
**Description**

In the Sentry UI, when inspecting all the backtraces info in the UI, the thread names are not readable, instead we see *unknown*.

<img width="515" alt="Screenshot 2023-01-30 at 9 32 02 PM" src="https://user-images.githubusercontent.com/11857745/215674080-9208c916-d0fd-4734-9006-b7d70573a8d1.png">

**When does the problem happen**

- [ ] During build
- [ ] During run-time
- [ * ] When capturing a hard crash

**Environment**

- OS: Linux, Ubuntu 18.04
- Compiler: gcc-11
- CMake version and config: [e.g. 3.21.x, SENTRY_BACKEND=breakpad]

**Steps To Reproduce**

This seems to be a PR related to supporting thread names -> https://github.com/getsentry/symbolicator/pull/834
Maybe breakpad never supported this, but I thought it did in very recent versions.

**Comment by Swatinem** [comment]
> Maybe breakpad never supported this, but I thought it did in very recent versions.

My impression was also it never did, at least when we initially added this feature only crashpad supported it.

Maybe breakpad added that in the meantime. I believe on Windows breakpad just uses the upstream microsoft APIs, in which case it would support it, but not on other platforms. We can double-check for sure, and we are regularly updating the crashpad and breakpad code as well.

**Comment by supervacuus** [comment]
Breakpad has only added [support for thread names in the processor](https://chromium-review.googlesource.com/c/breakpad/breakpad/+/3690389) (which we don't use in the Native SDK). AFAIK, only the windows minidump generator in breakpad stores the thread names. If you want broad support for thread names in the snapshots, then crashpad has more to offer at this point.

**Comment by bsergean** [comment]
Thanks for the reply. 

Right now I’m avoiding crashpad as I’m not ready to tackle the environmental problems around ptrace (for us it appears to be a systemd thing).

If I have time I will try to catch a mini dump, and run the breakpad_stackwalk tool to see if they are able to display thread names.

**Comment by supervacuus** [comment]
I am closing this for now, since I don't think that we will be working on adding thread-names in breakpad anytime soon. Feel free to reopen if you think this should stay in the backlog.
