### ISSUE TITLE
support for 32 bit applications on Linux 64 bit

### ISSUE THREAD

**Issue by bkaimal** [getsentry/sentry-native#81]
Is sentry-native supported with 32 bit applications on Linux? I did not find instructions on building for sentry-native as a 32-bit binary in the documentation and hence posting here.

**Comment by mitsuhiko** [comment]
Should work in theory. I did not try but which issues are you running into?

**Comment by bkaimal** [comment]
The build currently builds only 64-bit binaries. We could try and build this for 32-bit, but it would be good to have this supported by the Sentry team.

**Comment by mitsuhiko** [comment]
It should build the native architecture on the machine by default. We're likely going to move all of the build system to cmake and we can revisit cross compiling there again.
