### ISSUE TITLE
Feature request: Add support for string length parameters

### ISSUE THREAD

**Issue by brad-anderson** [getsentry/sentry-native#819]
Tools like `std::string_view` are becoming increasingly common in the C++ world, but that presents issues when interacting with interfaces that expect traditional null terminated strings because `std::string_view` isn't guaranteed to be null terminated.

The workaround is to allocate a temporary new null terminated string (on the stack, preferably) for the call to Sentry functions, but it would be nice if this could be avoided entirely so the sentry-native can be interacted without this additional cost.

I hit this stumbling block while creating a breadcrumb sink for spdlog which uses std::string_view for its log messages. There is no safe way of knowing which messages are null terminated, meaning you have to allocate a temporary string for every log message.

**Comment by brad-anderson** [comment]
There are some security benefits from such an interface as well.

**Comment by supervacuus** [comment]
Interfaces with explicit-length arguments would be a valuable addition to the SDK. This is not only sensible for `std::string_view` or C++ code, but quite a few C codebases also quit null-terminated strings for various reasons. Needing to allocate to use the SDK in these cases is an unnecessary burden.

**Comment by Icantjuddle** [comment]
Just wanted to say thanks for doing this, had been an issue for me as well.

**Comment by brad-anderson** [comment]
I switched over to the new interface and it works great. Thanks for doing this (and much more quickly than I ever would have hoped when I created the issue).
