### ISSUE TITLE
Specify `instruction_addr_adjustment: "none"` when using Android libunwindstack

### ISSUE THREAD

**Issue by Swatinem** [getsentry/sentry-native#835]
We should put the `instruction_addr_adjustment` into stack traces according to https://github.com/getsentry/rfcs/blob/main/text/0043-instruction-addr-adjustment.md

It looks like the `libunwindstack` that we use for unwinding on Android already does its adjustment before handing us the PC values:

https://github.com/getsentry/libunwindstack-ndk/blob/90d80b7073ae2108f7f42e2f576bddf988069ba2/Unwinder.cpp#L97

We should thus use `"none"`, to avoid double-adjusting in the symbolication pipeline which could lead to wrong symbolication results.

**Comment by supervacuus** [comment]
Is the idea here (for now) to add this only for `libunwindstack` as a special case, or should we expose this cleanly in the API too?

For the former, I would do something simple like the following [here](https://github.com/getsentry/sentry-native/blob/e97930a2ea10f2db263c5fece6a5d548f67f5613/src/sentry_value.c#LL1264C1-L1264C1):
```C
#ifdef SENTRY_WITH_UNWINDER_LIBUNWINDSTACK
    // libunwindstack already adjusts the PC according to `GetPcAdjustment()`
    // https://github.com/getsentry/libunwindstack-ndk/blob/1929f7b601797fc8b2cac092d563b31d01d46a76/Regs.cpp#L187
    // so there is no need to adjust the PC in the backend processing.
    sentry_value_set_by_key(stacktrace, "instruction_addr_adjustment",
        sentry_value_new_string("none"));
#endif
```
