### ISSUE TITLE
Building sentry library with curl(with AsynchDNS feature) cause an error

### ISSUE THREAD

**Issue by Kostiantyn-Zakharchuk-GlobalLogic** [getsentry/sentry-native#838]
**Description**
I can't build sentry library with curl library with AsynchDNS feature

I've build curl library with AsynchDNS feature to use it in new sentry release 0.6.2. But it still cause issue for me.
![image](https://user-images.githubusercontent.com/93606690/236392065-59b641ce-6386-462a-80cc-b6b1789d39fe.png)

**When does the problem happen**
Problem happens when I try to build sentry library with curl library

- [x ] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [e.g. docker image ubuntu:20.04, 64-bit]
- Compiler: [e.g. own arm toolchain]
- CMake version and config: [
			-DCMAKE_TOOLCHAIN_FILE=<own_toolchain>
			-DSENTRY_BUILD_TESTS=OFF
			-DSENTRY_BUILD_EXAMPLES=OFF
			-DSENTRY_TRANSPORT="curl"
			-DSENTRY_BACKEND="breakpad"
			-DSENTRY_EXPORT_SYMBOLS=OFF
			-DCMAKE_BUILD_TYPE=MinSizeRel
			-DSENTRY_LIBRARY_TYPE=SHARED
			-DCURL_INCLUDE_DIR="<path>"
			-DCURL_LIBRARY="<path>"
]

**Steps To Reproduce**

Build curl:
cmake \
		-DCMAKE_INSTALL_PREFIX=<path> \
		-DCMAKE_TOOLCHAIN_FILE=<path> \
		-DCURL_USE_OPENSSL=OFF \
		-DENABLE_ARES=ON \
		-DCARES_LIBRARY=<path> \
		-DCARES_INCLUDE_DIR=<path>
Build sentry:
cmake \
	-DCMAKE_TOOLCHAIN_FILE=<path> \
	-DSENTRY_BUILD_TESTS=OFF \
	-DSENTRY_BUILD_EXAMPLES=OFF \
	-DSENTRY_TRANSPORT="curl" \
	-DSENTRY_BACKEND="breakpad" \
	-DSENTRY_EXPORT_SYMBOLS=OFF \
	-DCMAKE_BUILD_TYPE=MinSizeRel \
	-DSENTRY_LIBRARY_TYPE=SHARED \
	-DCURL_INCLUDE_DIR="<path>" \
	-DCURL_LIBRARY="<path>"

**Log output**

![image](https://user-images.githubusercontent.com/93606690/236393512-3a7a3140-7181-4f9f-936c-7e8eb75fd22f.png)

-- The C compiler identification is Clang 12.0.0
-- The CXX compiler identification is Clang 12.0.0
-- The ASM compiler identification is Clang
-- Found assembler: /self/sdk-meta/prebuilt/toolchain/bin/armv7a-cros-linux-gnueabihf-clang
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /self/sdk-meta/prebuilt/toolchain/bin/armv7a-cros-linux-gnueabihf-clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /self/sdk-meta/prebuilt/toolchain/bin/armv7a-cros-linux-gnueabihf-clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=breakpad
-- SENTRY_LIBRARY_TYPE=SHARED
-- SENTRY_SDK_NAME=
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
CMake Error at /cmake/share/cmake-3.20/Modules/FindCURL.cmake:175 (message):
  CURL: Required feature AsynchDNS is not found
Call Stack (most recent call first):
  CMakeLists.txt:277 (find_package)

-- Configuring incomplete, errors occurred!
See also "/self/build/sentry-native_build/CMakeFiles/CMakeOutput.log".
See also "/self/build/sentry-native_build/CMakeFiles/CMakeError.log".
make: *** [Makefile:130: build] Error 1

**Comment by supervacuus** [comment]
Hi @Kostiantyn-Zakharchuk-GlobalLogic. We're not doing anything fancy with the component specifier, the actual search is deferred to `FindCURL.cmake`, which would show this typically only if the found library does not have that feature enabled.

If I were in your position, I would double-check 

1. whether the files in the `curl` build-output have that feature enabled (to be sure that they are not only selected in the build configuration): `./your-build-path/curl --version` would reflect this as would `./your-build-path/libcurl.pc` and `./your-build-path/curl-config`, also,
1. make sure that either `CURL_INCLUDE_DIR` and `CURL_LIBRARY` or `CMAKE_PREFIX_PATH` (!!!) are correctly set up to find _your_ `curl` build, and
1. make sure that your `sentry-native` CMake configuration picks up the right `curl`. I would do this by removing the `AsynchDNS` feature requirement in our `CMakeLists.txt` and checking which `curl` path was logged after `-- Found CURL:`.

**Comment by supervacuus** [comment]
I use the latest `CMake` version on my local dev machines, so some `3.26.x`. In `CI`, we run with `3.16.3`, `3.22.1`, and `3.26.3`.

After a quick look in the `CMake` repo, [comparing](https://github.com/Kitware/CMake/compare/v3.16.3...v3.20.5) the `FindCURL` script, the biggest change seems to be how it handles a `curl` installation if it was built with `CMake`:
https://github.com/Kitware/CMake/commit/c11e7c5c3d5c5e682adf761c4b0de734ff68e690#diff-6fc63538146c7cbfdd878e743382d4bd353e1d11f9c29691e27f4ccb4383d55c

If `3.16.3` works for you, you can try to pass `-DCURL_NO_CURL_CMAKE=On` with `3.20.5` to make the find command almost equivalent between the two versions.

**Comment by Kostiantyn-Zakharchuk-GlobalLogic** [comment]
This flag doesn't help but switching to lower cmake version works.
I have another issue when I try to build sentry with breakpad. Sentry library was build successfully but when I use 
> google_breakpad::MinidumpDescriptor minidump_desc_("/home/kostiantyn");
> google_breakpad::ExceptionHandler handler_(minidump_desc_, nullptr, callback, nullptr, true, -1);
I've get next error: 
**/usr/bin/ld: /tmp/cciH3KDD.o: in function `main':
main.cpp:(.text+0xdb): undefined reference to `google_breakpad::ExceptionHandler::ExceptionHandler(google_breakpad::MinidumpDescriptor const&, bool (*)(void*), bool (*)(google_breakpad::MinidumpDescriptor const&, void*, bool), void*, bool, int)'
collect2: error: ld returned 1 exit status**

It fixes when I explicitly add breakpad_lib to build process.
@supervacuus Can you please explain why?

**Comment by supervacuus** [comment]
> It fixes when I explicitly add breakpad_lib to build process.
> @supervacuus Can you please explain why?

We do not expose our backends in the Native SDK. Please do not instantiate an additional exception handler; the Native SDK does that for you. What are you trying to accomplish?

**Comment by supervacuus** [comment]
If you use the Native SDK, there is no need to do this yourself. The Native SDK will do all of this for you. Please follow the docs on setting up a basic environment to capture crashes (and much more): https://docs.sentry.io/platforms/native/#configure . With the Native SDK, you only choose the backend you want us to defer to in case of a crash but never have to interact with their API.

On the other hand, if you want to use breakpad directly, you don't need to use the Native SDK: https://docs.sentry.io/platforms/native/guides/breakpad/#linux-example. This is mostly for users who already have applications running with breakpad but want to use the sentry backend for crash analysis/reporting. We don't recommend going down this route since you'd have to track all the meta-data that goes into a sentry event payload yourself (as opposed to the Native SDK).

**Comment by supervacuus** [comment]
Did you find a solution to your problem?

**Comment by mehulmathur001** [comment]
Hi @supervacuus, I'm facing a similar issue, with AsyncDNS. I haven't installed curl explicitly, just integrated sentry. Getting error on Github CI using cmake version 3.20.1.

Error:   CURL: Required feature AsynchDNS is not found

**Comment by 0x4eadac43** [comment]
You should set CMAKE_PROGRAM_PATH to include {{ curl_install_dir }}/bin in order for FindCURL.cmake to find curl-config executable.

**Comment by supervacuus** [comment]
Thanks for the suggestion, @0x4eadac43.

@mehulmathur001, I recommend creating a new issue even if you face a similar problem (you can always reference that issue). In particular, CMake/dependency errors have a high probability of environmental causes, and it is only guesswork if you don't provide more details.

For instance, the suggestion above (setting the `CMAKE_PROGRAM_PATH` to allow finding `curl-config`) is sensible. Still, it would be interesting (for you and other users) to understand why that is necessary in the first place.

For instance, our CI also runs on GitHub actions, and most of our tests require a transport, which will require `curl` if the platform supports it. Am I correct to assume that you install `CMake` via a non-standard package manager or even build it yourself? We have seen issues with `vcpkg` for instance.
