### ISSUE TITLE
A required debug information file was missing on msys2

### ISSUE THREAD

**Issue by mariuszmaximus** [getsentry/sentry-native#861]
**Description**

I have msys2 , environment clang64, mingw64 and try run sample with sentry. 
But I have problem, always on .....sentry.io I see "There was 1 problem processing this event 
A required debug information file was missing"

Compresed `.sentry-native`

[.sentry-native.zip](https://github.com/getsentry/sentry-native/files/11927096/default.sentry-native.zip)

**When does the problem happen**

- [ ] During build
- [X] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: [Windows 11, 64-bit]
- Compiler: [clang 16.0.4]
- CMake version and config: [cmake:3.26.4, all default only SENTRY_BUILD_SHARED_LIBS=OFF ]

**Steps To Reproduce**

1) I create on .....sentry.io new native project
2) copy/paste sample code to my PC 
3) add in cmake
```
add_executable(x222233344 x.cpp)
target_link_libraries(x222233344 PRIVATE sentry)
target_compile_options(x222233344 PRIVATE -gcodeview)
``` 

4) Add in main exception:  `int *x{nullptr}; *x = 7;`

5) run `x222233344`

6) go to my exception on  .....sentry.io

Problem: **There was 1 problem processing this event 
A required debug information file was missing**

**Log output**

**mingw64 environment compile commands** 
```
[build] [ 99%] Building CXX object CMakeFiles/x222233344.dir/x.cpp.obj
[build] C:\msys64\mingw64\bin\clang++.exe -DSENTRY_BUILD_STATIC @CMakeFiles/x222233344.dir/includes_CXX.rsp -g -std=gnu++17 -gcodeview -MD -MT CMakeFiles/x222233344.dir/x.cpp.obj -MF CMakeFiles\x222233344.dir\x.cpp.obj.d -o CMakeFiles\x222233344.dir\x.cpp.obj -c D:\mariusz\pulpit\gity\_sentry\sentry-native_002\x.cpp
[build] [100%] Linking CXX executable x222233344.exe
[build] C:\msys64\mingw64\bin\cmake.exe -E cmake_link_script CMakeFiles\x222233344.dir\link.txt --verbose=1
[build] C:\msys64\mingw64\bin\cmake.exe -E rm -f CMakeFiles\x222233344.dir/objects.a
[build] C:\msys64\mingw64\bin\llvm-ar.exe qc CMakeFiles\x222233344.dir/objects.a @CMakeFiles\x222233344.dir\objects1.rsp
[build] C:\msys64\mingw64\bin\clang++.exe -g -Wl,--whole-archive CMakeFiles\x222233344.dir/objects.a -Wl,--no-whole-archive -o x222233344.exe -Wl,--out-implib,libx222233344.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\x222233344.dir\linkLibs.rsp
```

**clang64 environment  compile commands** 
```
[build] [1/2  50% :: 0.879] C:\msys64\clang64\bin\clang++.exe -DSENTRY_BUILD_STATIC -ID:/mariusz/pulpit/gity/_sentry/sentry-native_002/include -g -std=gnu++17 -gcodeview -MD -MT CMakeFiles/x222233344.dir/x.cpp.obj -MF CMakeFiles\x222233344.dir\x.cpp.obj.d -o CMakeFiles/x222233344.dir/x.cpp.obj -c D:/mariusz/pulpit/gity/_sentry/sentry-native_002/x.cpp
[build] [2/2 100% :: 1.028] cmd.exe /C "cd . && C:\msys64\clang64\bin\clang++.exe -g  CMakeFiles/x222233344.dir/x.cpp.obj -o x222233344.exe -Wl,--out-implib,libx222233344.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libsentry.a  -ldbghelp  -lshlwapi  -lpthread  crashpad_build/client/libcrashpad_client.a  crashpad_build/util/libcrashpad_util.a  crashpad_build/compat/libcrashpad_compat.a  C:/msys64/clang64/lib/libz.dll.a  -luser32  -lversion  -lwinhttp  crashpad_build/third_party/mini_chromium/libmini_chromium.a  -ladvapi32  -lkernel32  -lrpcrt4  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
```

**Comment by supervacuus** [comment]
Hi, @mariuszmaximus!

Since you didn't state it in your issue comment: did you upload the necessary debug information as described here: https://docs.sentry.io/product/cli/dif/ ? Sentry requires all debug information to be uploaded before it processes a crash event.

If so, can you provide the concrete debug information file the error box requests (you can click it to open it)? You can also scroll down on the event/issue page until you reach the header "Images Loaded" and click on the right-aligned toggle link "Show Details", where you will get a much more detailed explanation for each image (when you click on the "View" button) loaded at the point of the crash.

**Comment by mariuszmaximus** [comment]
Mea culpa, 
I read the documentation (@supervacuus thank you for the link), everything works for me now.

**Comment by supervacuus** [comment]
I'm happy it works for you now, @mariuszmaximus!
