### ISSUE TITLE
Streamline and align the "Getting Started" docs to fit in the new structure

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry-native#869]
### Problem Statement

- The "Getting Started" documentation for sentry-native platforms may not conform to the newly defined format, which includes the steps "Install", "Configure", "Verify", and the optional "Next Steps".
    - The "Verify" step is not always available and it is a very important step that helps the user to verify that the installation and configuration were done correctly.
- New users onboarding with Sentry may find the existing documentation extensive and unclear. The "Getting Started" guide should cover the basics, while more advanced configurations shall live on the [sentry-docs website](https://docs.sentry.io/).
- Some copies and code snippets in the documentation may be outdated.

### Solution Brainstorm

The task goals are as follows:

- Thoroughly review all sentry-native platform documentation, including less commonly used sections, and reorganize their content into structured headings: 'Install,' 'Configure,' 'Verify,' and the optional 'Next Steps.'
- The onboarding documentation should strictly focus on the basics to help users get started. Advanced configurations should be available in the complete documentation on the [sentry-docs website](https://docs.sentry.io/).
- Essential information for new users should be included under the new 'Notes' section in the onboarding documentation.
- Update code snippets and copies as necessary.
- If a "Verify" step is missing, include it in the documentation.

Please refer to the "Frontendend Handbook" guide in our "Sentry" main repository for assistance in adding and updating the getting started docs: [Frontendend Handbook](https://develop.sentry.dev/frontend/working-on-getting-started-docs/). 

**Project:** https://github.com/getsentry/team-sdks/issues/23

**Comment by supervacuus** [comment]
Thanks @priscilawebdev! After a first quick look into the guidelines, I think we're mostly good but we'll review further next week.

**Comment by supervacuus** [comment]
@bitsandfoxes, @markushi and @kahest: can you read the "Getting Started" section in the docs concerning the guidelines? We follow the model, but I am already used to this, so a fresh set of eyes is helpful. We updated that section, particularly with user input, once or twice over the last year.

**Comment by supervacuus** [comment]
ping @bitsandfoxes, @markushi, @kahest

**Comment by markushi** [comment]
I just double checked and compared it side-by-side with Android, looks good to me!

**Comment by priscilawebdev** [comment]
the documentation for the react-native platforms shows extra information:

![image](https://github.com/getsentry/sentry-native/assets/29228205/8a44f046-4451-4ee4-b2ed-50440e212703)


are they really needed? Can we move them to a "Notes" section?

**Comment by priscilawebdev** [comment]
damn yes...you are right! so I checked also "native" (only) and "QT" and the documentation looks good to me! 😉 sorry for the false alarm

**Comment by kahest** [comment]
haha no worries 👍

**Comment by kahest** [comment]
<img width="999" alt="Screenshot 2023-08-17 at 15 45 35" src="https://github.com/getsentry/sentry-native/assets/2005158/2e17fcaa-aebb-4a9d-afa9-597fff8eb919">
This is native atm, looks pretty good in terms of following the "Install - Configure - Verify" format 👍 
@priscilawebdev we can close this if you agree
