### ISSUE TITLE
O_TMPFILE is not available on Centos 7 - sentry-native will not build with the crashpad backend

### ISSUE THREAD

**Issue by zokrovi** [getsentry/sentry-native#870]
**Description**

On Centos 7, O_TMPFILE is not defined in the headers and crashpad will not build.   

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

Centos 7.9. 

- OS: [e.g. Centos 7.9]
- Compiler: [e.g. GCC 9]
- SENTRY_BACKEND=crashpad

The following piece of code causes the problem:
https://github.com/getsentry/crashpad/blob/432ff49ecccc1cdebf1a7646007bb0594ac3481f/util/file/file_io_posix.cc#L169C1-L184C4

The fix should be simple: wrap those lines with an `#ifdef O_TMPFILE`.
If `O_TMPFILE` is unavailable, it will use the fallback below anyway.

**Comment by supervacuus** [comment]
Thanks for the report @zokrovi! I think on Centos 7 (and other distributions which use kernel 3.10.x) we might be able to cleanly fall back on an alternate definition. Will look into and test that.

**Comment by zokrovi** [comment]
Just noticed, this affects breakpad too at this line:
https://github.com/getsentry/breakpad/blob/ba07f4c5fe0e0616e7663d5ab456329dd29fe04e/src/common/linux/scoped_tmpfile.cc#L77

**Comment by JLuse** [comment]
Hello, it has been concluded was that centos 7 was ancient and not worth supporting
