### ISSUE TITLE
Unable to compile crashpad due to missing <stdint.h> #includes (Linux) - fixed in upstream mini_chromium

### ISSUE THREAD

**Issue by past-due** [getsentry/sentry-native#882]
**Description**

Failure to compile crashpad due to missing `<stdint.h>` `#includes`

It looks like mini_chromium _just_ fixed this upstream:
https://chromium.googlesource.com/chromium/mini_chromium/+/eb418ec05f1142fd03cead1ef6201e6bafee7c9a

So updating the mini_chromium submodule is probably desirable: https://github.com/getsentry/crashpad/tree/getsentry/third_party/mini_chromium

> **Note**
> I just happened to notice recent mini_chromium commits moving macOS / iOS files:
> https://chromium.googlesource.com/chromium/mini_chromium/+/f5370228f40bbb8c453e17f6af6c6742858c45d1
> https://chromium.googlesource.com/chromium/mini_chromium/+/e35fc73aa87bb27e10306900b15a18b0e9c7ca42
> 
> So it looks like [the CMakeLists.txt](https://github.com/getsentry/crashpad/blob/getsentry/third_party/mini_chromium/CMakeLists.txt) also needs updating.

**When does the problem happen**

Trying to compile Sentry w/ crashpad on the very latest Freedesktop 23.08 Runtime.

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Comment by supervacuus** [comment]
Thanks for the report @past-due! I will update `crashpad` with upstream soon. I hope the referenced `mini_chromium` was also updated in `crashpad` (we track the DEPS from upstream), otherwise I can test it with the particular commit.

**Comment by supervacuus** [comment]
Okay, it seems that [DEPS](https://chromium.googlesource.com/crashpad/crashpad/+/refs/heads/main/DEPS#48) currently points to [10f39a97650a0fe0b305415c15434443c0690a20](https://chromium.googlesource.com/chromium/mini_chromium/+/10f39a97650a0fe0b305415c15434443c0690a20) which is the parent of the commit you are referring to. I will add this with the next update from upstream.

**Comment by past-due** [comment]
@supervacuus Looks great! 🥳 Any chance a new sentry-native release can be pushed this week?

**Comment by supervacuus** [comment]
https://github.com/getsentry/publish/issues/2788
