### ISSUE TITLE
mingw32 compiles a 32-bit sentry native library to report an error

### ISSUE THREAD

**Issue by new360** [getsentry/sentry-native#890]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

_1_ According to the compilation instructions of Sentry Native, a 32-bit Sentry is compiled
2 entry-native/external/crashpad/util/misc/capture_context_win.asm(342) : Error A2030
: Instruction or register not accepted in current CPU mode

### Expected Result

compiled success,no error

### Actual Result

compiled fail,error

### Product Area

Unknown

**Comment by past-due** [comment]
@new360: For now, you may be able to use the breakpad backend if building for x86 / 32-bit Windows via mingw.
