### ISSUE TITLE
sentry_transaction_finish() like memory leak

### ISSUE THREAD

**Issue by Wzzzx** [getsentry/sentry-native#893]
**Description**

I have found that the sentry_transaction_finish() like memory leak. 

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10 Version 22H2 (Build 19045.3448)
- Compiler:   Visual Studio 16 2019
- CMake version and config: 
     - cmake version 3.26.0-rc3 
     - SENTRY_TRANSPORT=winhttp
     - SENTRY_BACKEND=crashpad
     - SENTRY_LIBRARY_TYPE=SHARED
 - Version: 0.6.0

**Steps To Reproduce**

``` C++

void startPerformenceDemo();
int main() {
        sentry_options_t* m_options = sentry_options_new();
        sentry_options_set_dsn(m_options, kSentryTarget.c_str());
        sentry_options_set_database_path(m_options, ".sentry-native");
        sentry_options_set_traces_sample_rate(m_options, 1.0);
        sentry_options_set_logger(m_options, sentryLogger, nullptr);
        sentry_init(m_options);

        startPerformenceDemo();
}

  void startPerformenceDemo() {
      sentry_span_status_t status = SENTRY_SPAN_STATUS_OK;
      while (true) {
          sentry_transaction_context_t* tx_ctx =
                  sentry_transaction_context_new("name", "operation");
          sentry_transaction_t* tx = sentry_transaction_start(tx_ctx, sentry_value_new_null());

          // do some work
          sentry_span_status_t status = (status == SENTRY_SPAN_STATUS_INTERNAL_ERROR)
                                                ? SENTRY_SPAN_STATUS_OK
                                                : SENTRY_SPAN_STATUS_INTERNAL_ERROR;
          sentry_transaction_set_status(tx, status);
          sentry_transaction_finish(tx);
      }
  }

```
Logger Function
``` C++
    static void sentryLogger(sentry_level_t level, const char* message, va_list args, void*) {
        const int len = std::vsnprintf(NULL, 0, message, args);
        std::vector<char> buffer(len + 1);
        std::vsnprintf(buffer.data(), buffer.size(), message, args);
        std::string msg = std::string(buffer.data(), buffer.size());
        common::trim(msg);

        switch (level) {
        case SENTRY_LEVEL_DEBUG:
            SLOGD(msg);
            break;
        case SENTRY_LEVEL_INFO:
            SLOGI(msg);
            break;
        case SENTRY_LEVEL_WARNING:
            SLOGW(msg);
            break;
        case SENTRY_LEVEL_ERROR:
            SLOGE(msg);
            break;
        case SENTRY_LEVEL_FATAL:
            SLOGC(msg);
            break;
        default:
            SLOGI(msg);
            break;
        }
    }

```

**Log output**

![image](https://github.com/getsentry/sentry-native/assets/16540508/e5f1fd36-fedb-40e9-9d21-2e766704230f)

The void pointer call stack like this:
![image](https://github.com/getsentry/sentry-native/assets/16540508/fdc9ba71-0de3-4541-b7f9-981a6a93966c)
![image](https://github.com/getsentry/sentry-native/assets/16540508/0fcfcd2a-ec04-4917-b8e0-2c526b6fc277)

Sentry Log:
```
[23-10-10 09:18:18:502] [I] [11220:16928] [sentry.cpp:158] sentry sdk version: 0.6.0
[23-10-10 09:18:18:502] [I] [11220:16928] [sentry.cpp:159] sentry sdk name: sentry.native
```

**Comment by supervacuus** [comment]
Hi @Wzzzx. 

I cannot conclude from your repro and the screenshots that there is a leak in `sentry_transaction_finish()`. You highlight two allocations with 8 and 40 bytes, respectively, but which don't account for the number of allocations or the respective size you see in the overview. Also, their allocation age isn't surprising given that these allocations have to live through an HTTP-request life-cycle, and every `sentry_transaction_finish()` will issue an asynchronous HTTP request (which is queued and processed in sequence)!

We have seen in tests that Windows will sometimes allocate a considerable number of bytes to handle HTTP requests coming from `WinHTTP`, if they happen to come in very short succession. Typically, these allocations will normalize to a much lower number after a few seconds. You should be able to see the main culprit if you sort the instance table of your memory snapshot by size and take a look at the top entries.

Can I ask which scenario you are using the transactions in, given that a high transaction frequency like this, will quickly exhaust the quota for performance units?

**Comment by Wzzzx** [comment]
> Hi @Wzzzx.
> 
> I cannot conclude from your repro and the screenshots that there is a leak in `sentry_transaction_finish()`. You highlight two allocations with 8 and 40 bytes, respectively, but which don't account for the number of allocations or the respective size you see in the overview. Also, their allocation age isn't surprising given that these allocations have to live through an HTTP-request life-cycle, and every `sentry_transaction_finish()` will issue an asynchronous HTTP request (which is queued and processed in sequence)!
> 
> We have seen in tests that Windows will sometimes allocate a considerable number of bytes to handle HTTP requests coming from `WinHTTP`, if they happen to come in very short succession. Typically, these allocations will normalize to a much lower number after a few seconds. You should be able to see the main culprit if you sort the instance table of your memory snapshot by size and take a look at the top entries.
> 
> Can I ask which scenario you are using the transactions in, given that a high transaction frequency like this, will quickly exhaust the quota for performance units?

@supervacuus  Thank for reply! I was developing a local service that will handle requests from multiple applications. And I wanna keep trace of the time it takes for each requests to be processed, as well as monitor other resource usages. Before using transactions to monitor performance, I conducted a simple experiment to see if there were any issues. During my testing, I made the thread sleep for a random amount of time. I noticed that during the loop, there was a significant increase in memory usage. So, I removed all unnecessary elements and only kept the essential parts of the interface calls and ran the experiment again. The results indeed showed signs of memory leakage. 
Let me explain the above three pictures. The first one is the snapshot that I take using [vs's Memory Usage snapshots](https://learn.microsoft.com/en-us/visualstudio/profiling/memory-usage-without-debugging2?view=vs-2022#monitor-memory-use) just before and about 10 seconds after the app is running.You can see a significant increase in the amount of memory occupied and the amount allocated. I took a look at some of the object allocation stacks and found that they were created by calling sentry transaction finish, so I've attached snapshot of two allocation stacks.

**Comment by supervacuus** [comment]
Hi @Wzzzx.
 
> Judging from your reply, a large number of requests in a short period of time will inevitably allocate a lot of small objects, it seems that there is no way to avoid this?

That is undoubtedly one part of it. There are just a lot of small allocations that have to live as long as the corresponding requests still need to be finished, and if there are many in-flight requests, then the total will be affected. However, more insight is needed to explain your snapshot's considerable total allocation size of 18284 KiB. The most significant allocations in sentry-land will be buffers for logging (if enabled), paths, and JSON buffers (when the envelopes are serialized).

Given that I see allocations with 256, 344, and 1024 bytes in that small view of the whole snapshot table, I would recommend that you also sort that snapshot table by size to see where the most significant allocations happen (which will account for much more of your total than the sentry allocations). My guess is that they are allocations done by the Windows winhttp/webio/crypto subsystem, which typically allocates many kilo(!) bytes per request and not only a couple of bytes as we do. But even with these, the total heap size would typically get back to a lower level and (more importantly) stop to increase over time.
