### ISSUE TITLE
Using `sentry_set_user` but no users show up in dashboards

### ISSUE THREAD

**Issue by connorjclark** [getsentry/sentry-native#911]
**Description**

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: windows, mac, linux
- Compiler: msvc/clang
- CMake version and config: [e.g. 3.17.2, SENTRY_BACKEND=inproc]

**Steps To Reproduce**

I have roughly this code:

```cpp
sentry_init(options);
// ...
sentry_value_t user = sentry_value_new_object();
sentry_value_set_by_key(user, "ip_address", sentry_value_new_string("{{auto}}"));
sentry_set_user(user);
```

(full context [here](https://github.com/ZQuestClassic/ZQuestClassic/blob/2637fc6aceb942f133878d20623428c4857003a0/src/base/zapp.cpp#L54-L84))

My interpretation based on the [docs](https://docs.sentry.io/platforms/native/enriching-events/identify-user/#ip_address) is that this should create a unique user for this user, at least until their IP address changes. However, I get 0 users in the various surfaces in the dashboard that deal with user related stuff. Sessions work just fine, but no user information.

Am I using this API incorrectly?

**Comment by supervacuus** [comment]
Thanks for the report, @connorjclark.  The API usage is okay, and I expect events to be shown with an IP address representing users and counting them accordingly.

Can someone look at the events(@kahest, @markushi, @Swatinem)? There is a DSN in the referenced "context". Could this be PII settings related?

**Comment by kahest** [comment]
@connorjclark do you have storing of IP addresses enabled for the project on sentry.io? See the docs:

> To opt out of storing users' IP addresses in your event data, you can go to your projectRepresents your service in Sentry and allows you to scope events to a distinct application. settings, click on "Security & Privacy", and enable "Prevent Storing of IP Addresses"

This setting is used on the backend to determine whether IP addresses should be resolved and stored for incoming events where `ip_address` is set to `{{auto}}`.

**Comment by kahest** [comment]
@connorjclark got it, please let us know if that solved your issue. This is something we could communicate on the docs more clearly I feel.

**Comment by kahest** [comment]
@connorjclark thanks for reporting back - this should work, we'll need to investigate

**Comment by kahest** [comment]
@connorjclark for User stats in Release Health, at least one of `id`, `email` or `username` of the user need to be set (see https://github.com/getsentry/sentry-native/blob/d88cd769f0cf091a2bac851a40af9bd6d5bf71d5/src/sentry_session.c#L307-L316). Apologies for the confusion, I see that this is not clearly communicated in the docs and we'll look to improve this.

**Comment by kahest** [comment]
@supervacuus yep I'm clarifying this internally and will follow up with docs updates and GH issues if necessary
