### ISSUE TITLE
sentry-native is missing tracing functions (e.g. continueTrace)

### ISSUE THREAD

**Issue by MattJustMatt** [getsentry/sentry-native#916]
We are attempting to integrate sentry tracing across our stack but looking through the docs, source, headers for sentry-native it doesn't appear that tracing is supported. 

This is a blocker for our tracing deployment since most of our core logic happens in C++ land. 

If there's a quick path to getting this implemented I would love it, otherwise I can look at contributing down the line. 

Thanks for looking!

**Comment by supervacuus** [comment]
This is being fixed as part of https://github.com/getsentry/sentry-docs/pull/8842. Feel free to reopen if there is something missing.
