### ISSUE TITLE
Support for nuget packages

### ISSUE THREAD

**Issue by compnerd** [getsentry/sentry-native#918]
When using sentry on Windows, it is convenient to treat the native SDK as a nuget package for easy integration into Windows products.  If this is of interest, we have build some automation via GHA for building the nuget packages, and hosting via GH Packages.  If this is of interest, we could send you a PR to integrate that into your releases.

**Comment by compnerd** [comment]
CC: @supervacuus

**Comment by supervacuus** [comment]
As I answered in the other issue, binary releases can make sense for Windows. Still, they would have to reflect all the combinations of backend, shared/static sentry, and shared/static runtime (architecture when ARM64 runners are available) to be broadly helpful. Nuget would then be the dot to the i.

Let's leave this here for users to vote.

**Comment by compnerd** [comment]
The is not arm64 specific, but architecture neutral.  Right, for the other backends, it should be possible to build and have a matrix of builds and packages that would allow you to have the other variants as well.

**Comment by vslavik** [comment]
FWIW, I build unofficial package [^1] at https://github.com/vslavik/nuget-sentry-native. I explicitly put the packaging code in public domain, so feel free to reuse should you decide to provide nuget packages.

[^1]: Default config, x86+x64 but w/o ARM64 where sentry-native fails to compile.
