### ISSUE TITLE
Build failure with Crashpad and aarch64

### ISSUE THREAD

**Issue by petrmanek** [getsentry/sentry-native#936]
Hi, after upgrading to v0.7.0 I started seeing a build failure with Linux Crashpad backend under aarch64. Note that the same code compiles perfectly under x86_64.

I believe that the cause is [this assembly instruction](https://github.com/getsentry/crashpad/blob/89991e9910bc4c0893e45c8cfad0bdd31cc25a5c/util/linux/pac_helper.cc#L37) that requires pointer authentication. I found a [related conversation in a mailing list](https://groups.google.com/a/chromium.org/g/crashpad-dev/c/Pznm3UuIi5Y/m/YYERt5lwAwAJ) that suggests that this can be resolved by upgrading to a more modern clang version. I am verifying that now, nevertheless you should be aware that this issue exists.

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Linux, [Ubuntu Focal 20.04 (in Docker)](https://git.launchpad.net/cloud-images/+oci/ubuntu-base/tree/oci/index.json?h=refs/tags/dist-focal-amd64-20231211-1c7098d1&id=1c7098d1f72badd8cc2d425da3e2aacbe394fb7d), aarch64
- Compiler: [clang-10](http://ports.ubuntu.com/pool/universe/l/llvm-defaults/clang_10.0-50~exp1_arm64.deb) from official repository
- CMake version and config: 3.27.5, SENTRY_ENABLE_INSTALL=ON, SENTRY_BUILD_EXAMPLES=ON

**Steps To Reproduce**

1. Compile sentry-native under the given architecture with the given toolchain and configuration
2. Observe build error

**Log output**

```
FAILED: lib/sentry/crashpad_build/util/CMakeFiles/crashpad_util.dir/linux/pac_helper.cc.o 
/usr/bin/clang++ -DCRASHPAD_FLOCK_ALWAYS_SUPPORTED=1 -DCRASHPAD_LSS_SOURCE_EMBEDDED -DCRASHPAD_ZLIB_SOURCE_SYSTEM -DTL_CMAKE_PROJECT_VERSION=\"1.4.0\" -DZLIB_CONST -I/app/build/release/lib/sentry/crashpad_build/util/crashpad_util_autogen/include -I/app/lib/sentry/external/crashpad -I/app/lib/sentry/external/crashpad/third_party/mini_chromium/mini_chromium -I/app/lib/sentry/external/crashpad/compat/non_win -I/app/lib/sentry/external/crashpad/compat/linux -I/app/lib/sentry/external/crashpad/third_party/mini_chromium -g -DNDEBUG -O3 -std=gnu++17 -fPIC -fcolor-diagnostics -MD -MT lib/sentry/crashpad_build/util/CMakeFiles/crashpad_util.dir/linux/pac_helper.cc.o -MF lib/sentry/crashpad_build/util/CMakeFiles/crashpad_util.dir/linux/pac_helper.cc.o.d -o lib/sentry/crashpad_build/util/CMakeFiles/crashpad_util.dir/linux/pac_helper.cc.o -c /app/lib/sentry/external/crashpad/util/linux/pac_helper.cc
/app/lib/sentry/external/crashpad/util/linux/pac_helper.cc:37:9: error: instruction requires: pa
    asm("xpaclri" : "+r"(x30));
        ^
<inline asm>:1:2: note: instantiated into assembly here
        xpaclri
        ^
```

**Comment by supervacuus** [comment]
Thanks for the info @petrmanek!

**Comment by petrmanek** [comment]
Yes, I can confirm that upgrading clang helps. :tada:  Tested it yesterday with clang 12 but theoretically clang 11 should be sufficient.
