### ISSUE TITLE
Add Linux distro meta-data to OS context.

### ISSUE THREAD

**Issue by supervacuus** [getsentry/sentry-native#943]
### Discussed in https://github.com/getsentry/sentry-native/discussions/942

<div type='discussions-op-text'>

<sup>Originally posted by **tkatsoulas** February  1, 2024</sup>
Hello guys, 

The current implementation to understand the host OS https://github.com/getsentry/sentry-native/blob/master/src/sentry_os.c provides poor information for any distro. Are there any plans to update them? For instance `/etc/os-releases` file is there for most* of the Linux distros and can provide detailed information about a host. The current mechanisms can be used as a fallback. 

Thanks in advance, 
Tasos.</div>

CC: @kahest would be interesting if other SDKs already have a tag reserved for this information.

**Comment by kahest** [comment]
related: https://github.com/getsentry/sentry-native/pull/467#issuecomment-768985938

**Comment by supervacuus** [comment]
Hi @tkatsoulas, can I ask you: would you want to use this for searching and filtering issues (requiring us to index the field in the backend and consider cardinality), or would it suffice as an additional data item that you look up per event? Thx!

**Comment by tkatsoulas** [comment]
The first one. I think your current pipelines will work if we just transform the current os and os.name to something more useful rather than  
![Screenshot from 2024-02-15 18-29-29](https://github.com/getsentry/sentry-native/assets/12612986/ac546aef-987e-4abe-9b8d-55f241698317)

If more information about a distro (like OS: Linux OS.name: Fedora OS.version:38) can be indexed it will be match appreciated.

This can give you a concrete view of what distros are affected by the same/similar issue.

Didn't had the time to work on the open-source contribution but I think I can have a draft PR by Monday.

**Comment by supervacuus** [comment]
Hi @tkatsoulas, thanks. I expected that you want to be able to filter it; I just wanted to make sure.

Changing the meaning of existing os-context properties is not a good idea: it would immediately split existing events from future events, which currently would appear in the same filter results.

Some customers want to differentiate between broad OS categories (Win, macOS, Linux, ...), and `os.name` is the right os-context key, changing its meaning would invalidate existing dashboards. 

A new key (+ sub-keys?) for distributions would be preferable, and we will discuss this internally with the ingest team regarding the right path.

Please wait with any time investment on your part until this is clarified since this isn't solely a client SDK issue.

**Comment by p0358** [comment]
One can also add Wine metadata to the context if the app is ran under that:
```cpp
{
    // Add WINE version metadata if running under WINE
    HMODULE hntdll;
    typedef const char* (CDECL* wine_get_version_t)();
    typedef const char* (CDECL* wine_get_build_id_t)();
    typedef void (CDECL* wine_get_host_version_t)(const char** sysname, const char** release);
    wine_get_version_t wine_get_version;
    wine_get_build_id_t wine_get_build_id;
    wine_get_host_version_t wine_get_host_version;
    if ((hntdll = GetModuleHandleA("ntdll.dll")) && (wine_get_version = reinterpret_cast<wine_get_version_t>(GetProcAddress(hntdll, "wine_get_version"))))
    {
        sentry_value_t wine_ctx = sentry_value_new_object();

        sentry_value_set_by_key(wine_ctx, "version", sentry_value_new_string(wine_get_version())); // example: 7.11
        if (wine_get_build_id = reinterpret_cast<wine_get_build_id_t>(GetProcAddress(hntdll, "wine_get_build_id")))
            sentry_value_set_by_key(wine_ctx, "build", sentry_value_new_string(wine_get_build_id())); // example: wine-7.11
        if (wine_get_host_version = reinterpret_cast<wine_get_host_version_t>(GetProcAddress(hntdll, "wine_get_host_version")))
        {
            const char* sysname; // example: Linux
            const char* release; // example: 5.16.20-2-MANJARO
            wine_get_host_version(&sysname, &release);
            sentry_value_set_by_key(wine_ctx, "sysname", sentry_value_new_string(sysname));
            sentry_value_set_by_key(wine_ctx, "release", sentry_value_new_string(release));
        }

        sentry_set_context("wine", wine_ctx);
    }
}
```

**Comment by supervacuus** [comment]
> One can also add Wine metadata to the context if the app is ran under that:

The effort here is definitely not in the Native SDK but in everything behind that. This issue and related PRs are not fixed/released yet because there are still issues with the lookup of the new context format in clickhouse. Let's track this separately.
