### ISSUE TITLE
[native] Add support for Sentry Metrics

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-native#953]
### Description
Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, including the Native SDK

*this will also enable that our Unreal Game Engine SDK could support Metrics

#### Requirements:

- [ ] API for sending Metrics, add protocol definitions for sending statsd envelope items
- [ ] Metrics Summary
- [ ] Code location, linking metrics to source code
- [ ] Tag normalization

#### Document(s)
[Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
[SDK Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)
[Product Specs](https://develop.sentry.dev/sdk/metrics/)

**Comment by JoshuaMoelans** [comment]
Closing since Metrics have been deprecated.
