### ISSUE TITLE
sentry_set_user() crashes when called after sentry_init()

### ISSUE THREAD

**Issue by matok** [getsentry/sentry-native#96]
## Important details

- Saas (sentry.io)
- mac (10.15)
- built from release 0.1.2
- sentry with crashpad backend

## Description

Invoking `sentry_set_user()` before `sentry_init()` works fine, all following events are tagged with provided user details, but when it's called after `sentry_init`, it crashes on BAD_ACCESS because of NULL `FILE*` pointer `writer->context` in `mpack_file_writer_flush`.

I don't know whether this is an expected behaviour, but it would be nice if we could change user details after initialization.

![sentry_crash_vars](https://user-images.githubusercontent.com/1105117/69349633-5af78080-0c78-11ea-89d0-d9827cb69d94.png)
![sentry_crash_stack](https://user-images.githubusercontent.com/1105117/69349638-5d59da80-0c78-11ea-853b-20c64b9f7e11.png)
![sentry_crash_code](https://user-images.githubusercontent.com/1105117/69349642-5fbc3480-0c78-11ea-8166-df6410103207.png)

**Comment by matok** [comment]
I just compiled the same code on windows, also with crashpad backend and it doesn't crash.

**Comment by mitsuhiko** [comment]
This might be the same core issues as #84. It fails to open the event file. I'm adding a fix for the crash in but it won't make the user data show up yet.
