### ISSUE TITLE
[#inc-517] Document caveats of signalhandlers and sigaltstack

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-native#960]
Document various aspects around signaldhandlers, memory usage, custom sigaltstacks, etc.
- how we use sigaltstacks
- what to consider when writing onCrash hooks
- etc.

**Comment by supervacuus** [comment]
This document already covers a lot of ground: https://develop.sentry.dev/sdk/signal-handlers/

Everything in that document applies to `on_crash`/`before_send` hooks executed on any Linux system (including Android).

I wouldn't add `sigaltstack` usage before we have a __very__ clear idea of what is safe in the context of Android. So, the question is whether this should be added to that document or whether we should reference the signal-handler description to Android-specific docs.

**Comment by kahest** [comment]
IMO we should have a place on the user-facing Native and Android docs where we call out (on a high level) that signal handlers require special considerations - and then linking to the develop docs should be fine.
As for `sigaltstack`, I wouldn't give any suggestions or advice - rather, I'd include `sigaltstack` in the callout above, if at all. Once/if we have more clear guidance, we can think about where to put this.

**Comment by supervacuus** [comment]
Great, I think this fits well within the bounds of the discussed "Advanced Usage" section of the user docs because most of the planned information is about the OS-specific mechanism or exceptional behavior. sentry-android docs can link there.
