### ISSUE TITLE
[Android] Support dynamic page size for Android 15+ devices

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-native#989]
See https://developer.android.com/about/versions/15/behavior-changes-all#16-kb for more details.

> Beginning with Android 15, Android supports devices that are configured to use a page size of 16 KB (16 KB devices). If your app uses any NDK libraries, either directly or indirectly through an SDK, then you will need to rebuild your app for it to work on these 16 KB devices.

**Comment by yousrasd** [comment]
Do we have an update on this? Android 15 will soon rollout and this could be a blocker for apps.

**Comment by kahest** [comment]
@yousrasd thanks for checking in - we have it on our radar and we're preparing patches for this
